Repository CompaniTech/compani-webapp, pull requests merged in 2020-12, with the labels that each got.

#834 From camel case to kebab case
  src/core/data/constants.js
  src/css/planning.styl
  src/modules/client/pages/ni/config/RhConfig.vue
Labels: dev

#829 Com 1655 - Tabs
  src/core/components/learners/ProfileCourses.vue
  src/core/components/table/ResponsiveTable.vue
  src/core/mixins/courseFollowUpMixin.js
  src/css/table.styl
  src/modules/vendor/components/courses/ProfileAccess.vue
  src/modules/vendor/components/courses/ProfileFollowUp.vue
  src/modules/vendor/pages/ni/management/ELearningCourseProfile.vue
  src/modules/vendor/router/routes.js
Labels: dev

#828 COM-1658 add category select to program creation
  src/modules/vendor/components/programs/ProgramCreationModal.vue
  src/modules/vendor/pages/ni/config/CategoriesDirectory.vue
  src/modules/vendor/pages/ni/config/ProgramsDirectory.vue
Labels: dev

#835 Com 1655 - POST
  src/core/api/Courses.js
  src/modules/vendor/components/courses/AccessRuleCreationModal.vue
  src/modules/vendor/components/courses/ProfileAccess.vue
Labels: dev

#837 Refacto
  src/core/api/Surcharges.js
  src/modules/client/pages/ni/config/CustomersConfig.vue
Labels: dev

#836 Com 1662
  src/core/components/BiColorButton.vue
  src/core/components/CopyButton.vue
  src/core/components/courses/ProfileOrganization.vue
  src/core/components/courses/TraineeTable.vue
Labels: dev

#838 COM-1660 - add learning goals
  src/core/components/courses/ProfileAdmin.vue
  src/modules/vendor/components/programs/ProfileInfo.vue
Labels: dev

#842 COM-1668 set sameSite cookies to lax
  src/core/helpers/alenvi.js
  src/core/mixins/logInMixin.js
  src/router/redirect.js
Labels: dev

#839 COM-1662 - Refacto ProfileAdmin
  src/core/components/BiColorButton.vue
  src/core/components/courses/CourseInfoLink.vue
  src/core/components/courses/ProfileAdmin.vue
  src/core/components/courses/TraineeTable.vue
Labels: dev

#844 Com 1698
  src/core/api/Users.js
  src/core/components/PictureUploader.vue
Labels: dev

#840 Com 1659
  src/core/api/Programs.js
  src/modules/vendor/components/programs/CategoryAdditionModal.vue
  src/modules/vendor/components/programs/ProfileInfo.vue
Labels: dev

#843 Com 1661
  src/core/api/Courses.js
  src/core/components/courses/CourseInfoLink.vue
  src/core/components/courses/ProfileAdmin.vue
  src/core/pages/courses/BlendedCourseInfo.vue
  src/router/routes.js
Labels: dev

#845 Com 1677 learnerDirectoryMixin
  src/core/mixins/learnerDirectoryMixin.js
  src/modules/client/pages/ni/courses/LearnersDirectory.vue
  src/modules/vendor/pages/ni/users/learners/LearnersDirectory.vue
Labels: dev

#846 COM-1655 - Add delete route
  src/core/api/Courses.js
  src/modules/vendor/components/courses/ProfileAccess.vue
Labels: dev

#849 COM-1655 - Fix
  src/modules/vendor/components/courses/ProfileAccess.vue
Labels: dev

#850 MES
  src/modules/vendor/components/courses/ProfileAccess.vue
Labels: staging

#852 COM-1716 npm update
  package-lock.json
  package.json
Labels: dev

#854 Com 1725
  src/core/components/courses/ProfileAdmin.vue
Labels: bug

#853 COM-1689 - remove x-access-token from bills pdf url
  src/core/api/Bills.js
  src/core/helpers/file.js
  src/core/pages/DisplayPdf.vue
  src/modules/client/components/customers/billing/CustomerBillingTable.vue
  src/router/routes.js
Labels: dev

#855 COM-1711 add origin in authentication payload
  src/core/data/constants.js
  src/core/mixins/logInMixin.js
Labels: dev

#856 Com 1691 - refacto qcm/qcu/questionAnswers
  src/core/helpers/vuelidateCustomVal.js
  src/modules/vendor/components/programs/cards/templates/MultipleChoiceQuestion.vue
  src/modules/vendor/components/programs/cards/templates/QuestionAnswer.vue
  src/modules/vendor/components/programs/cards/templates/SingleChoiceQuestion.vue
Labels: dev

#858 Com 1699 planning
  src/modules/client/components/customers/EventConflictModal.vue
  src/modules/client/components/planning/Agenda.vue
  src/modules/client/components/planning/PlanningEvent.vue
  src/modules/client/mixins/planningEventMixin.js
  src/modules/client/pages/auxiliaries/planning/AuxiliaryAgenda.vue
  src/modules/client/pages/customers/CustomerAgenda.vue
Labels: dev

#859 COM-1710 - add origin in user creation
  src/core/api/Users.js
Labels: dev

#860 COM-1699 - fix overflow
  src/css/planning.styl
Labels: dev

#862 Com 1691 put
  src/modules/vendor/components/programs/cards/templates/MultipleChoiceQuestion.vue
  src/modules/vendor/components/programs/cards/templates/QuestionAnswer.vue
  src/modules/vendor/components/programs/cards/templates/SingleChoiceQuestion.vue
  src/modules/vendor/mixins/templateMixin.js
Labels: dev

#861 Com 1694 expandingTable
  src/core/components/CourseProgress.vue
  src/core/components/learners/ProfileCourses.vue
  src/modules/vendor/components/courses/ProfileFollowUp.vue
Labels: dev

#865 COM-1694 exported expanding table
  src/core/components/learners/ProfileCourses.vue
  src/core/components/table/ExpandingTable.vue
Labels: dev

#863 Com 1691 - post
  src/modules/vendor/components/programs/cards/templates/MultipleChoiceQuestion.vue
  src/modules/vendor/components/programs/cards/templates/QuestionAnswer.vue
  src/modules/vendor/components/programs/cards/templates/SingleChoiceQuestion.vue
  src/modules/vendor/mixins/templateMixin.js
Labels: dev

#864 Com 1691 - delete
  src/core/data/constants.js
  src/modules/vendor/components/programs/cards/templates/MultipleChoiceQuestion.vue
  src/modules/vendor/components/programs/cards/templates/QuestionAnswer.vue
  src/modules/vendor/components/programs/cards/templates/SingleChoiceQuestion.vue
  src/modules/vendor/mixins/templateMixin.js
Labels: dev

#867 Com 1690 get
  src/core/data/constants.js
  src/modules/vendor/components/programs/cards/templates/OrderTheSequence.vue
  src/modules/vendor/mixins/templateMixin.js
Labels: dev

#868 Com 1691 class
  src/modules/vendor/components/programs/cards/templates/MultipleChoiceQuestion.vue
  src/modules/vendor/components/programs/cards/templates/QuestionAnswer.vue
  src/modules/vendor/components/programs/cards/templates/SingleChoiceQuestion.vue
Labels: dev

#869 Com 1690 post delete orderedAnswers
  src/modules/vendor/components/programs/cards/templates/OrderTheSequence.vue
Labels: dev

#870 Com 1693 - refacto put
  src/core/data/constants.js
  src/modules/vendor/components/programs/cards/templates/FillTheGaps.vue
  src/modules/vendor/mixins/templateMixin.js
Labels: dev

#873 Com 1708
  src/modules/vendor/components/programs/ProgramCreationModal.vue
  src/modules/vendor/pages/ni/config/ProgramsDirectory.vue
Labels: dev

#871 Com 1693 post delete
  src/modules/vendor/components/programs/cards/templates/FillTheGaps.vue
Labels: dev

#874 COM-1700 rules to publish sub-program
  src/modules/vendor/components/programs/ProfileContent.vue
Labels: dev

#876 COM-1693 using constants
  src/css/app.styl
  src/modules/vendor/components/programs/cards/templates/FillTheGaps.vue
  src/modules/vendor/components/programs/cards/templates/MultipleChoiceQuestion.vue
  src/modules/vendor/components/programs/cards/templates/OrderTheSequence.vue
  src/modules/vendor/components/programs/cards/templates/QuestionAnswer.vue
  src/modules/vendor/components/programs/cards/templates/SingleChoiceQuestion.vue
Labels: dev

#877 Com 1740 fix no mutating props chapter one
  src/modules/vendor/components/programs/ActivityCreationModal.vue
  src/modules/vendor/components/programs/ActivityEditionModal.vue
  src/modules/vendor/components/programs/CategoryCreationModal.vue
  src/modules/vendor/components/programs/CategoryEditionModal.vue
  src/modules/vendor/components/programs/ProfileContent.vue
  src/modules/vendor/components/programs/StepCreationModal.vue
  src/modules/vendor/components/programs/StepEditionModal.vue
  src/modules/vendor/components/programs/SubProgramCreationModal.vue
  src/modules/vendor/pages/ni/config/CategoriesDirectory.vue
Labels: bug

#878 MES
  package-lock.json
  package.json
  src/core/api/BillSlips.js
  src/core/api/Bills.js
  src/core/api/Courses.js
  src/core/api/CreditNotes.js
  src/core/api/TaxCertificates.js
  src/core/api/Users.js
  src/core/components/CourseProgress.vue
  src/core/components/courses/CourseInfoLink.vue
  src/core/components/courses/ProfileAdmin.vue
  src/core/components/learners/ProfileCourses.vue
  src/core/components/table/ExpandingTable.vue
  src/core/data/constants.js
  src/core/helpers/file.js
  src/core/helpers/vuelidateCustomVal.js
  src/core/mixins/logInMixin.js
  src/core/pages/DisplayPdf.vue
  src/css/app.styl
  src/css/planning.styl
  src/modules/client/components/contracts/ContractsCell.vue
  src/modules/client/components/customers/EventConflictModal.vue
  src/modules/client/components/customers/billing/CustomerBillingTable.vue
  src/modules/client/components/customers/billing/ProfileBilling.vue
  src/modules/client/components/customers/infos/ProfileInfo.vue
  src/modules/client/components/planning/Agenda.vue
  src/modules/client/components/planning/PlanningEvent.vue
  src/modules/client/mixins/planningEventMixin.js
  src/modules/client/pages/auxiliaries/planning/AuxiliaryAgenda.vue
  src/modules/client/pages/customers/CustomerAgenda.vue
  src/modules/client/pages/ni/billing/TppBillSlips.vue
  src/modules/vendor/components/courses/ProfileFollowUp.vue
  src/modules/vendor/components/programs/ActivityCreationModal.vue
  src/modules/vendor/components/programs/ActivityEditionModal.vue
  src/modules/vendor/components/programs/CategoryCreationModal.vue
  src/modules/vendor/components/programs/CategoryEditionModal.vue
  src/modules/vendor/components/programs/ProfileContent.vue
  src/modules/vendor/components/programs/ProgramCreationModal.vue
  src/modules/vendor/components/programs/StepCreationModal.vue
  src/modules/vendor/components/programs/StepEditionModal.vue
  src/modules/vendor/components/programs/SubProgramCreationModal.vue
  src/modules/vendor/components/programs/cards/templates/FillTheGaps.vue
  src/modules/vendor/components/programs/cards/templates/MultipleChoiceQuestion.vue
  src/modules/vendor/components/programs/cards/templates/OrderTheSequence.vue
  src/modules/vendor/components/programs/cards/templates/QuestionAnswer.vue
  src/modules/vendor/components/programs/cards/templates/SingleChoiceQuestion.vue
  src/modules/vendor/mixins/templateMixin.js
  src/modules/vendor/pages/ni/config/CategoriesDirectory.vue
  src/modules/vendor/pages/ni/config/ProgramsDirectory.vue
  src/router/routes.js
Labels: staging

#879 COM-1732 update axios
  package-lock.json
  package.json
Labels: dev

#875 Com 1689 cookies
  src/core/api/Users.js
  src/core/api/ressources/alenviAxios.js
  src/core/components/form/FileUploader.vue
  src/core/helpers/alenvi.js
  src/core/mixins/logInMixin.js
  src/core/pages/signin/Authenticate.vue
  src/core/pages/signin/ForgotPassword.vue
  src/core/pages/signin/ResetPassword.vue
  src/modules/client/components/contracts/ContractsCell.vue
  src/modules/client/components/customers/infos/ProfileInfo.vue
  src/modules/client/layouts/Layout.vue
  src/router/index.js
  src/router/redirect.js
  test/cypress/integration/authenticate.spec.js
  test/cypress/integration/customer/agenda.spec.js
  test/cypress/integration/customer/billing.spec.js
  test/cypress/integration/customer/subscription.spec.js
  test/cypress/integration/ni/billing/toBill.spec.js
  test/cypress/support/index.js
Labels: dev

#880 COM-1734 npm update
  package-lock.json
  package.json
Labels: dev

#882 MEP
  package-lock.json
  package.json
  src/core/api/BillSlips.js
  src/core/api/Bills.js
  src/core/api/Courses.js
  src/core/api/CreditNotes.js
  src/core/api/TaxCertificates.js
  src/core/api/Users.js
  src/core/components/CourseProgress.vue
  src/core/components/courses/CourseInfoLink.vue
  src/core/components/courses/ProfileAdmin.vue
  src/core/components/learners/ProfileCourses.vue
  src/core/components/table/ExpandingTable.vue
  src/core/data/constants.js
  src/core/helpers/file.js
  src/core/helpers/vuelidateCustomVal.js
  src/core/mixins/logInMixin.js
  src/core/pages/DisplayPdf.vue
  src/css/app.styl
  src/css/planning.styl
  src/modules/client/components/contracts/ContractsCell.vue
  src/modules/client/components/customers/EventConflictModal.vue
  src/modules/client/components/customers/billing/CustomerBillingTable.vue
  src/modules/client/components/customers/billing/ProfileBilling.vue
  src/modules/client/components/customers/infos/ProfileInfo.vue
  src/modules/client/components/planning/Agenda.vue
  src/modules/client/components/planning/PlanningEvent.vue
  src/modules/client/mixins/planningEventMixin.js
  src/modules/client/pages/auxiliaries/planning/AuxiliaryAgenda.vue
  src/modules/client/pages/customers/CustomerAgenda.vue
  src/modules/client/pages/ni/billing/TppBillSlips.vue
  src/modules/vendor/components/courses/ProfileFollowUp.vue
  src/modules/vendor/components/programs/ActivityCreationModal.vue
  src/modules/vendor/components/programs/ActivityEditionModal.vue
  src/modules/vendor/components/programs/CategoryCreationModal.vue
  src/modules/vendor/components/programs/CategoryEditionModal.vue
  src/modules/vendor/components/programs/ProfileContent.vue
  src/modules/vendor/components/programs/ProgramCreationModal.vue
  src/modules/vendor/components/programs/StepCreationModal.vue
  src/modules/vendor/components/programs/StepEditionModal.vue
  src/modules/vendor/components/programs/SubProgramCreationModal.vue
  src/modules/vendor/components/programs/cards/templates/FillTheGaps.vue
  src/modules/vendor/components/programs/cards/templates/MultipleChoiceQuestion.vue
  src/modules/vendor/components/programs/cards/templates/OrderTheSequence.vue
  src/modules/vendor/components/programs/cards/templates/QuestionAnswer.vue
  src/modules/vendor/components/programs/cards/templates/SingleChoiceQuestion.vue
  src/modules/vendor/mixins/templateMixin.js
  src/modules/vendor/pages/ni/config/CategoriesDirectory.vue
  src/modules/vendor/pages/ni/config/ProgramsDirectory.vue
  src/router/routes.js
Labels: master

#881 Com 1738 fix no-mutating prop
  src/core/components/courses/SlotContainer.vue
  src/core/components/courses/SlotCreationModal.vue
  src/core/components/courses/SlotEditionModal.vue
  src/modules/vendor/components/companies/CompanyCreationModal.vue
  src/modules/vendor/components/courses/CourseCreationModal.vue
  src/modules/vendor/pages/ni/management/BlendedCoursesDirectory.vue
  src/modules/vendor/pages/ni/users/companies/CompaniesDirectory.vue
Labels: dev

#885 MEP
  src/modules/client/components/planning/Agenda.vue
  src/modules/client/pages/customers/CustomerAgenda.vue
Labels: master

#886 COM-1689 - create authentication files
  src/core/api/Authentication.js
  src/core/api/Users.js
  src/core/helpers/alenvi.js
  src/core/mixins/logInMixin.js
  src/core/pages/AccountInfo.vue
  src/core/pages/signin/ForgotPassword.vue
  src/core/pages/signin/ResetPassword.vue
  src/modules/client/components/auxiliary/AuxiliaryProfileHeader.vue
  src/modules/client/pages/ni/auxiliaries/Directory.vue
  src/router/redirect.js
Labels: dev

#887 Com 1738
  src/core/components/courses/LearnerCreationModal.vue
  src/core/components/courses/ProfileAdmin.vue
  src/core/components/courses/SmsDetailsModal.vue
  src/core/components/courses/SmsSendingModal.vue
  src/core/components/courses/TraineeEditionModal.vue
  src/core/components/courses/TraineeTable.vue
  src/modules/client/pages/ni/courses/LearnersDirectory.vue
  src/modules/vendor/components/courses/AccessRuleCreationModal.vue
  src/modules/vendor/components/courses/ProfileAccess.vue
  src/modules/vendor/components/trainers/TrainerCreationModal.vue
  src/modules/vendor/pages/ni/users/trainers/TrainersDirectory.vue
Labels: dev

#889 Com 1736 remove Cloudinary
  quasar.conf.js
  src/core/api/Cloudinary.js
  src/core/components/form/CustomImg.vue
  src/core/components/form/FileUploader.vue
  src/core/components/form/MultipleFilesUploader.vue
  src/modules/client/components/auxiliary/ProfileInfo.vue
  src/modules/client/components/customers/infos/ProfileInfo.vue
  src/modules/client/components/planning/EventCreationModal.vue
  src/modules/client/components/planning/EventEditionModal.vue
  src/modules/client/pages/customers/Subscriptions.vue
  src/modules/client/pages/ni/config/CustomersConfig.vue
  src/modules/client/pages/ni/config/RhConfig.vue
  src/modules/vendor/components/programs/ProfileInfo.vue
  src/modules/vendor/components/programs/cards/templates/TextMedia.vue
  src/modules/vendor/components/programs/cards/templates/TitleTextMedia.vue
Labels: dev

#891 COM-1736 - move link from cloudinary to GCS
  public/favicon_metadata/browserconfig.xml
  public/favicon_metadata/site.webmanifest
  src/core/components/menu/SideMenuFooter.vue
  src/core/data/constants.js
  src/core/mixins/sideMenuMixin.js
  src/index.template.html
Labels: dev

#894 Com 1719
  src/core/components/ProfileTabs.vue
  src/core/components/courses/ProfileAdmin.vue
  src/core/components/table/Pagination.vue
  src/core/components/table/SimpleTable.vue
  src/css/table.styl
  src/modules/client/components/auxiliary/ProfilePay.vue
  src/modules/client/components/customers/ProfileFollowUp.vue
  src/modules/client/components/customers/billing/CustomerBillingTable.vue
  src/modules/client/pages/auxiliaries/administrative/Documents.vue
  src/modules/client/pages/ni/auxiliaries/StaffRegister.vue
  src/modules/client/pages/ni/billing/ClientsBalances.vue
  src/modules/client/pages/ni/billing/CreditNotes.vue
  src/modules/client/pages/ni/billing/DebitsArchive.vue
  src/modules/client/pages/ni/billing/ToBill.vue
  src/modules/client/pages/ni/billing/TppBillSlips.vue
  src/modules/client/pages/ni/customers/CustomersFundingsMonitoring.vue
  src/modules/client/pages/ni/pay/Absences.vue
  src/modules/client/pages/ni/pay/ContractEnds.vue
  src/modules/client/pages/ni/pay/ContractMonitoring.vue
  src/modules/client/pages/ni/pay/ToPay.vue
Labels: dev
