Repository CompaniTech/compani-webapp, pull requests merged in 2020-10, with the labels that each got.

#720 COM-1534 check that startDate and endDate are on same day for a cours…
  src/core/components/courses/SlotContainer.vue
Labels: dev

#721 Com 1500
  src/core/data/constants.js
  src/modules/vendor/components/programs/cards/CardContainer.vue
  src/modules/vendor/components/programs/cards/CardEdition.vue
  src/modules/vendor/components/programs/cards/templates/QuestionAnswer.vue
  src/modules/vendor/helpers/cardValidation.js
  src/modules/vendor/mixins/templateMixin.js
Labels: dev

#724 COM-1560 filtered to blended only in ProfileCourses
  src/modules/vendor/components/learners/ProfileCourses.vue
Labels: dev

#726 COM-1555 - change card validation to isValid
  src/modules/vendor/components/programs/cards/CardContainer.vue
  src/modules/vendor/helpers/cardValidation.js
Labels: dev

#727 COM-1527
  src/modules/vendor/components/programs/ProfileContent.vue
Labels: dev

#729 COM-1571 refacto EstablishmentCreationModal
  src/core/mixins/establishmentMixin.js
  src/modules/client/pages/ni/config/CompanyConfig.vue
  src/modules/client/pages/ni/config/EstablishmentCreationModal.vue
Labels: dev

#728 COM-1528 - Add step status dot
  src/modules/vendor/components/programs/ProfileContent.vue
Labels: dev

#731 Com 1573 fixed sort by date in debit archive
  src/modules/client/pages/ni/billing/DebitsArchive.vue
Labels: dev

#730 COM-1571 refacto EstablishmentEditionModal
  src/modules/client/pages/ni/config/CompanyConfig.vue
  src/modules/client/pages/ni/config/EstablishmentEditionModal.vue
Labels: dev

#734 COM-1566 - Change max-width and min-width and fix menu access
  src/core/components/courses/CourseInfoLink.vue
  src/css/app.styl
  src/css/chip.styl
  src/css/planning.styl
  src/modules/client/components/planning/AuxiliaryIndicators.vue
  src/modules/client/components/planning/ChipCustomerIndicator.vue
  src/modules/client/components/planning/Planning.vue
  src/modules/client/layouts/Layout.vue
  src/modules/vendor/layouts/Layout.vue
Labels: dev

#733 Com 1574
  src/modules/vendor/components/programs/ActivityCreationModal.vue
  src/modules/vendor/components/programs/ActivityEditionModal.vue
  src/modules/vendor/components/programs/ProfileContent.vue
Labels: dev

#732 COM-1549 - change otherFees to phoneFees
  src/modules/client/mixins/configMixin.js
  src/modules/client/mixins/payMixin.js
  src/modules/client/pages/ni/config/RhConfig.vue
  src/modules/client/pages/ni/pay/ToPay.vue
Labels: dev

#735 Com 1549 Fix - Fix sort by option
  src/modules/client/pages/ni/pay/ToPay.vue
Labels: dev

#737 Com 1578 - refacto surchargeCreationModal
  src/modules/client/mixins/configMixin.js
  src/modules/client/pages/ni/config/CustomersConfig.vue
  src/modules/client/pages/ni/config/SurchargeCreationModal.vue
Labels: dev

#739 Com 1560 - Fix courses count
  src/modules/vendor/pages/ni/users/learners/LearnersDirectory.vue
Labels: dev

#736 COM-1572 add subscriptonId in payload when validate subscription
  src/modules/client/pages/customers/Subscriptions.vue
Labels: dev

#740 COM-1578 added surchargeEditionModal component
  src/modules/client/components/config/EstablishmentCreationModal.vue
  src/modules/client/components/config/EstablishmentEditionModal.vue
  src/modules/client/components/config/SurchargeCreationModal.vue
  src/modules/client/components/config/SurchargeEditionModal.vue
  src/modules/client/pages/ni/config/CompanyConfig.vue
  src/modules/client/pages/ni/config/CustomersConfig.vue
Labels: dev

#738 COM-1527 - Add published dot to ActivityProfile after Romain's review
  src/core/data/constants.js
  src/modules/vendor/components/programs/ProfileContent.vue
  src/modules/vendor/components/programs/PublishedDot.vue
  src/modules/vendor/pages/ni/config/ActivityProfile.vue
Labels: dev

#741 Com 1516 surveys
  src/core/api/Courses.js
  src/core/components/courses/HorizontalBarChart.vue
  src/core/components/courses/ProfileTraineeFollowUp.vue
  src/core/components/courses/SurveyChart.vue
  src/core/pages/courses/BlendedCourseProfile.vue
  src/modules/vendor/components/programs/ProfileContent.vue
Labels: dev

#745 Com 1595 ThirdPartyPayerEditionModal
  src/modules/client/components/config/ServiceEditionModal.vue
  src/modules/client/components/config/ThirdPartyPayerEditionModal.vue
  src/modules/client/pages/ni/config/CustomersConfig.vue
Labels: dev

#743 Com 1597 - Refacto Rh Config Modals
  src/modules/client/components/config/AdministrativeDocumentCreationModal.vue
  src/modules/client/components/config/InternalHourCreationModal.vue
  src/modules/client/components/config/SectorCreationModal.vue
  src/modules/client/components/config/SectorEditionModal.vue
  src/modules/client/pages/ni/config/RhConfig.vue
Labels: dev

#747 MES
  src/core/api/Courses.js
  src/core/components/courses/CourseInfoLink.vue
  src/core/components/courses/HorizontalBarChart.vue
  src/core/components/courses/ProfileAdmin.vue
  src/core/components/courses/ProfileTraineeFollowUp.vue
  src/core/components/courses/SurveyChart.vue
  src/core/data/constants.js
  src/core/mixins/establishmentMixin.js
  src/core/pages/courses/BlendedCourseProfile.vue
  src/css/app.styl
  src/css/chip.styl
  src/css/planning.styl
  src/modules/client/components/config/AdministrativeDocumentCreationModal.vue
  src/modules/client/components/config/EstablishmentCreationModal.vue
  src/modules/client/components/config/EstablishmentEditionModal.vue
  src/modules/client/components/config/InternalHourCreationModal.vue
  src/modules/client/components/config/SectorCreationModal.vue
  src/modules/client/components/config/SectorEditionModal.vue
  src/modules/client/components/config/ServiceEditionModal.vue
  src/modules/client/components/config/SurchargeCreationModal.vue
  src/modules/client/components/config/SurchargeEditionModal.vue
  src/modules/client/components/config/ThirdPartyPayerCreationModal.vue
  src/modules/client/components/config/ThirdPartyPayerEditionModal.vue
  src/modules/client/components/customers/infos/ProfileInfo.vue
  src/modules/client/components/planning/AuxiliaryIndicators.vue
  src/modules/client/components/planning/ChipCustomerIndicator.vue
  src/modules/client/components/planning/Planning.vue
  src/modules/client/layouts/Layout.vue
  src/modules/client/mixins/configMixin.js
  src/modules/client/mixins/payMixin.js
  src/modules/client/pages/customers/Subscriptions.vue
  src/modules/client/pages/ni/billing/DebitsArchive.vue
  src/modules/client/pages/ni/config/CompanyConfig.vue
  src/modules/client/pages/ni/config/CustomersConfig.vue
  src/modules/client/pages/ni/config/RhConfig.vue
  src/modules/client/pages/ni/pay/ToPay.vue
  src/modules/vendor/components/learners/ProfileCourses.vue
  src/modules/vendor/components/programs/ActivityCreationModal.vue
  src/modules/vendor/components/programs/ActivityEditionModal.vue
  src/modules/vendor/components/programs/ProfileContent.vue
  src/modules/vendor/components/programs/PublishedDot.vue
  src/modules/vendor/components/programs/cards/CardContainer.vue
  src/modules/vendor/helpers/cardValidation.js
  src/modules/vendor/layouts/Layout.vue
  src/modules/vendor/pages/ni/config/ActivityProfile.vue
  src/modules/vendor/pages/ni/users/learners/LearnersDirectory.vue
Labels: staging

#746 COM-1597 hide modal on submit for sector creation and edition modal
  src/modules/client/pages/ni/config/CustomersConfig.vue
  src/modules/client/pages/ni/config/RhConfig.vue
Labels: dev

#748 Dev
  src/modules/client/pages/ni/config/CustomersConfig.vue
  src/modules/client/pages/ni/config/RhConfig.vue
Labels: staging

#750 COM-1583 hide card type in cardContainer
  src/modules/vendor/components/programs/cards/CardContainer.vue
Labels: dev

#749 COM-1593 added firstLogin link on landing page
  src/core/components/Button.vue
  src/core/pages/signin/Authenticate.vue
Labels: dev

#752 Com 1587
  src/modules/client/mixins/configMixin.js
  src/modules/client/pages/ni/config/CustomersConfig.vue
Labels: dev

#755 Com 1588 move publish button
  src/modules/vendor/components/programs/ProfileContent.vue
Labels: dev

#754 Com 1586
  src/core/components/courses/CourseInfoLink.vue
  src/core/components/courses/ProfileAdmin.vue
Labels: dev

#753 Com 1596 edition
  src/core/api/Cards.js
  src/modules/vendor/components/programs/cards/templates/QuestionAnswer.vue
Labels: dev

#757 COM-1608 - fix validation if error is undefined
  src/modules/client/pages/ni/customers/CustomersDirectory.vue
Labels: bug, dev

#758 COM-1582 - delete course
  src/core/api/Courses.js
  src/core/pages/courses/BlendedCourseProfile.vue
  src/modules/client/components/customers/CustomerProfileHeader.vue
  src/modules/vendor/components/ProfileHeader.vue
Labels: dev

#759 COM-1584 card-creation in two clicks
  src/modules/vendor/components/programs/cards/CardCreationModal.vue
  src/modules/vendor/pages/ni/config/ActivityProfile.vue
Labels: dev

#760 COM-1590 added phone input
  src/modules/vendor/components/learners/ProfileInfo.vue
  src/modules/vendor/components/trainers/ProfileInfo.vue
Labels: dev

#761 Com 1596
  src/core/api/Cards.js
  src/core/data/constants.js
  src/core/helpers/vuelidateCustomVal.js
  src/modules/vendor/components/programs/cards/templates/QuestionAnswer.vue
Labels: dev

#762 COM_1587 disable sub if service is archived
  src/modules/client/components/planning/EventCreationModal.vue
  src/modules/client/mixins/planningModalMixin.js
Labels: dev

#763 Com 1596 deleteAnswer
  src/core/api/Cards.js
  src/modules/vendor/components/programs/cards/templates/QuestionAnswer.vue
Labels: dev

#765 Dev
  src/core/api/Cards.js
  src/core/api/Courses.js
  src/core/components/Button.vue
  src/core/components/courses/CourseInfoLink.vue
  src/core/components/courses/ProfileAdmin.vue
  src/core/data/constants.js
  src/core/helpers/vuelidateCustomVal.js
  src/core/pages/courses/BlendedCourseProfile.vue
  src/core/pages/signin/Authenticate.vue
  src/modules/client/components/customers/CustomerProfileHeader.vue
  src/modules/client/components/customers/infos/ProfileInfo.vue
  src/modules/client/components/planning/EventCreationModal.vue
  src/modules/client/mixins/configMixin.js
  src/modules/client/mixins/planningModalMixin.js
  src/modules/client/pages/ni/config/CustomersConfig.vue
  src/modules/client/pages/ni/customers/CustomersDirectory.vue
  src/modules/vendor/components/ProfileHeader.vue
  src/modules/vendor/components/learners/ProfileInfo.vue
  src/modules/vendor/components/programs/ProfileContent.vue
  src/modules/vendor/components/programs/cards/CardContainer.vue
  src/modules/vendor/components/programs/cards/CardCreationModal.vue
  src/modules/vendor/components/programs/cards/templates/QuestionAnswer.vue
  src/modules/vendor/components/trainers/ProfileInfo.vue
  src/modules/vendor/pages/ni/config/ActivityProfile.vue
Labels: staging

#767 MEP
  src/core/api/Cards.js
  src/core/api/Courses.js
  src/core/components/Button.vue
  src/core/components/courses/CourseInfoLink.vue
  src/core/components/courses/ProfileAdmin.vue
  src/core/data/constants.js
  src/core/helpers/vuelidateCustomVal.js
  src/core/pages/courses/BlendedCourseProfile.vue
  src/core/pages/signin/Authenticate.vue
  src/modules/client/components/customers/CustomerProfileHeader.vue
  src/modules/client/components/customers/infos/ProfileInfo.vue
  src/modules/client/components/planning/EventCreationModal.vue
  src/modules/client/mixins/configMixin.js
  src/modules/client/mixins/planningModalMixin.js
  src/modules/client/pages/ni/config/CustomersConfig.vue
  src/modules/client/pages/ni/customers/CustomersDirectory.vue
  src/modules/vendor/components/ProfileHeader.vue
  src/modules/vendor/components/learners/ProfileInfo.vue
  src/modules/vendor/components/programs/ProfileContent.vue
  src/modules/vendor/components/programs/cards/CardContainer.vue
  src/modules/vendor/components/programs/cards/CardCreationModal.vue
  src/modules/vendor/components/programs/cards/templates/QuestionAnswer.vue
  src/modules/vendor/components/trainers/ProfileInfo.vue
  src/modules/vendor/pages/ni/config/ActivityProfile.vue
Labels: master

#768 Com 1609
  src/core/components/courses/OpenQuestionChart.vue
  src/core/components/courses/ProfileTraineeFollowUp.vue
  src/core/components/courses/SurveyChart.vue
  src/modules/vendor/components/programs/ProfileContent.vue
Labels: dev

#770 Com 1585
  src/modules/vendor/components/programs/cards/templates/FillTheGaps.vue
  src/modules/vendor/components/programs/cards/templates/Flashcard.vue
  src/modules/vendor/components/programs/cards/templates/MultipleChoiceQuestion.vue
  src/modules/vendor/components/programs/cards/templates/OpenQuestion.vue
  src/modules/vendor/components/programs/cards/templates/OrderTheSequence.vue
  src/modules/vendor/components/programs/cards/templates/QuestionAnswer.vue
  src/modules/vendor/components/programs/cards/templates/SingleChoiceQuestion.vue
  src/modules/vendor/components/programs/cards/templates/Survey.vue
  src/modules/vendor/components/programs/cards/templates/TextMedia.vue
  src/modules/vendor/components/programs/cards/templates/TitleText.vue
  src/modules/vendor/components/programs/cards/templates/TitleTextMedia.vue
  src/modules/vendor/components/programs/cards/templates/Transition.vue
  src/modules/vendor/mixins/templateMixin.js
Labels: dev

#773 COM-1585-fix - Fix updateCard
  src/modules/vendor/mixins/templateMixin.js
Labels: dev

#774 COM-1606 using rounded divs instead of q-linear-progress
  src/core/components/courses/SurveyChart.vue
Labels: dev

#769 COM-1611 - Add CourseHistoryFeed
  src/core/api/CourseHistories.js
  src/core/components/courses/CourseHistory.vue
  src/core/components/courses/CourseHistoryFeed.vue
  src/core/components/courses/ProfileOrganization.vue
  src/core/data/constants.js
  src/css/app.styl
  src/css/history.styl
  src/modules/client/components/planning/EventHistory.vue
  src/modules/client/components/planning/EventHistoryFeed.vue
Labels: dev

#776 COM-1552 FlashCard add front validations
  src/core/data/constants.js
  src/core/mixins/companyMixin.js
  src/modules/vendor/components/programs/cards/templates/Flashcard.vue
Labels: dev
