Repository CompaniTech/compani-webapp, pull requests merged in 2020-11, with the labels that each got.

#777 COM-1611 - Add infinite scroll
  src/core/components/courses/CourseHistoryFeed.vue
  src/core/components/courses/ProfileOrganization.vue
Labels: dev

#778 Com 1617
  src/modules/vendor/components/programs/ProfileContent.vue
Labels: dev

#781 COM-1610 rounded percentage QuestionAnswer
  src/core/components/courses/QuestionAnswerChart.vue
Labels: dev

#779 COM-1612 - Create coursehistory on slot deletion
  src/core/components/courses/CourseHistory.vue
  src/core/data/constants.js
Labels: dev

#782 CON-1621 - fix csv to match with table
  src/modules/client/mixins/payMixin.js
Labels: bug, dev

#784 COM-1618 view history action after course edition
  src/core/components/courses/CourseHistory.vue
  src/core/data/constants.js
Labels: dev

#783 COM-1613
  src/core/components/courses/CourseHistory.vue
  src/core/data/constants.js
  src/css/history.styl
Labels: dev

#786 COM-1606 new Romain's sketch
  src/core/components/courses/SurveyChart.vue
Labels: dev

#787 Com 1640
  src/core/components/courses/CourseHistory.vue
  src/css/history.styl
  src/modules/client/components/planning/EventHistory.vue
Labels: bug, dev

#785 COM-1614 - Add course history for trainee deletion
  src/core/components/courses/CourseHistory.vue
  src/core/data/constants.js
Labels: dev

#788 COM-1619 add newHour in courseHistory switch
  src/core/components/courses/CourseHistory.vue
Labels: dev

#791 Dev
  src/core/components/courses/CourseHistory.vue
Labels: staging

#793 Com 1631 refacto LearnerCreationModal
  src/core/components/courses/LearnerCreationModal.vue
  src/core/components/courses/TraineeTable.vue
Labels: dev

#794 Com 1628 - Upload Image, Video and Audio
  src/core/components/form/FileUploader.vue
  src/core/data/constants.js
  src/modules/vendor/components/programs/cards/templates/TextMedia.vue
  src/modules/vendor/components/programs/cards/templates/TitleTextMedia.vue
  src/modules/vendor/mixins/templateMixin.js
Labels: dev

#797 Com 1628 - Allow audio and video upload
  src/modules/vendor/components/programs/cards/templates/TextMedia.vue
  src/modules/vendor/components/programs/cards/templates/TitleTextMedia.vue
  src/modules/vendor/mixins/templateMixin.js
Labels: dev

#796 Com 1627 add QUESTIONNAIRE activity type
  src/core/data/constants.js
  src/modules/vendor/components/programs/ProfileContent.vue
Labels: dev

#801 Com 1633 - ELearningCourseProfile
  src/core/helpers/rbac.js
  src/modules/vendor/components/programs/cards/templates/TextMedia.vue
  src/modules/vendor/pages/ni/management/ELearningCourseProfile.vue
  src/modules/vendor/pages/ni/management/ELearningCoursesDirectory.vue
  src/modules/vendor/router/routes.js
Labels: dev

#804 Com 1633
  src/core/helpers/rbac.js
  src/modules/vendor/components/programs/cards/templates/TextMedia.vue
  src/modules/vendor/pages/ni/management/ELearningCourseProfile.vue
  src/modules/vendor/pages/ni/management/ELearningCoursesDirectory.vue
  src/modules/vendor/router/routes.js
Labels: dev

#807 COM-1667 - fix picture image upload
  src/core/components/PictureUploader.vue
Labels: bug, dev

#805 COM-1629 add option group in TitleTextMedia
  src/modules/vendor/components/programs/cards/templates/TextMedia.vue
  src/modules/vendor/components/programs/cards/templates/TitleTextMedia.vue
  src/modules/vendor/mixins/templateMixin.js
Labels: dev

#802 Com 1623
  src/core/api/Pay.js
  src/modules/client/pages/ni/pay/ToPay.vue
Labels: dev

#806 COM-1630 using CourseProgress
  src/core/components/CourseProgress.vue
  src/core/components/learners/ProfileCourses.vue
Labels: dev

#809 COM-1670 - fix update good answer
  src/modules/vendor/components/programs/cards/templates/MultipleChoiceQuestion.vue
Labels: bug, dev

#810 COM-1633 - redirect to learner profile
  src/modules/vendor/pages/ni/management/ELearningCourseProfile.vue
Labels: dev

#811 COM-1623 - add contract version in export
  src/core/data/constants.js
  src/modules/client/pages/ni/pay/ToPay.vue
Labels: dev

#813 Com 1630 list user course
  src/core/api/Courses.js
  src/core/components/learners/ProfileCourses.vue
  src/core/mixins/courseFollowUpMixin.js
  src/modules/vendor/pages/ni/management/ELearningCourseProfile.vue
Labels: dev

#816 COM-1624 - export absence info to 123paie
  src/core/data/constants.js
  src/modules/client/pages/ni/pay/ToPay.vue
Labels: dev

#814 COM-1603 - Disable publishment button when subProgram is not valid
  src/modules/vendor/components/programs/ProfileContent.vue
Labels: dev

#823 Com 1657 view and add categories
  src/core/api/Categories.js
  src/core/helpers/rbac.js
  src/modules/vendor/components/programs/CategoryCreationModal.vue
  src/modules/vendor/mixins/menuItemsMixin.js
  src/modules/vendor/pages/ni/config/CategoriesDirectory.vue
  src/modules/vendor/router/routes.js
Labels: dev

#824 Com 1654
  src/core/components/courses/TraineeTable.vue
  src/core/data/constants.js
  src/core/helpers/utils.js
  src/css/modal.styl
  src/modules/vendor/components/courses/CourseCreationModal.vue
  src/modules/vendor/components/programs/ProfileContent.vue
  src/modules/vendor/components/programs/SubProgramPublicationModal.vue
  src/modules/vendor/pages/ni/management/BlendedCoursesDirectory.vue
Labels: dev

#825 Com 1657 update (PUT ROUTE)
  src/core/api/Categories.js
  src/modules/vendor/components/programs/CategoryEditionModal.vue
  src/modules/vendor/pages/ni/config/CategoriesDirectory.vue
Labels: dev

#826 COM-1657 delete button
  src/core/api/Categories.js
  src/modules/vendor/pages/ni/config/CategoriesDirectory.vue
Labels: dev

#830 Com 1668 staging
  src/core/data/constants.js
  src/core/helpers/alenvi.js
  src/core/mixins/logInMixin.js
Labels: staging

#832 Com 1675
  src/core/data/constants.js
  src/modules/client/pages/ni/pay/ToPay.vue
Labels: dev
