Repository CompaniTech/compani-webapp, pull requests merged in 2020-09, with the labels that each got.

#665 COM-1428 - allow reodering
  package-lock.json
  package.json
  src/modules/client/components/planning/Planning.vue
  src/modules/client/components/planning/PlanningEvent.vue
  src/modules/client/pages/ni/pay/ToPay.vue
  src/modules/vendor/components/programs/ProfileContent.vue
Labels: dev

#667 Com 1410 - Fix Warnings for exceptionnal cases
  src/core/helpers/vuelidateCustomVal.js
  src/modules/vendor/components/programs/cards/templates/MultipleChoiceQuestion.vue
Labels: dev

#671 COM-1441 add step index
  src/modules/vendor/components/programs/ProfileContent.vue
Labels: dev

#672 COM-1439 add open question template
  src/modules/vendor/components/programs/cards/CardEdition.vue
  src/modules/vendor/components/programs/cards/templates/OpenQuestion.vue
  src/modules/vendor/helpers/cardValidation.js
Labels: dev

#674 COM-1474 change fillTheGaps field name 'text' to 'gappedText'
  src/modules/vendor/components/programs/cards/templates/FillTheGaps.vue
  src/modules/vendor/helpers/cardValidation.js
Labels: dev

#676 Com 1479
  src/modules/client/components/planning/ChipsAutocomplete.vue
  src/modules/client/pages/auxiliaries/customers/AuxiliaryCustomersDirectory.vue
  src/modules/client/pages/auxiliaries/teams/TeamsDirectory.vue
  src/modules/client/pages/ni/auxiliaries/Directory.vue
  src/modules/client/pages/ni/customers/CustomersDirectory.vue
  src/modules/vendor/pages/ni/config/ProgramsDirectory.vue
  src/modules/vendor/pages/ni/users/companies/CompaniesDirectory.vue
  src/modules/vendor/pages/ni/users/learners/LearnersDirectory.vue
  src/modules/vendor/pages/ni/users/trainers/TrainersDirectory.vue
Labels: dev

#677 fix tests
  test/cypress/plugins/index.js
Labels: dev

#678 COM-1472 add title for quiz and survey
  src/modules/vendor/components/programs/cards/CardContainer.vue
Labels: dev

#684 Dev
  src/modules/client/components/auxiliary/AuxiliaryProfileHeader.vue
  src/modules/client/components/customers/CustomerProfileHeader.vue
  src/modules/client/components/planning/EventCreationModal.vue
  src/modules/client/components/planning/EventEditionModal.vue
  src/modules/client/pages/auxiliaries/customers/CustomerInfo.vue
Labels: staging

#686 Com 1458
  src/core/api/Steps.js
  src/modules/vendor/components/programs/ProfileContent.vue
Labels: dev

#688 Com 1420 - Open step when user go back from activity
  src/modules/vendor/components/programs/ProfileContent.vue
  src/modules/vendor/pages/ni/config/ActivityProfile.vue
  src/modules/vendor/store/program.js
Labels: dev

#689 Com 1459
  src/modules/vendor/components/programs/ProfileContent.vue
  src/modules/vendor/components/programs/cards/CardContainer.vue
  src/modules/vendor/pages/ni/config/ActivityProfile.vue
Labels: dev

#690 COM-1494 call refresh if there is auxiliaries or sectors in filter
  src/modules/client/pages/ni/planning/AuxiliaryPlanning.vue
Labels: dev

#693 Com 1497
  src/core/api/Services.js
  src/modules/client/components/config/ServiceCreationModal.vue
  src/modules/client/components/config/ServiceEditionModal.vue
  src/modules/client/pages/ni/config/CustomersConfig.vue
Labels: dev

#692 COM-1496 - fix error message on authentification
  src/core/data/constants.js
  src/core/helpers/alenvi.js
  src/core/mixins/logInMixin.js
  src/core/pages/signin/Authenticate.vue
  src/router/redirect.js
  test/cypress/integration/authenticate.spec.js
  test/cypress/support/commands.js
Labels: dev

#691 Com 1459 fix
  src/modules/vendor/components/programs/ProfileContent.vue
  src/modules/vendor/components/programs/cards/CardContainer.vue
Labels: dev

#695 Com 1461
  src/modules/vendor/components/programs/ProfileContent.vue
Labels: dev

#696 COM-1463 can't add, delete, change order of cards and can't change ac…
  src/modules/vendor/components/programs/ProfileContent.vue
  src/modules/vendor/components/programs/cards/CardContainer.vue
Labels: dev

#698 Dev
  src/core/api/Services.js
  src/core/api/Steps.js
  src/core/components/Button.vue
  src/core/data/constants.js
  src/core/helpers/alenvi.js
  src/core/mixins/logInMixin.js
  src/core/pages/signin/Authenticate.vue
  src/modules/client/components/config/ServiceCreationModal.vue
  src/modules/client/components/config/ServiceEditionModal.vue
  src/modules/client/mixins/contractMixin.js
  src/modules/client/mixins/planningActionMixin.js
  src/modules/client/pages/ni/config/CustomersConfig.vue
  src/modules/client/pages/ni/planning/AuxiliaryPlanning.vue
  src/modules/vendor/components/programs/ProfileContent.vue
  src/modules/vendor/components/programs/cards/CardContainer.vue
  src/modules/vendor/pages/ni/config/ActivityProfile.vue
  src/modules/vendor/store/program.js
  src/router/redirect.js
  test/cypress/integration/authenticate.spec.js
  test/cypress/support/commands.js
Labels: staging

#702 Staging
  src/core/api/Services.js
  src/core/api/Steps.js
  src/core/components/Button.vue
  src/core/components/form/FileUploader.vue
  src/core/data/constants.js
  src/core/helpers/alenvi.js
  src/core/mixins/logInMixin.js
  src/core/pages/signin/Authenticate.vue
  src/modules/client/components/config/ServiceCreationModal.vue
  src/modules/client/components/config/ServiceEditionModal.vue
  src/modules/client/mixins/contractMixin.js
  src/modules/client/mixins/planningActionMixin.js
  src/modules/client/pages/ni/config/CustomersConfig.vue
  src/modules/client/pages/ni/planning/AuxiliaryPlanning.vue
  src/modules/vendor/components/programs/ProfileContent.vue
  src/modules/vendor/components/programs/cards/CardContainer.vue
  src/modules/vendor/pages/ni/config/ActivityProfile.vue
  src/modules/vendor/store/program.js
  src/router/redirect.js
  test/cypress/integration/authenticate.spec.js
  test/cypress/support/commands.js
Labels: master

#699 COM-1504 max-length demo for title-text
  src/core/data/constants.js
  src/core/helpers/vuelidateCustomVal.js
  src/modules/vendor/components/programs/cards/templates/FillTheGaps.vue
  src/modules/vendor/components/programs/cards/templates/MultipleChoiceQuestion.vue
  src/modules/vendor/components/programs/cards/templates/OpenQuestion.vue
  src/modules/vendor/components/programs/cards/templates/OrderTheSequence.vue
  src/modules/vendor/components/programs/cards/templates/SingleChoiceQuestion.vue
  src/modules/vendor/components/programs/cards/templates/Survey.vue
  src/modules/vendor/helpers/cardValidation.js
  src/modules/vendor/mixins/templateMixin.js
Labels: dev

#704 Com 1511
  src/core/components/courses/CourseContainer.vue
  src/core/data/constants.js
  src/core/helpers/rbac.js
  src/core/pages/courses/BlendedCourseInfo.vue
  src/core/pages/courses/BlendedCourseProfile.vue
  src/modules/client/pages/ni/courses/BlendedCoursesDirectory.vue
  src/modules/client/router/routes.js
  src/modules/vendor/components/learners/ProfileCourses.vue
  src/modules/vendor/mixins/menuItemsMixin.js
  src/modules/vendor/pages/ni/management/BlendedCoursesDirectory.vue
  src/modules/vendor/pages/ni/management/ELearningCoursesDirectory.vue
  src/modules/vendor/pages/trainers/management/BlendedCoursesDirectory.vue
  src/modules/vendor/router/routes.js
  src/router/routes.js
Labels: dev

#705 COM-1505 refacto falsy answers
  src/modules/vendor/components/programs/cards/templates/FillTheGaps.vue
  src/modules/vendor/components/programs/cards/templates/MultipleChoiceQuestion.vue
  src/modules/vendor/components/programs/cards/templates/SingleChoiceQuestion.vue
  src/modules/vendor/helpers/cardValidation.js
Labels: dev

#707 COM-1514
  src/core/components/courses/SlotContainer.vue
Labels: dev

#708 COM-1542
  src/modules/vendor/components/programs/ProfileContent.vue
  src/modules/vendor/pages/ni/config/ProgramCreationModal.vue
  src/modules/vendor/pages/ni/config/ProgramsDirectory.vue
Labels: dev

#712 COM-1542 refacto newPassword modal
  src/core/pages/AccountInfo.vue
  src/core/pages/NewPasswordModal.vue
  src/modules/vendor/components/programs/ActivityCreationModal.vue
Labels: dev

#715 COM-1544 npm upgrade
  package-lock.json
  package.json
Labels: dev

#710 COM-1542-contract move modals
  src/modules/client/components/auxiliary/ProfileContracts.vue
  src/modules/client/components/contracts/ContractCreationModal.vue
  src/modules/client/components/contracts/ContractEndingModal.vue
  src/modules/client/components/contracts/VersionCreationModal.vue
Labels: dev

#713 COM-1499 added Q&A to cardCreation modal
  src/core/data/constants.js
  src/modules/vendor/components/programs/cards/CardCreationModal.vue
Labels: dev

#717 COM-1512 added sector name
  src/modules/client/pages/auxiliaries/teams/TeamsDirectory.vue
Labels: dev

#719 Com 1498
  src/core/components/courses/ProfileFollowUp.vue
  src/core/pages/courses/BlendedCourseInfo.vue
  src/modules/vendor/components/programs/ProfileInfo.vue
Labels: dev
