Repository CompaniTech/compani-webapp, pull requests merged in 2021-11, with the labels that each got.

#1341 COM-2425: refacto activity title edition
  src/modules/vendor/components/programs/ActivityCreationModal.vue
  src/modules/vendor/components/programs/ActivityEditionModal.vue
  src/modules/vendor/components/programs/ProfileContent.vue
  src/modules/vendor/components/programs/cards/CardContainer.vue
  src/modules/vendor/components/questionnaires/ProfileEdition.vue
  src/modules/vendor/pages/ni/pedagogy/ActivityProfile.vue
Labels: dev

#1338 COM-2427 - Fix Romain's review
  src/modules/client/components/planning/EventEditionModal.vue
Labels: dev

#1345 Mes 02.11.2021
  package-lock.json
  package.json
  src/core/api/BillingItems.js
  src/core/api/Courses.js
  src/core/api/EventHistories.js
  src/core/api/Steps.js
  src/core/api/SubPrograms.js
  src/core/api/Teletransmission.js
  src/core/components/ButtonToggle.vue
  src/core/components/courses/ProfileAdmin.vue
  src/core/components/courses/SlotContainer.vue
  src/core/components/courses/SlotCreationModal.vue
  src/core/components/courses/SlotEditionModal.vue
  src/core/components/form/DatetimeRange.vue
  src/core/components/form/FileUploader.vue
  src/core/components/form/MultipleOptionGroup.vue
  src/core/components/form/TimeInput.vue
  src/core/data/constants.js
  src/core/helpers/vuelidateCustomVal.js
  src/core/mixins/courseMixin.js
  src/modules/client/components/customers/billing/DeliveryDownloadModal.vue
  src/modules/client/components/customers/billing/PaymentCreationModal.vue
  src/modules/client/components/customers/infos/FundingDetailsModal.vue
  src/modules/client/components/customers/infos/FundingHistoryModal.vue
  src/modules/client/components/customers/infos/ProfileInfo.vue
  src/modules/client/components/planning/EventCreationModal.vue
  src/modules/client/components/planning/EventEditionModal.vue
  src/modules/client/components/planning/EventHistory.vue
  src/modules/client/components/planning/HistoryCancellationModal.vue
  src/modules/client/components/table/FundingGridTable.vue
  src/modules/client/mixins/planningActionMixin.js
  src/modules/client/mixins/subscriptionMixin.js
  src/modules/client/pages/auxiliaries/planning/AuxiliaryAgenda.vue
  src/modules/client/pages/ni/billing/ToBill.vue
  src/modules/client/pages/ni/config/CustomersConfig.vue
  src/modules/client/pages/ni/config/RhConfig.vue
  src/modules/client/pages/ni/courses/Dashboard.vue
  src/modules/client/pages/ni/pay/Absences.vue
  src/modules/client/pages/ni/planning/AuxiliaryPlanning.vue
  src/modules/client/pages/ni/planning/CustomerPlanning.vue
  src/modules/vendor/components/programs/ActivityCreationModal.vue
  src/modules/vendor/components/programs/ActivityEditionModal.vue
  src/modules/vendor/components/programs/ActivityReuseModal.vue
  src/modules/vendor/components/programs/ProfileContent.vue
  src/modules/vendor/components/programs/StepAdditionModal.vue
  src/modules/vendor/components/programs/StepCreationModal.vue
  src/modules/vendor/components/programs/ValidateUnlockingStepModal.vue
  src/modules/vendor/components/programs/cards/CardContainer.vue
  src/modules/vendor/components/questionnaires/ProfileEdition.vue
  src/modules/vendor/pages/ni/pedagogy/ActivityProfile.vue
Labels: staging

#1346 MEP 03/11
  package-lock.json
  package.json
  src/core/api/BillingItems.js
  src/core/api/Courses.js
  src/core/api/EventHistories.js
  src/core/api/Steps.js
  src/core/api/SubPrograms.js
  src/core/api/Teletransmission.js
  src/core/components/ButtonToggle.vue
  src/core/components/courses/ProfileAdmin.vue
  src/core/components/courses/SlotContainer.vue
  src/core/components/courses/SlotCreationModal.vue
  src/core/components/courses/SlotEditionModal.vue
  src/core/components/form/DatetimeRange.vue
  src/core/components/form/FileUploader.vue
  src/core/components/form/MultipleOptionGroup.vue
  src/core/components/form/TimeInput.vue
  src/core/data/constants.js
  src/core/helpers/vuelidateCustomVal.js
  src/core/mixins/courseMixin.js
  src/modules/client/components/customers/billing/DeliveryDownloadModal.vue
  src/modules/client/components/customers/billing/PaymentCreationModal.vue
  src/modules/client/components/customers/infos/FundingDetailsModal.vue
  src/modules/client/components/customers/infos/FundingHistoryModal.vue
  src/modules/client/components/customers/infos/ProfileInfo.vue
  src/modules/client/components/planning/EventCreationModal.vue
  src/modules/client/components/planning/EventEditionModal.vue
  src/modules/client/components/planning/EventHistory.vue
  src/modules/client/components/planning/HistoryCancellationModal.vue
  src/modules/client/components/table/FundingGridTable.vue
  src/modules/client/mixins/planningActionMixin.js
  src/modules/client/mixins/subscriptionMixin.js
  src/modules/client/pages/auxiliaries/planning/AuxiliaryAgenda.vue
  src/modules/client/pages/ni/billing/ToBill.vue
  src/modules/client/pages/ni/config/CustomersConfig.vue
  src/modules/client/pages/ni/config/RhConfig.vue
  src/modules/client/pages/ni/courses/Dashboard.vue
  src/modules/client/pages/ni/pay/Absences.vue
  src/modules/client/pages/ni/planning/AuxiliaryPlanning.vue
  src/modules/client/pages/ni/planning/CustomerPlanning.vue
  src/modules/vendor/components/programs/ActivityCreationModal.vue
  src/modules/vendor/components/programs/ActivityEditionModal.vue
  src/modules/vendor/components/programs/ActivityReuseModal.vue
  src/modules/vendor/components/programs/ProfileContent.vue
  src/modules/vendor/components/programs/StepAdditionModal.vue
  src/modules/vendor/components/programs/StepCreationModal.vue
  src/modules/vendor/components/programs/ValidateUnlockingStepModal.vue
  src/modules/vendor/components/programs/cards/CardContainer.vue
  src/modules/vendor/components/questionnaires/ProfileEdition.vue
  src/modules/vendor/pages/ni/pedagogy/ActivityProfile.vue
Labels: master

#1353 COM-2474 - Prevent event creation and update if customer is absent
  src/modules/client/mixins/planningActionMixin.js
Labels: dev

#1355 COM-2480: block slot addition and edition
  src/core/components/courses/SlotContainer.vue
Labels: dev

#1354 COM-2479: add togle on kanban
  src/core/components/DirectoryHeader.vue
  src/core/components/courses/BlendedCourseProfileHeader.vue
  src/core/components/courses/CourseCell.vue
  src/core/mixins/courseFiltersMixin.js
  src/core/mixins/courseMixin.js
  src/modules/client/pages/ni/courses/BlendedCoursesDirectory.vue
  src/modules/vendor/pages/ni/management/BlendedCoursesDirectory.vue
  src/modules/vendor/pages/trainers/management/BlendedCoursesDirectory.vue
Labels: dev

#1357 COM-2486: refacto progress
  src/core/components/courses/ElearningFollowUpTable.vue
  src/core/components/courses/ProfileFollowUp.vue
  src/core/components/courses/ProfileTraineeFollowUp.vue
  src/core/mixins/traineeFollowUpTableMixin.js
Labels: dev

#1358 COM-2484: block infos edition
  src/core/components/courses/ProfileAdmin.vue
  src/core/components/courses/ProfileOrganization.vue
  src/core/mixins/courseMixin.js
Labels: dev

#1361 COM-2507 - multiple tpps
  src/core/components/table/AttendanceTable.vue
  src/modules/client/components/customers/billing/DeliveryDownloadModal.vue
  src/modules/client/pages/ni/billing/ToBill.vue
Labels: dev

#1366 Mes 2211
  package-lock.json
  package.json
  src/core/api/CustomerAbsences.js
  src/core/components/DirectoryHeader.vue
  src/core/components/ProfileHeader.vue
  src/core/components/courses/BlendedCourseProfileHeader.vue
  src/core/components/courses/CourseCell.vue
  src/core/components/courses/ElearningFollowUpTable.vue
  src/core/components/courses/ProfileAdmin.vue
  src/core/components/courses/ProfileFollowUp.vue
  src/core/components/courses/ProfileOrganization.vue
  src/core/components/courses/ProfileTraineeFollowUp.vue
  src/core/components/courses/SlotContainer.vue
  src/core/components/courses/TraineeTable.vue
  src/core/components/table/AttendanceTable.vue
  src/core/data/constants.js
  src/core/mixins/courseFiltersMixin.js
  src/core/mixins/courseMixin.js
  src/core/mixins/traineeFollowUpTableMixin.js
  src/css/icon.styl
  src/css/planning.styl
  src/modules/client/components/customers/EventConflictModal.vue
  src/modules/client/components/customers/billing/DeliveryDownloadModal.vue
  src/modules/client/components/planning/DeleteEventsModal.vue
  src/modules/client/components/planning/Planning.vue
  src/modules/client/components/planning/PlanningEventCell.vue
  src/modules/client/components/planning/PlanningNavigation.vue
  src/modules/client/mixins/planningActionMixin.js
  src/modules/client/mixins/planningEventMixin.js
  src/modules/client/pages/ni/billing/ToBill.vue
  src/modules/client/pages/ni/courses/BlendedCoursesDirectory.vue
  src/modules/client/pages/ni/planning/CustomerPlanning.vue
  src/modules/vendor/pages/ni/management/BlendedCourseProfile.vue
  src/modules/vendor/pages/ni/management/BlendedCoursesDirectory.vue
  src/modules/vendor/pages/trainers/management/BlendedCoursesDirectory.vue
  test/cypress/integration/ni/planning/auxiliaryPlanning.spec.js
Labels: staging

#1369 MEP 23/11/2021
  package-lock.json
  package.json
  src/core/api/CustomerAbsences.js
  src/core/components/DirectoryHeader.vue
  src/core/components/ProfileHeader.vue
  src/core/components/courses/BlendedCourseProfileHeader.vue
  src/core/components/courses/CourseCell.vue
  src/core/components/courses/ElearningFollowUpTable.vue
  src/core/components/courses/ProfileAdmin.vue
  src/core/components/courses/ProfileFollowUp.vue
  src/core/components/courses/ProfileOrganization.vue
  src/core/components/courses/ProfileTraineeFollowUp.vue
  src/core/components/courses/SlotContainer.vue
  src/core/components/courses/TraineeTable.vue
  src/core/components/table/AttendanceTable.vue
  src/core/data/constants.js
  src/core/mixins/courseFiltersMixin.js
  src/core/mixins/courseMixin.js
  src/core/mixins/traineeFollowUpTableMixin.js
  src/css/icon.styl
  src/css/planning.styl
  src/modules/client/components/customers/EventConflictModal.vue
  src/modules/client/components/customers/billing/DeliveryDownloadModal.vue
  src/modules/client/components/planning/Agenda.vue
  src/modules/client/components/planning/ChipCustomerIndicator.vue
  src/modules/client/components/planning/DeleteEventsModal.vue
  src/modules/client/components/planning/Planning.vue
  src/modules/client/components/planning/PlanningEventCell.vue
  src/modules/client/components/planning/PlanningNavigation.vue
  src/modules/client/mixins/planningActionMixin.js
  src/modules/client/mixins/planningEventMixin.js
  src/modules/client/pages/customers/CustomerAgenda.vue
  src/modules/client/pages/ni/billing/ToBill.vue
  src/modules/client/pages/ni/courses/BlendedCoursesDirectory.vue
  src/modules/client/pages/ni/planning/CustomerPlanning.vue
  src/modules/vendor/pages/ni/management/BlendedCourseProfile.vue
  src/modules/vendor/pages/ni/management/BlendedCoursesDirectory.vue
  src/modules/vendor/pages/trainers/management/BlendedCoursesDirectory.vue
  test/cypress/integration/ni/planning/auxiliaryPlanning.spec.js
Labels: master

#1370 COM-2532: npm update
  .eslintrc.js
  package-lock.json
  package.json
  src/modules/client/components/customers/ProfileFollowUp.vue
  src/modules/client/pages/customers/Subscriptions.vue
  src/modules/vendor/mixins/templateMixin.js
Labels: dependencies

#1372 COM-2517: can add trainee with email
  src/core/components/courses/TraineeTable.vue
  src/core/components/form/Select.vue
Labels: dev
