Repository CompaniTech/compani-webapp, pull requests merged in 2021-01, with the labels that each got.

#897 Fix deconnection
  src/core/api/Authentication.js
Labels: bug, dev

#898 COM-1719 - remove large table
  src/core/components/table/LargeTable.vue
Labels: bug, dev

#899 MES
  src/core/api/Authentication.js
  src/core/components/table/LargeTable.vue
Labels: staging

#901 COM-1553 - fix moment
  src/core/components/courses/SmsDetailsModal.vue
  src/modules/client/components/customers/infos/FundingEditionModal.vue
  src/modules/client/pages/customers/Subscriptions.vue
Labels: dev

#896 Com 1787 npm update
  package-lock.json
  package.json
Labels: dev

#905 update casl
  package-lock.json
  package.json
Labels: dev

#906 Com 1758
  src/core/helpers/rbac.js
  src/modules/client/mixins/menuItemsMixin.js
  src/modules/client/pages/ni/courses/Dashboard.vue
  src/modules/client/router/routes.js
Labels: dev

#909 Com 1706
  src/core/components/learners/ProfileCourses.vue
  src/core/components/table/ExpandingTable.vue
  src/css/table.styl
  src/modules/vendor/components/courses/ProfileFollowUp.vue
Labels: dev

#907 Com 1744 - add extension for absence
  src/modules/client/components/planning/EventCreationModal.vue
  src/modules/client/mixins/planningActionMixin.js
  src/modules/client/pages/ni/planning/AuxiliaryPlanning.vue
Labels: dev

#908 Com 1751 upload attendanceSheets
  src/core/api/AttendanceSheets.js
  src/core/components/courses/AttendanceSheetAdditionModal.vue
  src/core/components/courses/ProfileTraineeFollowUp.vue
  src/modules/vendor/pages/ni/config/CategoriesDirectory.vue
Labels: dev

#910 COM-1749 - go to blended course profile
  src/core/components/learners/ProfileCourses.vue
  src/modules/client/router/routes.js
  src/modules/vendor/router/routes.js
Labels: dev

#911 COM-1770 - Add welcome email for trainee
  src/core/components/courses/TraineeTable.vue
  src/core/data/constants.js
  src/modules/client/pages/ni/courses/LearnersDirectory.vue
Labels: dev

#914 COM-1737 fix chart color fill
  src/core/components/courses/SurveyChart.vue
Labels: bug

#916 Com 1759
  src/core/api/ActivityHistories.js
  src/core/components/form/DateRange.vue
  src/modules/client/pages/ni/courses/Dashboard.vue
Labels: dev

#913 Com 1747
  src/modules/client/components/planning/AuxiliaryIndicators.vue
  src/modules/client/pages/ni/auxiliaries/Dashboard.vue
Labels: dev

#915 Com 1744 edition
  src/modules/client/components/planning/EventCreationModal.vue
  src/modules/client/components/planning/EventEditionModal.vue
  src/modules/client/mixins/planningActionMixin.js
Labels: dev

#919 COM-1752 rename
  src/modules/client/mixins/menuItemsMixin.js
  src/modules/vendor/mixins/menuItemsMixin.js
Labels: dev

#920 COM-1750 followUp for blendedCourses
  src/core/components/courses/ProfileTraineeFollowUp.vue
  src/modules/vendor/components/courses/ProfileFollowUp.vue
  src/modules/vendor/router/routes.js
Labels: dev

#921 COM-1747 - take january into account
  src/modules/client/mixins/payMixin.js
  src/modules/client/pages/ni/pay/ToPay.vue
Labels: dev

#917 COM-1751 delete attendanceSheet
  src/core/api/AttendanceSheets.js
  src/core/components/courses/ProfileTraineeFollowUp.vue
Labels: dev

#922 Com 1750 rename
  src/core/components/courses/ProfileTraineeFollowUp.vue
  src/modules/vendor/components/courses/ProfileFollowUp.vue
Labels: dev

#925 COM-1760: endDate non excluded
  src/modules/client/pages/ni/courses/Dashboard.vue
Labels: dev

#923 Com 1748
  src/modules/client/mixins/payMixin.js
  src/modules/client/pages/ni/pay/ToPay.vue
Labels: dev

#924 COM-1753 add traineesCount
  src/core/mixins/eLearningCourseDirectoryMixin.js
  src/modules/client/pages/ni/courses/ELearningCoursesDirectory.vue
  src/modules/vendor/pages/ni/management/ELearningCoursesDirectory.vue
Labels: dev

#926 [FIX] COM-1748
  src/modules/client/mixins/payMixin.js
Labels: dev

#928 COM-1827 npm update
  package-lock.json
  package.json
Labels: dev

#931 COM-1832 - update counter limits
  src/modules/client/pages/ni/auxiliaries/Dashboard.vue
Labels: bug, dev

#932 COM-1832 - update counter limits
  src/modules/client/pages/ni/auxiliaries/Dashboard.vue
Labels: bug, staging

#935 Com 1757
  src/core/components/courses/ELearningIndicator.vue
  src/core/components/learners/ProfileCourses.vue
  src/core/components/table/ExpandingTable.vue
  src/modules/client/pages/ni/courses/Dashboard.vue
Labels: dev

#936 COM-1835 - display all lines of table
  src/modules/client/components/customers/billing/CustomerBillingTable.vue
Labels: bug, dev

#933 COM-1799
  src/modules/client/pages/ni/courses/Dashboard.vue
Labels: dev

#930 Com 1756
  src/core/helpers/date.js
  src/core/mixins/learnerDirectoryMixin.js
  src/modules/client/pages/ni/courses/LearnersDirectory.vue
  src/modules/vendor/pages/ni/users/learners/LearnersDirectory.vue
Labels: dev

#937 COM-1836 - use screen width to display menu burger
  src/store/main.js
Labels: bug, dev

#939 COM-1799 center active trainees count
  src/modules/client/pages/ni/courses/Dashboard.vue
Labels: dev

#938 COM-1817
  src/core/components/courses/ProfileTraineeFollowUp.vue
Labels: dev

#940 Com 1800
  src/modules/client/pages/ni/courses/Dashboard.vue
Labels: dev

#945 Com 1798
  src/core/mixins/courseFiltersMixin.js
  src/core/pages/courses/BlendedCourseProfile.vue
  src/modules/client/pages/ni/courses/BlendedCoursesDirectory.vue
  src/modules/vendor/pages/ni/management/BlendedCoursesDirectory.vue
  src/modules/vendor/pages/trainers/management/BlendedCoursesDirectory.vue
  src/store/course.js
  src/store/index.js
Labels: dev

#946 Com 1818
  src/core/api/Courses.js
  src/core/components/ProfileHeader.vue
  src/core/components/courses/ProfileTraineeFollowUp.vue
  src/core/components/courses/QuestionAnswerChart.vue
  src/core/helpers/rbac.js
  src/modules/vendor/pages/trainers/management/QuestionnaireAnswers.vue
  src/modules/vendor/router/routes.js
Labels: dev

#949 Com 1786 design system
  src/core/components/ProfileTabs.vue
  src/core/components/courses/CourseInfoLink.vue
  src/core/components/courses/SlotContainer.vue
  src/core/components/learners/ProfileCourses.vue
  src/core/pages/signin/Authenticate.vue
  src/css/app.styl
  src/css/chip.styl
  src/css/history.styl
  src/css/planning.styl
  src/css/table.styl
  src/modules/client/components/auxiliary/AuxiliaryProfileHeader.vue
  src/modules/client/components/planning/AuxiliaryIndicators.vue
  src/modules/client/components/planning/ChipCustomerIndicator.vue
  src/modules/client/components/planning/Planning.vue
  src/modules/client/layouts/Layout.vue
  src/modules/client/pages/ni/billing/ToBill.vue
  src/modules/vendor/components/programs/cards/CardCreationModal.vue
  src/modules/vendor/components/programs/cards/templates/TextMedia.vue
  src/modules/vendor/components/programs/cards/templates/TitleTextMedia.vue
  src/modules/vendor/layouts/Layout.vue
Labels: dev

#947 COM-1816 - require phone on client learner directory and vendor train…
  src/core/components/courses/LearnerCreationModal.vue
  src/core/components/courses/TraineeTable.vue
  src/modules/client/pages/ni/courses/LearnersDirectory.vue
Labels: dev
