Repository CompaniTech/compani-webapp, pull requests merged in 2021-09, with the labels that each got.

#1221 Com 2315
  src/core/api/GoogleDrive.js
  src/modules/client/pages/customers/Subscriptions.vue
  src/modules/client/pages/ni/config/RhConfig.vue
Labels: dev

#1222 Com 2296
  src/core/api/BillingItems.js
  src/core/data/constants.js
  src/modules/client/components/config/BillingItemCreationModal.vue
  src/modules/client/pages/ni/config/CustomersConfig.vue
Labels: dev

#1224 Com 2318
  src/core/components/form/MultipleFilesUploader.vue
  src/modules/client/components/auxiliary/ProfileInfo.vue
  src/modules/client/components/customers/infos/ProfileInfo.vue
  src/modules/client/pages/customers/Subscriptions.vue
Labels: dev

#1227 COM-2305: change green
  src/core/components/courses/ConnectedDot.vue
  src/core/components/popup/notify.js
  src/css/colors.styl
  src/css/icon.styl
  src/css/quasar.variables.styl
  src/modules/client/components/auxiliary/AuxiliaryProfileHeader.vue
  src/modules/client/components/auxiliary/ProfileInfo.vue
  src/modules/client/components/contracts/ContractsCell.vue
  src/modules/client/components/customers/CustomerProfileHeader.vue
  src/modules/client/pages/ni/auxiliaries/Dashboard.vue
  src/modules/vendor/components/programs/ProfileContent.vue
Labels: dev

#1229 Com 2321
  src/modules/client/components/customers/billing/CustomerBillingTable.vue
  src/modules/client/components/customers/billing/ProfileBilling.vue
Labels: dev

#1223 Com 2294
  src/core/data/constants.js
  src/modules/client/components/planning/EventCreationModal.vue
  src/modules/client/components/planning/EventEditionModal.vue
  src/modules/client/mixins/planningActionMixin.js
  src/modules/client/mixins/planningModalMixin.js
Labels: dev

#1225 COM-2306: remove useless params
  src/core/api/Companies.js
Labels: dev

#1228 Com 2301
  src/core/api/Courses.js
  src/core/components/courses/LearnerCreationModal.vue
  src/core/components/courses/TraineeAdditionModal.vue
  src/core/components/courses/TraineeTable.vue
  src/modules/client/pages/ni/courses/LearnersDirectory.vue
Labels: dev

#1231 Com 2322
  src/core/components/form/MultipleFilesUploader.vue
  src/core/helpers/file.js
  src/modules/client/components/auxiliary/ProfilePay.vue
  src/modules/client/components/contracts/ContractsCell.vue
  src/modules/client/components/customers/billing/CustomerBillingTable.vue
  src/modules/client/pages/customers/Subscriptions.vue
  src/modules/client/pages/ni/auxiliaries/StaffRegister.vue
  src/modules/client/pages/ni/config/RhConfig.vue
  src/modules/client/pages/ni/pay/Absences.vue
Labels: dev

#1232 COM-2307: accept link request
  src/core/api/CompanyLinkRequests.js
  src/core/components/CompanyLinkRequestCell.vue
  src/css/colors.styl
  src/css/quasar.variables.styl
  src/modules/client/components/planning/ChipAuxiliaryIndicator.vue
  src/modules/client/components/planning/ChipCustomerIndicator.vue
  src/modules/client/pages/ni/auxiliaries/Dashboard.vue
  src/modules/client/pages/ni/courses/Dashboard.vue
Labels: dev

#1236 COM-2327 - filter event histories in back
  src/modules/client/components/planning/EventHistoryFeed.vue
  src/modules/client/pages/ni/planning/AuxiliaryPlanning.vue
Labels: bug, dev

#1234 Com 2322 2
  src/modules/client/components/customers/infos/ProfileInfo.vue
  src/modules/client/pages/auxiliaries/administrative/Documents.vue
Labels: dev

#1238 COM-2319 - update file uploader
  src/core/components/form/FileUploader.vue
  src/core/components/form/MultipleFilesUploader.vue
  src/modules/client/components/auxiliary/ProfileInfo.vue
  src/modules/client/components/customers/infos/ProfileInfo.vue
  src/modules/client/components/planning/EventCreationModal.vue
  src/modules/client/components/planning/EventEditionModal.vue
  src/modules/client/pages/customers/Subscriptions.vue
  src/modules/client/pages/ni/config/CustomersConfig.vue
  src/modules/client/pages/ni/config/RhConfig.vue
  src/modules/vendor/components/programs/ProfileInfo.vue
  src/modules/vendor/components/programs/cards/templates/TextMedia.vue
  src/modules/vendor/components/programs/cards/templates/TitleTextMedia.vue
Labels: dev

#1235 COM-2302: add trainer selector for questionnaire answers
  src/core/components/courses/QuestionAnswerChart.vue
  src/core/components/courses/SurveyChart.vue
  src/modules/vendor/components/questionnaires/ProfileAnswers.vue
Labels: dev

#1230 Com 2298
  src/core/api/BillingItems.js
  src/core/api/Bills.js
  src/core/helpers/rbac.js
  src/modules/client/components/customers/billing/CustomerBillingTable.vue
  src/modules/client/components/customers/billing/ManualBillCreationModal.vue
  src/modules/client/components/customers/billing/ProfileBilling.vue
  src/modules/client/mixins/menuItemsMixin.js
  src/modules/client/pages/ni/billing/ManualBills.vue
  src/modules/client/pages/ni/billing/ToBill.vue
  src/modules/client/router/routes.js
Labels: dev

#1237 COM-2308 : remove link request
  src/core/api/CompanyLinkRequests.js
  src/core/components/CompanyLinkRequestCell.vue
  src/modules/client/pages/ni/courses/Dashboard.vue
Labels: dev

#1243 COM-2308: created calls in a promise.all
  src/modules/client/pages/ni/courses/Dashboard.vue
Labels: dev

#1239 COM-2294 - handle repetitions
  src/modules/client/mixins/planningActionMixin.js
Labels: dev

#1240 Com 2319 staging
  src/core/api/GoogleDrive.js
  src/core/components/form/FileUploader.vue
  src/core/components/form/MultipleFilesUploader.vue
  src/core/helpers/file.js
  src/modules/client/components/auxiliary/ProfileInfo.vue
  src/modules/client/components/auxiliary/ProfilePay.vue
  src/modules/client/components/contracts/ContractsCell.vue
  src/modules/client/components/customers/billing/CustomerBillingTable.vue
  src/modules/client/components/customers/billing/ProfileBilling.vue
  src/modules/client/components/customers/infos/ProfileInfo.vue
  src/modules/client/components/planning/EventCreationModal.vue
  src/modules/client/components/planning/EventEditionModal.vue
  src/modules/client/pages/auxiliaries/administrative/Documents.vue
  src/modules/client/pages/customers/Subscriptions.vue
  src/modules/client/pages/ni/auxiliaries/StaffRegister.vue
  src/modules/client/pages/ni/config/CustomersConfig.vue
  src/modules/client/pages/ni/config/RhConfig.vue
  src/modules/client/pages/ni/pay/Absences.vue
  src/modules/vendor/components/programs/ProfileInfo.vue
  src/modules/vendor/components/programs/cards/templates/TextMedia.vue
  src/modules/vendor/components/programs/cards/templates/TitleTextMedia.vue
Labels: staging

#1247 Staging
  src/core/api/GoogleDrive.js
  src/core/components/form/FileUploader.vue
  src/core/components/form/MultipleFilesUploader.vue
  src/core/helpers/file.js
  src/modules/client/components/auxiliary/ProfileInfo.vue
  src/modules/client/components/auxiliary/ProfilePay.vue
  src/modules/client/components/contracts/ContractsCell.vue
  src/modules/client/components/customers/billing/CustomerBillingTable.vue
  src/modules/client/components/customers/billing/ProfileBilling.vue
  src/modules/client/components/customers/infos/ProfileInfo.vue
  src/modules/client/components/planning/EventCreationModal.vue
  src/modules/client/components/planning/EventEditionModal.vue
  src/modules/client/pages/auxiliaries/administrative/Documents.vue
  src/modules/client/pages/customers/Subscriptions.vue
  src/modules/client/pages/ni/auxiliaries/StaffRegister.vue
  src/modules/client/pages/ni/config/CustomersConfig.vue
  src/modules/client/pages/ni/config/RhConfig.vue
  src/modules/client/pages/ni/pay/Absences.vue
  src/modules/vendor/components/programs/ProfileInfo.vue
  src/modules/vendor/components/programs/cards/templates/TextMedia.vue
  src/modules/vendor/components/programs/cards/templates/TitleTextMedia.vue
Labels: master

#1242 Com 2297
  src/core/components/form/Select.vue
  src/modules/client/components/config/ServiceCreationModal.vue
  src/modules/client/components/config/ServiceEditionModal.vue
  src/modules/client/components/customers/billing/CreditNoteCreationModal.vue
  src/modules/client/components/customers/billing/ManualBillCreationModal.vue
  src/modules/client/pages/ni/config/CustomersConfig.vue
Labels: dev

#1254 COM-2346 - Fix billingItem list bug
  src/modules/client/pages/ni/config/CustomersConfig.vue
Labels: dev

#1253 Com 2298 get
  src/core/api/Bills.js
  src/modules/client/pages/ni/billing/ManualBills.vue
Labels: dev

#1255 MES 13/09
  src/core/api/Bills.js
  src/core/components/form/Select.vue
  src/modules/client/components/config/ServiceCreationModal.vue
  src/modules/client/components/config/ServiceEditionModal.vue
  src/modules/client/components/customers/billing/CreditNoteCreationModal.vue
  src/modules/client/components/customers/billing/ManualBillCreationModal.vue
  src/modules/client/pages/ni/billing/ManualBills.vue
  src/modules/client/pages/ni/config/CustomersConfig.vue
Labels: staging

#1256 Com 2347 - npm update
  package-lock.json
Labels: dependances

#1258 MES 14/09
  package-lock.json
  src/core/components/courses/ProfileAdmin.vue
  src/core/helpers/date.js
  src/core/helpers/utils.js
  src/core/mixins/eLearningCourseDirectoryMixin.js
  src/modules/client/components/auxiliary/ProfileContracts.vue
  src/modules/client/components/contracts/ContractsCell.vue
  src/modules/client/components/customers/infos/ProfileInfo.vue
  src/modules/client/components/planning/ChipCustomerIndicator.vue
  src/modules/client/pages/ni/config/CustomersConfig.vue
Labels: staging

#1260 COM-2333 company filter
  src/modules/vendor/components/questionnaires/ProfileAnswers.vue
Labels: dev

#1262 COM-2334: filter by program
  src/core/api/Programs.js
  src/modules/vendor/components/questionnaires/ProfileAnswers.vue
Labels: dev

#1261 COM-2328 - Handle billingItems in draft pay
  src/modules/client/components/table/ToBillRow.vue
Labels: dev

#1264 COM-2335: reset filters
  src/modules/vendor/components/questionnaires/ProfileAnswers.vue
Labels: dev

#1267 COM-2355-downgrade downgrade axios to 0.21.1
  package-lock.json
  package.json
Labels: dependances

#1268 COM-2355-downgrade downgrade axios to 0.21.1
  package-lock.json
  package.json
Labels: staging

#1269 MEP 21/09
  package-lock.json
  package.json
Labels: master

#1271 COM-2355: infinite loop
  package-lock.json
  package.json
  src/core/helpers/vuelidateCustomVal.js
Labels: dev, dependances

#1272 COM-2359: display good VAT
  src/modules/client/pages/ni/config/CustomersConfig.vue
Labels: dev

#1273 COM-2358 fix border
  src/core/components/form/OptionGroup.vue
Labels: bug, dev

#1274 COM-2363 - rgpd and cgu from compani.fr
  src/core/components/Button.vue
  src/core/pages/AccountInfo.vue
  src/statics/cguCompani.html
  src/statics/rgpd.html
Labels: bug, dev

#1277 COM-2354: can't have two versions with same date
  src/modules/client/components/config/ServiceEditionModal.vue
  src/modules/client/pages/ni/config/CustomersConfig.vue
Labels: dev

#1276 COM-2384 - fix startDate on toBill
  src/core/components/Button.vue
  src/modules/client/components/table/ToBillRow.vue
  src/modules/client/pages/ni/billing/ToBill.vue
Labels: bug, dev

#1279 COM-2332 - max 2 fractions in numbers
  src/core/helpers/vuelidateCustomVal.js
  src/modules/client/components/config/BillingItemCreationModal.vue
  src/modules/client/mixins/configMixin.js
  src/modules/client/pages/ni/config/CustomersConfig.vue
Labels: bug, dev

#1275 Com 2345
  src/modules/client/pages/ni/billing/CreditNotes.vue
Labels: dev

#1282 MES 28/09 - resolve conflicts
  package-lock.json
  src/core/api/Programs.js
  src/core/components/Button.vue
  src/core/components/form/OptionGroup.vue
  src/core/helpers/utils.js
  src/core/helpers/vuelidateCustomVal.js
  src/core/pages/AccountInfo.vue
  src/modules/client/components/config/BillingItemCreationModal.vue
  src/modules/client/components/config/ServiceEditionModal.vue
  src/modules/client/components/customers/billing/CustomerBillingTable.vue
  src/modules/client/components/customers/billing/ManualBillCreationModal.vue
  src/modules/client/components/table/ToBillRow.vue
  src/modules/client/mixins/configMixin.js
  src/modules/client/pages/ni/billing/CreditNotes.vue
  src/modules/client/pages/ni/billing/ToBill.vue
  src/modules/client/pages/ni/config/CustomersConfig.vue
  src/modules/vendor/components/questionnaires/ProfileAnswers.vue
  src/statics/cguCompani.html
  src/statics/rgpd.html
Labels: staging

#1283 MEP 29/09
  package-lock.json
  src/core/api/Programs.js
  src/core/components/Button.vue
  src/core/components/form/OptionGroup.vue
  src/core/helpers/utils.js
  src/core/helpers/vuelidateCustomVal.js
  src/core/pages/AccountInfo.vue
  src/modules/client/components/config/BillingItemCreationModal.vue
  src/modules/client/components/config/ServiceEditionModal.vue
  src/modules/client/components/customers/billing/CustomerBillingTable.vue
  src/modules/client/components/customers/billing/ManualBillCreationModal.vue
  src/modules/client/components/table/ToBillRow.vue
  src/modules/client/mixins/configMixin.js
  src/modules/client/pages/ni/billing/CreditNotes.vue
  src/modules/client/pages/ni/billing/ToBill.vue
  src/modules/client/pages/ni/config/CustomersConfig.vue
  src/modules/vendor/components/questionnaires/ProfileAnswers.vue
  src/statics/cguCompani.html
  src/statics/rgpd.html
Labels: master
