Repository CompaniTech/compani-webapp, pull requests merged in 2021-08, with the labels that each got.

#1201 COM-2109: inclusive
  src/core/components/courses/AttendanceSheetAdditionModal.vue
  src/core/components/courses/CourseHistory.vue
  src/core/components/courses/LearnerCreationModal.vue
  src/core/components/courses/ProfileOrganization.vue
  src/core/components/courses/TraineeEditionModal.vue
  src/core/components/courses/TraineeFollowUpTable.vue
  src/core/components/courses/TraineeTable.vue
  src/core/components/table/AttendanceTable.vue
  src/core/components/table/CoachCreationModal.vue
  src/core/components/table/CoachEditionModal.vue
  src/core/components/table/CoachList.vue
  src/core/components/table/TraineeAttendanceCreationModal.vue
  src/core/data/constants.js
  src/core/mixins/courseFiltersMixin.js
  src/core/mixins/courseMixin.js
  src/core/mixins/learnerMixin.js
  src/core/pages/signin/ForgotPassword.vue
  src/modules/client/components/auxiliary/AuxiliaryCreationModal.vue
  src/modules/client/components/auxiliary/AuxiliaryProfileHeader.vue
  src/modules/client/components/auxiliary/ProfileContracts.vue
  src/modules/client/components/customers/CustomerProfileHeader.vue
  src/modules/client/components/customers/PartnerCreationModal.vue
  src/modules/client/components/customers/PartnerEditionModal.vue
  src/modules/client/components/customers/ProfileFollowUp.vue
  src/modules/client/components/customers/billing/CreditNoteCreationModal.vue
  src/modules/client/components/customers/billing/CreditNoteEditionModal.vue
  src/modules/client/components/customers/billing/ProfileBilling.vue
  src/modules/client/components/customers/infos/CustomerPartnerCreationModal.vue
  src/modules/client/components/customers/infos/FundingCreationModal.vue
  src/modules/client/components/customers/infos/FundingEditionModal.vue
  src/modules/client/components/customers/infos/HelperCreationModal.vue
  src/modules/client/components/customers/infos/ProfileInfo.vue
  src/modules/client/components/customers/infos/StopSupportModal.vue
  src/modules/client/components/planning/DeleteEventsModal.vue
  src/modules/client/components/table/CustomerNotesContainer.vue
  src/modules/client/mixins/helperMixin.js
  src/modules/client/mixins/paymentMixin.js
  src/modules/client/mixins/planningActionMixin.js
  src/modules/client/pages/customers/Contact.vue
  src/modules/client/pages/ni/auxiliaries/Directory.vue
  src/modules/client/pages/ni/billing/CreditNotes.vue
  src/modules/client/pages/ni/config/CompanyConfig.vue
  src/modules/client/pages/ni/config/CustomersConfig.vue
  src/modules/client/pages/ni/config/RhConfig.vue
  src/modules/client/pages/ni/config/TagConfig.vue
  src/modules/client/pages/ni/courses/LearnersDirectory.vue
  src/modules/client/pages/ni/customers/CustomersDirectory.vue
  src/modules/client/pages/ni/customers/CustomersFundingsMonitoring.vue
  src/modules/client/pages/ni/customers/PartnerOrganizationProfile.vue
  src/modules/client/pages/ni/planning/CustomerPlanning.vue
  src/modules/vendor/components/programs/TesterCreationModal.vue
  src/modules/vendor/components/programs/TesterTable.vue
  src/modules/vendor/components/trainers/ProfileInfo.vue
  src/modules/vendor/components/trainers/TrainerCreationModal.vue
  src/modules/vendor/pages/ni/users/trainers/TrainerProfile.vue
  src/modules/vendor/pages/ni/users/trainers/TrainersDirectory.vue
Labels: dev

#1202 Com 2223
  src/core/components/form/SelectSector.vue
  src/css/header.styl
  src/modules/client/components/auxiliary/ProfileInfo.vue
  src/modules/client/components/customers/infos/ProfileInfo.vue
  src/modules/client/pages/ni/billing/ClientsBalances.vue
  src/modules/client/pages/ni/billing/ToBill.vue
  src/modules/client/pages/ni/config/CustomersConfig.vue
  src/modules/client/pages/ni/customers/CustomersFundingsMonitoring.vue
  src/modules/client/pages/ni/exports/DataExports.vue
  src/modules/client/pages/ni/exports/HistoryExports.vue
  src/modules/client/pages/ni/pay/ContractEnds.vue
  src/modules/client/pages/ni/pay/ToPay.vue
Labels: bug, dev

#1203 COM-2257 remove partnerorga from payload
  src/modules/client/pages/ni/customers/PartnerOrganizationProfile.vue
Labels: dev

#1205 Com 2205 helper
  src/css/colors.styl
  src/modules/client/components/table/FundingGridTable.vue
  src/modules/client/pages/customers/Subscriptions.vue
Labels: bug, dev

#1208 COM-2109: forgotten words
  src/modules/client/components/customers/infos/HelperEditionModal.vue
  src/modules/client/mixins/helperMixin.js
Labels: dev

#1207 Com 2275
  src/modules/client/components/contracts/ContractsCell.vue
  src/modules/client/components/customers/infos/ProfileInfo.vue
  src/modules/client/helpers/generateContractFields.js
  src/modules/client/helpers/tags.js
  src/modules/client/mixins/contractMixin.js
  src/modules/client/pages/ni/config/TagConfig.vue
Labels: dev

#1210 Com 2246
  src/modules/client/components/auxiliary/AuxiliaryProfileHeader.vue
  src/modules/client/components/auxiliary/ProfileContracts.vue
Labels: dev

#1212 COM-2276 - do not add auxiliary in array if already inside
  src/modules/client/pages/ni/planning/AuxiliaryPlanning.vue
Labels: dev

#1211 Com 1682
  package-lock.json
  package.json
  quasar.extensions.json
  test/cypress/integration/authenticate.spec.js
  test/cypress/integration/customer/billing.spec.js
  test/cypress/integration/customer/contact.spec.js
  test/cypress/integration/customer/subscription.spec.js
  test/cypress/integration/ni/billing/toBill.spec.js
  test/cypress/plugins/index.js
  test/cypress/support/commands.js
Labels: dev

#1219 MES 30.08.2021 | COM-2312-staging
  src/modules/client/pages/ni/auxiliaries/Dashboard.vue
Labels: staging

#1220 MEP 31/08
  src/modules/client/pages/ni/auxiliaries/Dashboard.vue
Labels: master
