Repository CompaniTech/compani-webapp, pull requests merged in 2021-03, with the labels that each got.

#998 Remove console lint error in dev environment
  .eslintrc.js
Labels: dev

#995 WEBAPP - npm update
  package-lock.json
  package.json
Labels: dev

#999 COM-1888 - Fix sort on month in tppBillSlips
  src/modules/client/pages/ni/billing/TppBillSlips.vue
Labels: dev

#997 COM-1845: chart for actities by month
  src/core/components/courses/ProfileFollowUp.vue
  src/core/mixins/chartMixin.js
  src/modules/client/pages/ni/courses/Dashboard.vue
Labels: dev

#996 Com 1923
  src/core/data/constants.js
  src/core/helpers/utils.js
  src/modules/client/components/config/ServiceHistoryModal.vue
  src/modules/client/components/config/SurchargeCreationModal.vue
  src/modules/client/components/config/SurchargeEditionModal.vue
  src/modules/client/pages/ni/config/CustomersConfig.vue
Labels: dev

#1000 COM-1945 fix connection for trainers
  src/core/data/user.js
  src/modules/client/mixins/configMixin.js
  src/modules/client/pages/ni/config/RhConfig.vue
Labels: dev

#1003 MEP - fix bug connexion aidant
  src/core/data/user.js
  src/modules/client/mixins/configMixin.js
  src/modules/client/pages/ni/config/RhConfig.vue
Labels: master

#993 COM-1882
  src/modules/client/components/customers/billing/CreditNoteEditionModal.vue
  src/modules/client/components/customers/billing/PaymentCreationModal.vue
  src/modules/client/components/customers/billing/PaymentEditionModal.vue
  src/modules/client/components/customers/billing/ProfileBilling.vue
  src/modules/client/pages/ni/billing/ClientsBalances.vue
Labels: dev

#1005 COM-1897: add graph in learner
  src/core/components/learners/ProfileCourses.vue
  src/core/helpers/date.js
  src/modules/client/pages/ni/courses/Dashboard.vue
Labels: dev

#1007 COM-1924: add cash as a payment method
  src/core/data/constants.js
  src/modules/client/components/customers/billing/CustomerBillingTable.vue
  src/modules/client/components/customers/billing/ProfileBilling.vue
Labels: dev

#1004 COM-1910 - Prevent step deletion if step is linked to courseSlot
  src/modules/vendor/components/programs/ProfileContent.vue
Labels: dev

#1006 Com 1938
  src/modules/client/components/auxiliary/ProfileContracts.vue
  src/modules/client/components/contracts/ContractCreationModal.vue
  src/modules/client/components/contracts/ContractEndingModal.vue
  src/modules/client/components/contracts/VersionCreationModal.vue
  src/modules/client/components/contracts/VersionEditionModal.vue
  src/modules/client/pages/ni/pay/ContractMonitoring.vue
Labels: dev

#1009 COM-1894: add is connected column
  src/core/components/courses/ConnectedDot.vue
  src/core/components/courses/TraineeFollowUpTable.vue
  src/core/mixins/traineeFollowUpTableMixin.js
Labels: dev

#1008 COM-1923 - Fix modal opening condition
  src/modules/client/mixins/payMixin.js
  src/modules/client/pages/ni/pay/ContractEnds.vue
  src/modules/client/pages/ni/pay/ToPay.vue
Labels: dev

#1010 Com 1939
  src/core/components/table/SimpleTable.vue
  src/core/mixins/passwordMixin.js
  src/core/pages/AccountInfo.vue
  src/core/pages/NewPasswordModal.vue
  src/core/pages/signin/ResetPassword.vue
  src/modules/client/components/config/AdministrativeDocumentCreationModal.vue
  src/modules/client/components/config/InternalHourCreationModal.vue
  src/modules/client/components/table/ToBillRow.vue
  src/modules/client/pages/ni/billing/ToBill.vue
  src/modules/client/pages/ni/config/RhConfig.vue
Labels: dev

#1014 COM-1929 remove cookie remove for expired cookies
  src/core/api/Authentication.js
Labels: dev

#1013 COM-1894: fix column display
  src/core/components/courses/ProfileTraineeFollowUp.vue
  src/core/components/courses/TraineeFollowUpTable.vue
  src/core/components/learners/ProfileCourses.vue
  src/core/components/table/ExpandingTable.vue
Labels: dev

#1017 MEP
  .eslintrc.js
  package-lock.json
  package.json
  src/core/api/Authentication.js
  src/core/components/courses/ConnectedDot.vue
  src/core/components/courses/ProfileFollowUp.vue
  src/core/components/courses/ProfileTraineeFollowUp.vue
  src/core/components/courses/TraineeFollowUpTable.vue
  src/core/components/learners/ProfileCourses.vue
  src/core/components/table/ExpandingTable.vue
  src/core/components/table/SimpleTable.vue
  src/core/data/constants.js
  src/core/helpers/ability.js
  src/core/helpers/date.js
  src/core/helpers/utils.js
  src/core/mixins/chartMixin.js
  src/core/mixins/passwordMixin.js
  src/core/mixins/traineeFollowUpTableMixin.js
  src/core/pages/AccountInfo.vue
  src/core/pages/NewPasswordModal.vue
  src/core/pages/signin/ResetPassword.vue
  src/modules/client/components/auxiliary/ProfileContracts.vue
  src/modules/client/components/config/AdministrativeDocumentCreationModal.vue
  src/modules/client/components/config/InternalHourCreationModal.vue
  src/modules/client/components/config/ServiceHistoryModal.vue
  src/modules/client/components/config/SurchargeCreationModal.vue
  src/modules/client/components/config/SurchargeEditionModal.vue
  src/modules/client/components/contracts/ContractCreationModal.vue
  src/modules/client/components/contracts/ContractEndingModal.vue
  src/modules/client/components/contracts/ContractsCell.vue
  src/modules/client/components/contracts/VersionCreationModal.vue
  src/modules/client/components/contracts/VersionEditionModal.vue
  src/modules/client/components/customers/billing/CreditNoteEditionModal.vue
  src/modules/client/components/customers/billing/CustomerBillingTable.vue
  src/modules/client/components/customers/billing/PaymentCreationModal.vue
  src/modules/client/components/customers/billing/PaymentEditionModal.vue
  src/modules/client/components/customers/billing/ProfileBilling.vue
  src/modules/client/components/table/ToBillRow.vue
  src/modules/client/mixins/contractMixin.js
  src/modules/client/mixins/payMixin.js
  src/modules/client/mixins/planningActionMixin.js
  src/modules/client/pages/ni/billing/ClientsBalances.vue
  src/modules/client/pages/ni/billing/ToBill.vue
  src/modules/client/pages/ni/billing/TppBillSlips.vue
  src/modules/client/pages/ni/config/CustomersConfig.vue
  src/modules/client/pages/ni/config/RhConfig.vue
  src/modules/client/pages/ni/courses/Dashboard.vue
  src/modules/client/pages/ni/pay/ContractEnds.vue
  src/modules/client/pages/ni/pay/ContractMonitoring.vue
  src/modules/client/pages/ni/pay/ToPay.vue
  src/modules/vendor/components/programs/ProfileContent.vue
  src/store/course.js
Labels: master

#1019 COM-1958: change config in pedagogy
  src/core/helpers/rbac.js
  src/modules/vendor/components/programs/ProfileContent.vue
  src/modules/vendor/mixins/menuItemsMixin.js
  src/modules/vendor/pages/ni/pedagogy/ActivityProfile.vue
  src/modules/vendor/pages/ni/pedagogy/CategoriesDirectory.vue
  src/modules/vendor/pages/ni/pedagogy/ProgramProfile.vue
  src/modules/vendor/pages/ni/pedagogy/ProgramsDirectory.vue
  src/modules/vendor/router/routes.js
Labels: dev

#1018 COM-1968 - npm update
  package-lock.json
  package.json
  server.js
  src/core/components/form/SearchAddress.vue
Labels: dev

#1020 Com 1925
  src/core/components/courses/BlendedCourseProfileHeader.vue
  src/core/components/courses/CourseCell.vue
  src/core/mixins/blendedCourseProfileMixin.js
  src/core/mixins/courseMixin.js
  src/core/pages/courses/BlendedCourseProfile.vue
  src/modules/client/pages/ni/courses/BlendedCourseProfile.vue
  src/modules/client/router/routes.js
  src/modules/vendor/pages/ni/management/BlendedCourseProfile.vue
  src/modules/vendor/router/routes.js
Labels: dev

#1026 COM-1965 - remove user_id from cookies
  src/core/api/Authentication.js
  src/core/helpers/alenvi.js
  src/router/index.js
  src/store/main.js
Labels: dev

#1023 COM-1952 - Add lastCesuPaymentDate to client balance
  src/core/helpers/utils.js
  src/modules/client/components/customers/billing/CustomerBillingTable.vue
  src/modules/client/components/table/ToBillRow.vue
  src/modules/client/pages/ni/billing/ClientsBalances.vue
Labels: dev

#1027 Boy scoot
  src/core/components/courses/AttendanceSheetAdditionModal.vue
  src/core/components/courses/ProfileAdmin.vue
  src/core/components/courses/ProfileTraineeFollowUp.vue
  src/core/components/courses/SlotContainer.vue
  src/core/components/courses/SmsDetailsModal.vue
  src/core/components/form/DateInput.vue
  src/core/components/form/Select.vue
  src/core/components/table/TraineeAttendanceCreationModal.vue
  src/core/helpers/utils.js
  src/core/mixins/courseFiltersMixin.js
  src/core/mixins/eLearningCourseDirectoryMixin.js
Labels: dev

#1025 COM-1875: default value for filter on trello
  src/core/components/courses/SlotContainer.vue
  src/core/components/form/Select.vue
  src/core/data/user.js
  src/modules/client/components/auxiliary/ProfileInfo.vue
  src/modules/client/mixins/menuItemsMixin.js
  src/modules/client/pages/ni/auxiliaries/Directory.vue
  src/modules/client/pages/ni/billing/CreditNotes.vue
  src/modules/client/pages/ni/config/CustomersConfig.vue
  src/modules/vendor/components/programs/SubProgramPublicationModal.vue
Labels: dev

#1024 Com 1956
  src/core/api/Programs.js
  src/modules/vendor/components/programs/ProfileInfo.vue
  src/modules/vendor/components/programs/TesterCreationModal.vue
  src/modules/vendor/components/programs/TesterTable.vue
Labels: dev

#1029 Validations accessrules
  src/modules/vendor/components/programs/SubProgramPublicationModal.vue
Labels: bug, dev

#1030 Boy scoot date 2
  src/core/components/courses/AttendanceSheetAdditionModal.vue
  src/core/helpers/utils.js
  src/core/mixins/chartMixin.js
  src/modules/client/components/auxiliary/ProfilePay.vue
  src/modules/client/components/contracts/ContractsCell.vue
  src/modules/client/components/customers/infos/ProfileInfo.vue
  src/modules/client/mixins/helperMixin.js
  src/modules/client/pages/customers/Subscriptions.vue
Labels: dev

#1028 COM-1946: refacto creditNote
  src/core/helpers/date.js
  src/modules/client/components/customers/billing/CreditNoteCreationModal.vue
  src/modules/client/components/customers/billing/CreditNoteEditionModal.vue
  src/modules/client/pages/ni/billing/CreditNotes.vue
Labels: dev

#1022 Com 1925 2
  src/core/api/Users.js
  src/core/components/courses/ProfileTraineeFollowUp.vue
  src/core/components/table/AttendanceTable.vue
  src/core/helpers/ability.js
  src/modules/client/pages/ni/courses/BlendedCourseProfile.vue
Labels: dev

#1034 Boyscoot date 3
  src/core/components/courses/AttendanceSheetAdditionModal.vue
  src/core/components/courses/ProfileAdmin.vue
  src/core/components/courses/ProfileTraineeFollowUp.vue
  src/core/components/courses/SlotContainer.vue
  src/core/components/courses/SmsDetailsModal.vue
  src/core/components/form/DateInput.vue
  src/core/components/learners/ProfileCourses.vue
  src/core/components/table/TraineeAttendanceCreationModal.vue
  src/core/helpers/date.js
  src/core/helpers/utils.js
  src/core/mixins/courseFiltersMixin.js
  src/core/mixins/eLearningCourseDirectoryMixin.js
  src/modules/client/components/auxiliary/ProfilePay.vue
  src/modules/client/components/contracts/ContractsCell.vue
  src/modules/client/components/customers/ProfileFollowUp.vue
  src/modules/client/components/customers/billing/CustomerBillingTable.vue
  src/modules/client/components/customers/billing/ProfileBilling.vue
  src/modules/client/components/customers/infos/ProfileInfo.vue
  src/modules/client/components/table/ToBillRow.vue
  src/modules/client/mixins/fundingMixin.js
  src/modules/client/mixins/helperMixin.js
  src/modules/client/mixins/payMixin.js
  src/modules/client/pages/customers/Subscriptions.vue
  src/modules/client/pages/ni/auxiliaries/Directory.vue
  src/modules/client/pages/ni/auxiliaries/StaffRegister.vue
  src/modules/client/pages/ni/billing/ClientsBalances.vue
  src/modules/client/pages/ni/billing/CreditNotes.vue
  src/modules/client/pages/ni/billing/DebitsArchive.vue
  src/modules/client/pages/ni/customers/CustomersDirectory.vue
  src/modules/client/pages/ni/pay/Absences.vue
Labels: dev

#1035 Com 1946 edition
  src/core/components/courses/SmsSendingModal.vue
  src/modules/client/components/customers/billing/CreditNoteEditionModal.vue
  src/modules/client/pages/ni/billing/CreditNotes.vue
Labels: dev

#1033 COM-1955 add questionnaire page in elearning formation
  src/core/api/Courses.js
  src/modules/vendor/components/courses/ProfileQuestionnaires.vue
  src/modules/vendor/pages/ni/management/ELearningCourseProfile.vue
Labels: dev

#1032 Com 1962
  src/modules/client/components/customers/ProfileFollowUp.vue
  src/modules/client/components/customers/infos/FundingCreationModal.vue
  src/modules/client/components/customers/infos/FundingEditionModal.vue
  src/modules/client/components/customers/infos/ProfileInfo.vue
  src/modules/client/components/planning/EventEditionModal.vue
  src/modules/client/components/table/ToBillRow.vue
  src/modules/client/pages/ni/billing/ToBill.vue
  src/modules/vendor/components/courses/CourseCreationModal.vue
Labels: dev

#1037 Com 1946 creation
  .eslintrc.js
  src/core/helpers/vuelidateCustomVal.js
  src/modules/client/components/auxiliary/ProfileContracts.vue
  src/modules/client/components/customers/billing/CreditNoteCreationModal.vue
  src/modules/client/mixins/contractMixin.js
  src/modules/client/pages/ni/billing/CreditNotes.vue
Labels: dev

#1036 Remove missing user_id cookie in trainer route
  src/modules/vendor/router/routes.js
Labels: dev

#1040 COM-1951: remove questionnaire
  src/core/components/courses/ProfileTraineeFollowUp.vue
  src/core/data/constants.js
  src/core/helpers/rbac.js
  src/modules/vendor/pages/trainers/management/QuestionnaireAnswers.vue
  src/modules/vendor/router/routes.js
Labels: dev

#1039 Com 1954
  src/core/api/Payments.js
  src/core/data/constants.js
  src/modules/client/components/customers/billing/CustomerBillingTable.vue
  src/modules/client/components/customers/billing/ProfileBilling.vue
  src/modules/client/mixins/paymentMixin.js
  src/modules/client/pages/ni/billing/ClientsBalances.vue
Labels: dev

#1038 Com 1926
  src/core/components/courses/ProfileTraineeFollowUp.vue
  src/core/components/table/AttendanceTable.vue
  src/modules/client/pages/ni/courses/BlendedCourseProfile.vue
Labels: dev

#1043 COM-1985: npm update
  package-lock.json
  package.json
Labels: dependances

#1044 COM-1973: add questionnaire section to menu
  src/core/helpers/rbac.js
  src/modules/vendor/mixins/menuItemsMixin.js
  src/modules/vendor/pages/ni/pedagogy/CategoriesDirectory.vue
  src/modules/vendor/pages/ni/pedagogy/QuestionnairesDirectory.vue
  src/modules/vendor/router/routes.js
Labels: dev
