Repository CompaniTech/compani-webapp, pull requests merged in 2021-10, with the labels that each got.

#1288 COM-2400 - reset selected events on toggle
  src/modules/client/pages/ni/billing/CreditNotes.vue
Labels: bug, dev

#1286 [ne pas fusionner] COM-2344: update node js
  .github/workflows/lint.yml
  package-lock.json
  package.json
Labels: dependencies

#1291 COM-2398 - npm update
  package-lock.json
  package.json
Labels: dependances

#1293 COM-2405 fix deletion button disabled on contract page
  src/core/helpers/date.js
  src/modules/client/components/contracts/ContractsCell.vue
Labels: bug, dev

#1294 MES intermediaire
  src/core/helpers/date.js
  src/modules/client/components/contracts/ContractsCell.vue
Labels: bug, staging

#1292 COM-2372 add remote step type
  src/core/data/constants.js
  src/modules/vendor/components/programs/ProfileContent.vue
Labels: dev

#1295 COM-2385: disable SMS if no phone numbers
  src/core/components/courses/ProfileAdmin.vue
Labels: dev

#1297 COM-2392 - Add billFooter input
  src/modules/client/mixins/configMixin.js
  src/modules/client/pages/ni/config/CustomersConfig.vue
Labels: dev

#1306 MES - 12/10
  src/modules/client/pages/ni/billing/ToBill.vue
Labels: staging

#1310 COM-2432 fix displayed service name in subscription creation modal
  src/modules/client/components/customers/infos/ProfileInfo.vue
  src/modules/client/components/table/ToBillRow.vue
Labels: bug, dev

#1311 COM-2404: calculate netInclTaxes in backend
  src/modules/client/pages/ni/billing/ManualBills.vue
Labels: dev
