Repository CompaniTech/compani-webapp, pull requests merged in 2021-02, with the labels that each got.

#950 COM-1755 learner stats
  src/core/components/courses/ProfileFollowUp.vue
  src/core/components/courses/ProfileTraineeFollowUp.vue
  src/core/components/courses/TraineeFollowUpTable.vue
  src/core/mixins/traineeFollowUpTableMixin.js
Labels: dev

#953 COM-1870 npm update
  package-lock.json
  package.json
Labels: dev

#955 COM-1846: add checkbox for commutative answers on fillthegap cards
  src/modules/vendor/components/programs/cards/templates/FillTheGaps.vue
  src/modules/vendor/components/programs/cards/templates/QuestionAnswer.vue
Labels: dev

#958 Com 1856
  src/modules/client/components/customers/CustomerCreationModal.vue
  src/modules/client/components/customers/infos/FundingCreationModal.vue
  src/modules/client/components/customers/infos/FundingEditionModal.vue
  src/modules/client/components/customers/infos/HelperCreationModal.vue
  src/modules/client/components/customers/infos/HelperEditionModal.vue
  src/modules/client/components/customers/infos/ProfileInfo.vue
  src/modules/client/pages/ni/customers/CustomersDirectory.vue
Labels: dev

#959 COM-1876 - fix sms
  src/modules/client/pages/ni/auxiliaries/Directory.vue
Labels: bug, dev

#956 Com 1851 attendanceTable
  src/core/components/courses/ProfileTraineeFollowUp.vue
  src/core/components/courses/TraineeFollowUpTable.vue
  src/core/components/table/AttendanceTable.vue
  src/core/components/table/ExpandingTable.vue
Labels: dev

#960 COM-1851 add and view attendances
  src/core/api/Attendances.js
  src/core/components/table/AttendanceTable.vue
Labels: dev

#961 COM-1877 - Fix course in client ELearningCourseProfile
  src/core/mixins/traineeFollowUpTableMixin.js
Labels: dev

#963 COM-1851 remove attendance
  src/core/api/Attendances.js
  src/core/components/table/AttendanceTable.vue
Labels: dev

#962 Com 1843
  package-lock.json
  package.json
  src/core/components/LineChart.vue
  src/core/components/courses/ProfileFollowUp.vue
  src/core/components/learners/ProfileCourses.vue
Labels: dev

#964 COM-1843: fix bug if no data in a month
  src/core/components/courses/ProfileFollowUp.vue
  src/core/components/courses/ProfileTraineeFollowUp.vue
  src/core/mixins/traineeFollowUpTableMixin.js
Labels: dev

#966 COM-1864: export data in csv
  src/modules/client/pages/ni/billing/ClientsBalances.vue
Labels: dev

#965 COM-1851 table enhancements
  src/core/components/table/AttendanceTable.vue
Labels: dev

#967 COM-1864: disable download button if data not loaded
  src/modules/client/pages/ni/billing/ClientsBalances.vue
  src/modules/client/pages/ni/customers/CustomersFundingsMonitoring.vue
Labels: dev

#968 Com 1855 vu no-mutating prop
  src/core/components/table/Pagination.vue
  src/core/components/table/SimpleTable.vue
  src/modules/client/pages/auxiliaries/teams/TeamsDirectory.vue
  src/modules/client/pages/ni/billing/TppBillSlips.vue
Labels: dev

#970 COM-1908 dont take step.subprogram or granted
  src/modules/client/pages/ni/courses/Dashboard.vue
  src/modules/vendor/pages/ni/config/ActivityProfile.vue
Labels: dev

#971 Dev
  package-lock.json
  package.json
  src/core/api/Attendances.js
  src/core/components/LineChart.vue
  src/core/components/courses/ProfileFollowUp.vue
  src/core/components/courses/ProfileTraineeFollowUp.vue
  src/core/components/courses/TraineeFollowUpTable.vue
  src/core/components/learners/ProfileCourses.vue
  src/core/components/table/AttendanceTable.vue
  src/core/components/table/ExpandingTable.vue
  src/core/components/table/Pagination.vue
  src/core/components/table/SimpleTable.vue
  src/core/helpers/utils.js
  src/core/mixins/traineeFollowUpTableMixin.js
  src/modules/client/components/customers/CustomerCreationModal.vue
  src/modules/client/components/customers/infos/FundingCreationModal.vue
  src/modules/client/components/customers/infos/FundingEditionModal.vue
  src/modules/client/components/customers/infos/HelperCreationModal.vue
  src/modules/client/components/customers/infos/HelperEditionModal.vue
  src/modules/client/components/customers/infos/ProfileInfo.vue
  src/modules/client/mixins/payMixin.js
  src/modules/client/pages/auxiliaries/teams/TeamsDirectory.vue
  src/modules/client/pages/ni/auxiliaries/Directory.vue
  src/modules/client/pages/ni/billing/ClientsBalances.vue
  src/modules/client/pages/ni/billing/TppBillSlips.vue
  src/modules/client/pages/ni/courses/Dashboard.vue
  src/modules/client/pages/ni/customers/CustomersDirectory.vue
  src/modules/client/pages/ni/customers/CustomersFundingsMonitoring.vue
  src/modules/vendor/components/programs/cards/templates/FillTheGaps.vue
  src/modules/vendor/components/programs/cards/templates/OpenQuestion.vue
  src/modules/vendor/components/programs/cards/templates/QuestionAnswer.vue
  src/modules/vendor/components/programs/cards/templates/Survey.vue
  src/modules/vendor/pages/ni/config/ActivityProfile.vue
Labels: staging

#969 COM-1909 fix only one line
  src/core/components/table/AttendanceTable.vue
Labels: dev

#973 COM-1903 - fix address validation
  src/core/mixins/companyMixin.js
  src/modules/client/mixins/configMixin.js
  src/modules/client/pages/ni/config/CompanyConfig.vue
Labels: bug, dev

#975 COM-1909 - Fix Romain's review
  src/core/components/table/AttendanceTable.vue
Labels: dev

#974 COM-1911 - npm update
  package-lock.json
  package.json
Labels: dev

#977 COM-1895 - disable slot deletion if attendance exist
  src/core/components/courses/SlotContainer.vue
Labels: dev

#978 Update checklist in PR template
  .github/pull_request_template.md
Labels: dev

#980 COM-1920 handle when an auxiliary is in two sector for one week
  src/modules/client/components/planning/Planning.vue
Labels: dev

#982 COM-1878 - trim name in sector creation modal
  src/modules/client/components/config/SectorCreationModal.vue
  src/modules/client/components/config/SectorEditionModal.vue
Labels: dev

#979 Com 1844
  src/core/components/charts/LineChart.vue
  src/core/components/charts/VueChartLineChart.vue
  src/core/components/courses/ProfileFollowUp.vue
  src/core/mixins/traineeChartMixin.js
  src/modules/client/pages/ni/courses/Dashboard.vue
Labels: dev

#985 COM-1919 fix bug on companyconfig
  src/core/components/table/CoachList.vue
  src/core/data/user.js
  src/modules/client/mixins/configMixin.js
  src/modules/client/pages/ni/config/CoachConfig.vue
  src/modules/client/pages/ni/config/CompanyConfig.vue
  src/modules/client/pages/ni/config/CustomersConfig.vue
  src/modules/client/pages/ni/config/RhConfig.vue
Labels: dev

#981 Com 1852
  src/core/components/table/AttendanceTable.vue
  src/core/components/table/TraineeAttendanceCreationModal.vue
Labels: dev

#987 COM-1899: fix minor errors
  src/statics/cguCompani.html
Labels: dev

#986 COM-1879 - Fix bug
  src/modules/client/pages/ni/config/CustomersConfig.vue
Labels: dev

#988 COM-1899: add phone (optional)
  src/statics/cguCompani.html
Labels: dev

#991 Com 1881
  src/modules/client/components/config/ServiceCreationModal.vue
  src/modules/client/components/config/ServiceEditionModal.vue
  src/modules/client/components/config/SurchargeCreationModal.vue
  src/modules/client/components/config/SurchargeEditionModal.vue
  src/modules/client/components/customers/infos/ProfileInfo.vue
  src/modules/client/components/customers/infos/SubscriptionCreationModal.vue
  src/modules/client/components/customers/infos/SubscriptionEditionModal.vue
  src/modules/client/pages/ni/config/CustomersConfig.vue
Labels: dev

#989 COM-1885: add pagination
  src/core/components/table/Pagination.vue
  src/core/components/table/TableList.vue
  src/modules/client/pages/auxiliaries/customers/AuxiliaryCustomersDirectory.vue
  src/modules/client/pages/auxiliaries/teams/TeamsDirectory.vue
  src/modules/client/pages/ni/auxiliaries/Directory.vue
  src/modules/client/pages/ni/courses/LearnersDirectory.vue
  src/modules/client/pages/ni/customers/CustomersDirectory.vue
  src/modules/vendor/pages/ni/users/learners/LearnersDirectory.vue
Labels: dev
