Repository CompaniTech/compani-webapp, pull requests merged in 2021-04, with the labels that each got.

#1048 COM-1822: fix bug when two auxiliaries on dashboard
  src/modules/client/pages/ni/auxiliaries/Dashboard.vue
Labels: bug

#1045 COM-1974: i can create questionnaire
  src/core/api/Questionnaires.js
  src/core/components/courses/QuestionnaireCell.vue
  src/core/data/constants.js
  src/modules/vendor/components/programs/QuestionnaireCreationModal.vue
  src/modules/vendor/pages/ni/pedagogy/QuestionnairesDirectory.vue
Labels: dev

#1046 Com 1979
  src/core/components/courses/AttendanceSheetAdditionModal.vue
  src/core/components/courses/ProfileOrganization.vue
  src/core/components/table/AttendanceTable.vue
  src/core/helpers/utils.js
  src/modules/client/components/customers/ProfileFollowUp.vue
  src/modules/client/mixins/planningModalMixin.js
  src/modules/vendor/components/courses/CourseCreationModal.vue
  src/modules/vendor/pages/ni/management/BlendedCoursesDirectory.vue
Labels: dev

#1051 COM-1991 fix startDateError
  src/modules/client/pages/ni/pay/ContractMonitoring.vue
Labels: dev

#1049 COM-1974: can't create a questionnaire if already one in draft
  src/modules/vendor/pages/ni/pedagogy/QuestionnairesDirectory.vue
Labels: dev

#1050 Com 1977
  src/core/api/PartnerOrganizations.js
  src/core/helpers/rbac.js
  src/core/mixins/learnerMixin.js
  src/core/mixins/partnerOrganizationMixin.js
  src/modules/client/components/customers/PartnerOrganizationCreationModal.vue
  src/modules/client/mixins/menuItemsMixin.js
  src/modules/client/pages/ni/customers/CustomersDirectory.vue
  src/modules/client/pages/ni/customers/PartnerOrganizationsDirectory.vue
  src/modules/client/router/routes.js
Labels: dev

#1052 Com 1975
  src/core/api/Questionnaires.js
  src/core/components/ProfileHeader.vue
  src/core/components/courses/BlendedCourseProfileHeader.vue
  src/core/components/courses/QuestionnaireCell.vue
  src/core/helpers/rbac.js
  src/css/icon.styl
  src/modules/client/pages/ni/courses/LearnerProfile.vue
  src/modules/client/store/customer.js
  src/modules/vendor/components/programs/PublishedDot.vue
  src/modules/vendor/components/questionnaires/ProfileEdition.vue
  src/modules/vendor/pages/ni/pedagogy/ActivityProfile.vue
  src/modules/vendor/pages/ni/pedagogy/QuestionnaireProfile.vue
  src/modules/vendor/pages/ni/pedagogy/QuestionnairesDirectory.vue
  src/modules/vendor/pages/ni/users/companies/CompanyProfile.vue
  src/modules/vendor/pages/ni/users/learners/LearnerProfile.vue
  src/modules/vendor/router/routes.js
  src/modules/vendor/store/company.js
  src/modules/vendor/store/program.js
  src/modules/vendor/store/questionnaire.js
  src/store/course.js
  src/store/index.js
  src/store/userProfile.js
Labels: dev

#1055 COM-1980 - Fix for trainer
  src/core/components/courses/ProfileOrganization.vue
  src/core/mixins/courseMixin.js
  src/store/course.js
Labels: dev

#1058 COM-2010 - fix trainee addition on inter b2b course profile
  src/core/components/courses/ProfileOrganization.vue
  src/core/components/courses/TraineeTable.vue
Labels: bug, dev

#1056 COM-1988: refacto card container
  src/modules/vendor/components/programs/cards/CardContainer.vue
  src/modules/vendor/components/programs/cards/CardEdition.vue
  src/modules/vendor/components/programs/cards/templates/FillTheGaps.vue
  src/modules/vendor/components/programs/cards/templates/MultipleChoiceQuestion.vue
  src/modules/vendor/components/programs/cards/templates/OrderTheSequence.vue
  src/modules/vendor/components/programs/cards/templates/QuestionAnswer.vue
  src/modules/vendor/components/programs/cards/templates/SingleChoiceQuestion.vue
  src/modules/vendor/components/programs/cards/templates/TextMedia.vue
  src/modules/vendor/components/programs/cards/templates/TitleTextMedia.vue
  src/modules/vendor/mixins/templateMixin.js
  src/modules/vendor/pages/ni/pedagogy/ActivityProfile.vue
  src/modules/vendor/store/card.js
  src/modules/vendor/store/program.js
  src/store/index.js
Labels: dev

#1057 Com 1977 list
  src/core/api/PartnerOrganizations.js
  src/modules/client/pages/ni/customers/PartnerOrganizationsDirectory.vue
Labels: dev

#1060 COM-1974 - add ellispis on 2 lines
  src/core/components/courses/QuestionnaireCell.vue
Labels: dev

#1059 Com 1981
  src/core/helpers/utils.js
  src/core/mixins/courseFiltersMixin.js
  src/css/course.styl
  src/modules/client/pages/ni/courses/BlendedCoursesDirectory.vue
  src/modules/vendor/pages/ni/management/BlendedCoursesDirectory.vue
  src/modules/vendor/pages/trainers/management/BlendedCoursesDirectory.vue
  src/store/course.js
Labels: dev

#1061 COM-1988: edit questionnaire cards
  src/core/api/Activities.js
  src/core/api/Cards.js
  src/core/api/Questionnaires.js
  src/core/components/ProfileTabs.vue
  src/core/components/courses/QuestionnaireCell.vue
  src/core/mixins/cardMixin.js
  src/modules/vendor/components/programs/cards/CardEdition.vue
  src/modules/vendor/components/questionnaires/ProfileEdition.vue
  src/modules/vendor/mixins/templateMixin.js
  src/modules/vendor/pages/ni/pedagogy/ActivityProfile.vue
  src/modules/vendor/pages/ni/pedagogy/QuestionnaireProfile.vue
Labels: dev

#1062 Com 1978
  src/core/api/PartnerOrganizations.js
  src/core/helpers/rbac.js
  src/modules/client/pages/ni/customers/PartnerOrganizationProfile.vue
  src/modules/client/pages/ni/customers/PartnerOrganizationsDirectory.vue
  src/modules/client/router/routes.js
Labels: dev

#1065 COM-2028 - Fix design bug
  src/core/components/ProfileTabs.vue
  src/css/app.styl
Labels: dev

#1063 COM-1976: can publish questionnaire
  src/core/components/courses/QuestionnaireCell.vue
  src/core/components/learners/ProfileInfo.vue
  src/modules/vendor/components/questionnaires/ProfileEdition.vue
  src/modules/vendor/pages/ni/pedagogy/ActivityProfile.vue
  src/modules/vendor/pages/ni/pedagogy/QuestionnaireProfile.vue
Labels: dev

#1066 Com 1998
  .github/workflows/lint.yml
  package-lock.json
  package.json
  quasar.conf.js
Labels: dependances, dev

#1070 COM-2031 - Fix trainerFilterOptions
  src/core/mixins/courseFiltersMixin.js
Labels: dev

#1071 Com 2001
  src/core/data/constants.js
  src/modules/vendor/pages/ni/pedagogy/QuestionnairesDirectory.vue
Labels: dev

#1072 COM-1989: name and phone required on trainee edition modal
  src/core/components/courses/TraineeEditionModal.vue
  src/core/components/courses/TraineeTable.vue
Labels: dev

#1073 Com 2004
  src/core/api/PartnerOrganizations.js
  src/core/components/courses/TraineeTable.vue
  src/core/components/table/CoachList.vue
  src/core/data/constants.js
  src/modules/client/components/customers/PartnerCreationModal.vue
  src/modules/client/pages/ni/customers/PartnerOrganizationProfile.vue
Labels: dev

#1080 COM-2004: firstname is optional and the first field
  src/modules/client/components/customers/PartnerCreationModal.vue
  src/modules/client/pages/ni/customers/PartnerOrganizationProfile.vue
Labels: dev

#1081 COM-1990: disbale links when missing
  src/core/components/courses/ProfileTraineeFollowUp.vue
  src/modules/client/pages/ni/config/RhConfig.vue
Labels: dev

#1078 Com 1993
  src/core/api/Helpers.js
  src/modules/client/mixins/helperMixin.js
  src/modules/client/mixins/menuItemsMixin.js
Labels: dev

#1083 MEP
  .github/workflows/lint.yml
  package-lock.json
  package.json
  quasar.conf.js
  src/core/api/PartnerOrganizations.js
  src/core/components/courses/QuestionnaireCell.vue
  src/core/components/courses/TraineeEditionModal.vue
  src/core/components/courses/TraineeTable.vue
  src/core/components/learners/ProfileCourses.vue
  src/core/components/learners/ProfileInfo.vue
  src/core/components/table/CoachList.vue
  src/core/data/constants.js
  src/core/helpers/rbac.js
  src/core/mixins/chartMixin.js
  src/modules/client/components/customers/PartnerCreationModal.vue
  src/modules/client/pages/ni/customers/PartnerOrganizationProfile.vue
  src/modules/client/pages/ni/customers/PartnerOrganizationsDirectory.vue
  src/modules/client/pages/ni/pay/ToPay.vue
  src/modules/client/router/routes.js
  src/modules/vendor/components/programs/QuestionnaireCreationModal.vue
  src/modules/vendor/components/questionnaires/ProfileEdition.vue
  src/modules/vendor/mixins/templateMixin.js
  src/modules/vendor/pages/ni/pedagogy/ActivityProfile.vue
  src/modules/vendor/pages/ni/pedagogy/QuestionnaireProfile.vue
  src/modules/vendor/pages/ni/pedagogy/QuestionnairesDirectory.vue
Labels: master

#1084 COM-2052: npm update
  package-lock.json
  package.json
Labels: dependances

#1086 COM-2004: add director in job options
  src/core/data/constants.js
Labels: dev

#1085 Com 2035
  src/core/api/Courses.js
  src/core/components/courses/ProfileTraineeFollowUp.vue
  src/core/components/courses/QuestionnaireAnswersCell.vue
Labels: dev
