Repository CompaniTech/compani-webapp, pull requests merged in 2021-12, with the labels that each got.

#1378 COM-2518: allow link to company
  src/modules/vendor/components/companies/CompanyLinkModal.vue
  src/modules/vendor/pages/ni/users/learners/LearnerProfile.vue
Labels: dev

#1377 COM-2520: create user to add to course
  src/core/components/courses/LearnerCreationModal.vue
  src/core/components/courses/TraineeAdditionModal.vue
  src/core/components/courses/TraineeTable.vue
  src/core/components/form/Select.vue
  src/core/mixins/learnerCreationMixin.js
  src/core/mixins/learnerDirectoryMixin.js
  src/modules/client/pages/ni/courses/LearnersDirectory.vue
  src/modules/vendor/pages/ni/users/learners/LearnersDirectory.vue
Labels: dev

#1379 Com 2547
  src/core/data/user.js
  src/modules/client/components/auxiliary/ProfileInfo.vue
Labels: dev

#1385 COM-2461: stop multiple api call when edit or create slot with address
  src/core/components/courses/SlotContainer.vue
  src/core/components/courses/SlotCreationModal.vue
  src/core/components/courses/SlotEditionModal.vue
Labels: dev

#1387 COM-2442: don't show archived customer in delete event modal
  src/modules/client/mixins/planningModalMixin.js
Labels: dev

#1395 COM-2574: error in console on locked steps
  src/modules/vendor/components/programs/ProfileContent.vue
Labels: bug

#1397 COM-2462: block multiple api calls
  src/modules/client/components/auxiliary/AuxiliaryCreationModal.vue
Labels: dev

#1400 COM-2462: pass set in parent
  src/modules/client/components/auxiliary/AuxiliaryCreationModal.vue
  src/modules/client/pages/ni/auxiliaries/Directory.vue
Labels: dev

#1398 COM-2576 - Fix customer absence creation on stop date
  src/core/components/form/DateRange.vue
  src/modules/client/components/planning/DeleteEventsModal.vue
Labels: dev

#1404 MES 20/12
  src/core/api/CustomerAbsences.js
  src/core/components/courses/SlotContainer.vue
  src/core/components/form/DateRange.vue
  src/core/helpers/date.js
  src/modules/client/components/auxiliary/AuxiliaryCreationModal.vue
  src/modules/client/components/config/EstablishmentCreationModal.vue
  src/modules/client/components/config/EstablishmentEditionModal.vue
  src/modules/client/components/config/ThirdPartyPayerCreationModal.vue
  src/modules/client/components/config/ThirdPartyPayerEditionModal.vue
  src/modules/client/components/planning/CustomerAbsenceEditionModal.vue
  src/modules/client/components/planning/DeleteEventsModal.vue
  src/modules/client/components/planning/EventCreationModal.vue
  src/modules/client/components/planning/EventEditionModal.vue
  src/modules/client/pages/ni/auxiliaries/Directory.vue
  src/modules/client/pages/ni/config/CompanyConfig.vue
  src/modules/client/pages/ni/config/CustomersConfig.vue
  src/modules/client/pages/ni/planning/CustomerPlanning.vue
  src/modules/vendor/components/programs/ProfileContent.vue
Labels: staging

#1405 MEP 21/12
  package-lock.json
  package.json
  src/core/api/CustomerAbsences.js
  src/core/components/CompaniHeader.vue
  src/core/components/courses/ProfileAdmin.vue
  src/core/components/courses/SlotContainer.vue
  src/core/components/courses/SlotCreationModal.vue
  src/core/components/courses/SlotEditionModal.vue
  src/core/components/form/DateRange.vue
  src/core/components/form/DatetimeRange.vue
  src/core/helpers/date.js
  src/core/mixins/courseMixin.js
  src/core/pages/signin/Authenticate.vue
  src/modules/client/components/auxiliary/AuxiliaryCreationModal.vue
  src/modules/client/components/config/EstablishmentCreationModal.vue
  src/modules/client/components/config/EstablishmentEditionModal.vue
  src/modules/client/components/config/SurchargeCreationModal.vue
  src/modules/client/components/config/SurchargeEditionModal.vue
  src/modules/client/components/config/ThirdPartyPayerCreationModal.vue
  src/modules/client/components/config/ThirdPartyPayerEditionModal.vue
  src/modules/client/components/planning/CustomerAbsenceEditionModal.vue
  src/modules/client/components/planning/DeleteEventsModal.vue
  src/modules/client/components/planning/EventCreationModal.vue
  src/modules/client/components/planning/EventEditionModal.vue
  src/modules/client/components/planning/Planning.vue
  src/modules/client/mixins/planningActionMixin.js
  src/modules/client/mixins/planningModalMixin.js
  src/modules/client/pages/ni/auxiliaries/Directory.vue
  src/modules/client/pages/ni/config/CompanyConfig.vue
  src/modules/client/pages/ni/config/CustomersConfig.vue
  src/modules/client/pages/ni/planning/CustomerPlanning.vue
  src/modules/vendor/components/programs/ProfileContent.vue
  src/store/course.js
Labels: master
