Repository CompaniTech/compani-webapp, pull requests merged in 2021-05, with the labels that each got.

#1090 COM-2057 - Remove pentecote, pentecote's monday and mother's day from…
  src/core/helpers/moment.js
Labels: dev

#1087 COM-2036: display questionnaire answers
  src/core/api/Questionnaires.js
  src/core/components/courses/OpenQuestionChart.vue
  src/core/components/courses/ProfileTraineeFollowUp.vue
  src/core/helpers/rbac.js
  src/core/mixins/questionnaireAnswersMixin.js
  src/modules/vendor/components/courses/ProfileQuestionnaires.vue
  src/modules/vendor/pages/ni/management/QuestionnaireAnswersProfile.vue
  src/modules/vendor/router/routes.js
Labels: dev

#1088 Com 2040
  src/core/api/Helpers.js
  src/modules/client/components/customers/ProfileFollowUp.vue
  src/modules/client/components/customers/infos/ProfileInfo.vue
  src/modules/client/mixins/helperMixin.js
Labels: dev

#1089 Com 2041
  src/core/components/CompaniHeader.vue
  src/core/pages/DocumentSigned.vue
  src/modules/vendor/components/courses/ProfileQuestionnaires.vue
  src/modules/vendor/components/programs/ActivityEditionModal.vue
  src/modules/vendor/components/programs/ProfileContent.vue
  src/modules/vendor/components/programs/PublishedDot.vue
Labels: dev

#1092 COM-2039: minor bug
  src/modules/vendor/pages/ni/management/QuestionnaireAnswersProfile.vue
Labels: dev

#1091 COM-1994: update title auxiliary and customer profile
  src/css/app.styl
  src/modules/client/components/auxiliary/AuxiliaryProfileHeader.vue
  src/modules/client/components/customers/CustomerProfileHeader.vue
  src/modules/client/pages/ni/auxiliaries/AuxiliaryProfile.vue
  src/modules/client/pages/ni/customers/CustomerProfile.vue
Labels: dev

#1095 COM-2076: npm update
  package-lock.json
  package.json
Labels: dependances

#1096 COM-2069: add prescriber
  src/core/api/CustomerPartners.js
  src/modules/client/components/customers/ProfileFollowUp.vue
  src/modules/client/components/customers/infos/ProfileInfo.vue
  src/modules/client/mixins/helperMixin.js
Labels: dev

#1097 COM-2065: remove client/prospect notion
  src/core/components/DirectoryHeader.vue
  src/modules/client/components/customers/CustomerProfileHeader.vue
  src/modules/client/pages/ni/customers/CustomersDirectory.vue
  src/modules/vendor/pages/ni/management/BlendedCourseProfile.vue
Labels: dev

#1098 COM-2070: remove customer partner
  src/core/api/CustomerPartners.js
  src/modules/client/components/customers/ProfileFollowUp.vue
  src/modules/client/mixins/helperMixin.js
Labels: dev

#1100 COM-2065-2 : undo change on directoryheader
  src/core/components/DirectoryHeader.vue
Labels: dev

#1101 COM-2072: send email only to new trainee
  src/core/components/courses/TraineeTable.vue
Labels: dev

#1104 Com 2068
  src/core/api/Partners.js
  src/core/components/table/CoachList.vue
  src/css/table.styl
  src/modules/client/components/customers/PartnerEditionModal.vue
  src/modules/client/components/customers/ProfileFollowUp.vue
  src/modules/client/pages/ni/customers/PartnerOrganizationProfile.vue
Labels: dev

#1105 mes-2405
  package-lock.json
  package.json
  src/core/api/CustomerPartners.js
  src/core/api/Partners.js
  src/core/components/DirectoryHeader.vue
  src/core/components/courses/TraineeTable.vue
  src/core/components/table/CoachList.vue
  src/core/data/constants.js
  src/core/helpers/date.js
  src/core/mixins/learnerDirectoryMixin.js
  src/css/icon.styl
  src/css/table.styl
  src/modules/client/components/auxiliary/AuxiliaryProfileHeader.vue
  src/modules/client/components/customers/CustomerProfileHeader.vue
  src/modules/client/components/customers/PartnerEditionModal.vue
  src/modules/client/components/customers/ProfileFollowUp.vue
  src/modules/client/components/customers/infos/ProfileInfo.vue
  src/modules/client/mixins/helperMixin.js
  src/modules/client/pages/ni/auxiliaries/Directory.vue
  src/modules/client/pages/ni/customers/CustomersDirectory.vue
  src/modules/client/pages/ni/customers/PartnerOrganizationProfile.vue
  src/modules/vendor/pages/ni/management/BlendedCourseProfile.vue
Labels: staging

#1106 dont show timestamp in event histories feed
  src/modules/client/components/planning/EventHistoryFeed.vue
Labels: dev

#1107 MEP
  package-lock.json
  package.json
  src/core/api/CustomerPartners.js
  src/core/api/Partners.js
  src/core/components/DirectoryHeader.vue
  src/core/components/courses/TraineeTable.vue
  src/core/components/table/CoachList.vue
  src/core/data/constants.js
  src/core/helpers/date.js
  src/core/mixins/learnerDirectoryMixin.js
  src/css/icon.styl
  src/css/table.styl
  src/modules/client/components/auxiliary/AuxiliaryProfileHeader.vue
  src/modules/client/components/customers/CustomerProfileHeader.vue
  src/modules/client/components/customers/PartnerEditionModal.vue
  src/modules/client/components/customers/ProfileFollowUp.vue
  src/modules/client/components/customers/infos/ProfileInfo.vue
  src/modules/client/mixins/helperMixin.js
  src/modules/client/pages/ni/auxiliaries/Directory.vue
  src/modules/client/pages/ni/customers/CustomersDirectory.vue
  src/modules/client/pages/ni/customers/PartnerOrganizationProfile.vue
  src/modules/vendor/pages/ni/management/BlendedCourseProfile.vue
Labels: master

#1108 COM-2106 - npm update
  package-lock.json
  package.json
Labels: dependances, dev

#1114 fix download on inter b2b courses for coach
  src/core/components/courses/ProfileAdmin.vue
  src/core/components/courses/ProfileOrganization.vue
  src/core/mixins/courseMixin.js
Labels: bug

#1115 MEP intermediaire 27/05 (puppeteer)
  src/core/api/Courses.js
  src/core/components/courses/CourseInfoLink.vue
  src/core/components/courses/ProfileAdmin.vue
  src/core/components/courses/ProfileOrganization.vue
  src/core/mixins/courseMixin.js
  src/modules/client/components/customers/billing/CustomerBillingTable.vue
  src/modules/client/components/customers/billing/ProfileBilling.vue
Labels: master

#1111 Com 2093
  src/core/data/constants.js
  src/core/helpers/date.js
  src/modules/client/components/auxiliary/AuxiliaryProfileHeader.vue
  src/modules/client/components/customers/CustomerProfileHeader.vue
  src/modules/client/components/customers/infos/StopSupportModal.vue
  src/modules/client/mixins/customerMixin.js
  src/modules/client/pages/ni/customers/CustomersDirectory.vue
Labels: dev

#1116 COM-2098 - refacto coach email
  src/core/components/table/CoachList.vue
Labels: dev
