Repository CompaniTech/compani-webapp, pull requests merged in 2021-07, with the labels that each got.

#1162 fix favicon error in console
  src/index.template.html
Labels: bug, dev

#1164 COM-2217 - fix display on safari
  src/modules/client/components/planning/ChipCustomerIndicator.vue
Labels: bug, dev

#1163 COM-2174: add qrcode button to helper
  src/core/components/form/MultipleFilesUploader.vue
  src/modules/client/components/auxiliary/ProfileInfo.vue
  src/modules/client/components/customers/ProfileFollowUp.vue
  src/modules/client/components/customers/infos/ProfileInfo.vue
  src/modules/client/mixins/customerMixin.js
  src/modules/client/pages/customers/Subscriptions.vue
Labels: dev

#1165 Com 2177
  src/core/components/form/Input.vue
  src/core/components/modal/Modal.vue
  src/css/modal.styl
  src/modules/client/components/customers/ProfileFollowUp.vue
  src/modules/client/components/customers/infos/CustomerNoteEditionModal.vue
  src/modules/client/components/planning/ChipAuxiliaryIndicator.vue
Labels: dev

#1166 Dev
  package-lock.json
  src/core/api/CustomerNotes.js
  src/core/api/Customers.js
  src/core/components/courses/ProfileAdmin.vue
  src/core/components/form/DateInput.vue
  src/core/components/form/DateRange.vue
  src/core/components/form/DatetimeRange.vue
  src/core/components/form/FileUploader.vue
  src/core/components/form/Input.vue
  src/core/components/form/MultipleFilesUploader.vue
  src/core/components/form/OptionGroup.vue
  src/core/components/form/SearchAddress.vue
  src/core/components/form/Select.vue
  src/core/components/form/TimeInput.vue
  src/core/components/modal/Modal.vue
  src/css/input.styl
  src/css/modal.styl
  src/index.template.html
  src/modules/client/components/auxiliary/ProfileInfo.vue
  src/modules/client/components/customers/ProfileFollowUp.vue
  src/modules/client/components/customers/infos/CustomerNoteCreationModal.vue
  src/modules/client/components/customers/infos/CustomerNoteEditionModal.vue
  src/modules/client/components/customers/infos/FundingDetailsModal.vue
  src/modules/client/components/customers/infos/ProfileInfo.vue
  src/modules/client/components/planning/ChipAuxiliaryIndicator.vue
  src/modules/client/components/planning/ChipCustomerIndicator.vue
  src/modules/client/components/table/CustomerNoteCell.vue
  src/modules/client/components/table/CustomerNotesContainer.vue
  src/modules/client/mixins/customerMixin.js
  src/modules/client/mixins/fundingMixin.js
  src/modules/client/pages/customers/Subscriptions.vue
Labels: staging

#1168 MEP
  package-lock.json
  src/core/api/CustomerNotes.js
  src/core/api/Customers.js
  src/core/components/courses/ProfileAdmin.vue
  src/core/components/form/DateInput.vue
  src/core/components/form/DateRange.vue
  src/core/components/form/DatetimeRange.vue
  src/core/components/form/FileUploader.vue
  src/core/components/form/Input.vue
  src/core/components/form/MultipleFilesUploader.vue
  src/core/components/form/OptionGroup.vue
  src/core/components/form/SearchAddress.vue
  src/core/components/form/Select.vue
  src/core/components/form/TimeInput.vue
  src/core/components/modal/Modal.vue
  src/css/input.styl
  src/css/modal.styl
  src/index.template.html
  src/modules/client/components/auxiliary/ProfileInfo.vue
  src/modules/client/components/customers/ProfileFollowUp.vue
  src/modules/client/components/customers/infos/CustomerNoteCreationModal.vue
  src/modules/client/components/customers/infos/CustomerNoteEditionModal.vue
  src/modules/client/components/customers/infos/FundingDetailsModal.vue
  src/modules/client/components/customers/infos/ProfileInfo.vue
  src/modules/client/components/planning/ChipAuxiliaryIndicator.vue
  src/modules/client/components/planning/ChipCustomerIndicator.vue
  src/modules/client/components/table/CustomerNoteCell.vue
  src/modules/client/components/table/CustomerNotesContainer.vue
  src/modules/client/mixins/customerMixin.js
  src/modules/client/mixins/fundingMixin.js
  src/modules/client/pages/customers/Subscriptions.vue
Labels: master

#1169 COM-2214 - npm update
  package-lock.json
  package.json
Labels: dependances

#1174 COM-2210 create a file-uploader to upload general terms of services
  src/modules/client/pages/ni/config/CustomersConfig.vue
Labels: dev

#1173 Com 2071
  src/core/components/learners/ProfileCourses.vue
  src/core/components/table/ExpandingTable.vue
  src/modules/client/pages/ni/customers/PartnerOrganizationProfile.vue
Labels: dev

#1170 COM-2206: lashistory on cell
  src/core/components/form/Input.vue
  src/core/data/constants.js
  src/modules/client/components/customers/infos/CustomerNoteEditionModal.vue
  src/modules/client/components/customers/infos/CustomerNoteHistory.vue
  src/modules/client/components/customers/infos/CustomerNoteHistoryContainer.vue
  src/modules/client/components/table/CustomerNoteCell.vue
Labels: dev

#1175 COM-2120 disable questionnaire answer in client interface
  src/core/components/courses/ProfileTraineeFollowUp.vue
Labels: dev

#1177 COM-2206: change message color
  src/modules/client/components/customers/infos/CustomerNoteEditionModal.vue
  src/modules/client/components/table/CustomerNoteCell.vue
Labels: dev

#1179 COM-2211 - Fix gcs use and add dynamic name
  src/core/data/constants.js
  src/modules/client/pages/customers/Subscriptions.vue
  src/modules/client/pages/ni/config/CustomersConfig.vue
Labels: dev

#1180 COM-2211 - Fix bug
  src/modules/client/pages/customers/Subscriptions.vue
Labels: bug

#1183 Com 2222
  src/modules/client/components/planning/EventEditionModal.vue
  src/modules/client/pages/ni/pay/Absences.vue
Labels: dev

#1185 COM-2189 - handle qr code time stamping in event history
  src/core/data/constants.js
  src/modules/client/components/planning/EventHistory.vue
Labels: dev

#1186 COM-2167: remove green popup when fail on email change
  src/core/components/learners/ProfileInfo.vue
  src/core/pages/AccountInfo.vue
  src/modules/client/components/auxiliary/ProfileInfo.vue
  src/modules/vendor/components/trainers/ProfileInfo.vue
Labels: dev

#1187 MES 22/07
  package-lock.json
  package.json
  src/core/components/courses/ProfileTraineeFollowUp.vue
  src/core/components/form/Input.vue
  src/core/components/learners/ProfileCourses.vue
  src/core/components/learners/ProfileInfo.vue
  src/core/components/table/ExpandingTable.vue
  src/core/data/constants.js
  src/core/pages/AccountInfo.vue
  src/modules/client/components/auxiliary/ProfileInfo.vue
  src/modules/client/components/customers/infos/CustomerNoteEditionModal.vue
  src/modules/client/components/customers/infos/CustomerNoteHistory.vue
  src/modules/client/components/customers/infos/CustomerNoteHistoryContainer.vue
  src/modules/client/components/planning/EventEditionModal.vue
  src/modules/client/components/planning/EventHistory.vue
  src/modules/client/components/table/CustomerNoteCell.vue
  src/modules/client/pages/customers/Subscriptions.vue
  src/modules/client/pages/ni/config/CustomersConfig.vue
  src/modules/client/pages/ni/customers/PartnerOrganizationProfile.vue
  src/modules/client/pages/ni/customers/PartnerOrganizationsDirectory.vue
  src/modules/client/pages/ni/pay/Absences.vue
  src/modules/vendor/components/questionnaires/ProfileAnswers.vue
  src/modules/vendor/components/questionnaires/ProfileEdition.vue
  src/modules/vendor/components/trainers/ProfileInfo.vue
  src/modules/vendor/pages/ni/pedagogy/QuestionnaireProfile.vue
Labels: staging

#1188 COM-2229: no third state when sort column
  src/core/components/table/ExpandingTable.vue
Labels: dev

#1190 COM-2232: doesn't access to useful actions if phone number incorrect
  src/core/mixins/courseMixin.js
Labels: dev

#1195 MEP 28/07
  package-lock.json
  package.json
  src/core/components/courses/ProfileTraineeFollowUp.vue
  src/core/components/form/Input.vue
  src/core/components/learners/ProfileCourses.vue
  src/core/components/learners/ProfileInfo.vue
  src/core/components/table/ExpandingTable.vue
  src/core/data/constants.js
  src/core/pages/AccountInfo.vue
  src/modules/client/components/auxiliary/ProfileInfo.vue
  src/modules/client/components/customers/infos/CustomerNoteEditionModal.vue
  src/modules/client/components/customers/infos/CustomerNoteHistory.vue
  src/modules/client/components/customers/infos/CustomerNoteHistoryContainer.vue
  src/modules/client/components/planning/EventEditionModal.vue
  src/modules/client/components/planning/EventHistory.vue
  src/modules/client/components/table/CustomerNoteCell.vue
  src/modules/client/pages/customers/Subscriptions.vue
  src/modules/client/pages/ni/config/CustomersConfig.vue
  src/modules/client/pages/ni/customers/PartnerOrganizationProfile.vue
  src/modules/client/pages/ni/customers/PartnerOrganizationsDirectory.vue
  src/modules/client/pages/ni/pay/Absences.vue
  src/modules/vendor/components/questionnaires/ProfileAnswers.vue
  src/modules/vendor/components/questionnaires/ProfileEdition.vue
  src/modules/vendor/components/trainers/ProfileInfo.vue
  src/modules/vendor/pages/ni/pedagogy/QuestionnaireProfile.vue
Labels: master

#1192 COM-2089: change clear button in close button
  src/core/components/PictureUploader.vue
  src/core/components/courses/CourseHistoryFeed.vue
  src/core/components/modal/HtmlModal.vue
  src/core/components/modal/Modal.vue
  src/modules/client/components/contracts/ContractEndingModal.vue
  src/modules/client/components/contracts/ContractsCell.vue
  src/modules/client/components/planning/ChipAuxiliaryIndicator.vue
  src/modules/client/components/planning/DeleteEventsModal.vue
  src/modules/client/components/planning/EventHistoryFeed.vue
  src/modules/client/components/planning/PlanningModalHeader.vue
  src/modules/client/pages/customers/Subscriptions.vue
Labels: dev

#1189 COM-2235 fixed name of unregistered trainee
  src/core/components/courses/ProfileTraineeFollowUp.vue
  src/core/components/table/AttendanceTable.vue
Labels: dev

#1196 COM-2203: return 404 for forbidden user
  src/modules/client/pages/ni/courses/LearnerProfile.vue
  src/store/userProfile.js
Labels: dev

#1198 COM-2227: add border on file upload
  src/core/components/form/Input.vue
  src/css/input.styl
Labels: dev

#1197 COM-2230: block request if user from other company
  src/core/components/courses/TraineeTable.vue
  src/modules/client/mixins/helperMixin.js
  src/modules/client/pages/ni/courses/LearnersDirectory.vue
Labels: dev

#1200 Com 2109
  src/core/components/PictureUploader.vue
  src/core/components/courses/SlotEditionModal.vue
  src/core/components/courses/TraineeTable.vue
  src/core/mixins/cardMixin.js
  src/modules/client/components/auxiliary/AuxiliaryProfileHeader.vue
  src/modules/client/components/auxiliary/ProfileContracts.vue
  src/modules/client/components/auxiliary/ProfileInfo.vue
  src/modules/client/components/auxiliary/ProfilePay.vue
  src/modules/client/components/customers/billing/ProfileBilling.vue
  src/modules/client/components/customers/infos/ProfileInfo.vue
  src/modules/client/components/planning/DeleteEventsModal.vue
  src/modules/client/mixins/configMixin.js
  src/modules/client/mixins/financialCertificatesMixin.js
  src/modules/client/mixins/helperMixin.js
  src/modules/client/mixins/planningActionMixin.js
  src/modules/client/pages/ni/auxiliaries/Directory.vue
  src/modules/client/pages/ni/billing/CreditNotes.vue
  src/modules/client/pages/ni/config/CompanyConfig.vue
  src/modules/client/pages/ni/config/CustomersConfig.vue
  src/modules/client/pages/ni/config/RhConfig.vue
  src/modules/vendor/components/courses/ProfileAccess.vue
  src/modules/vendor/components/programs/ProfileContent.vue
  src/modules/vendor/components/programs/ProfileInfo.vue
  src/modules/vendor/components/programs/SubProgramPublicationModal.vue
  src/modules/vendor/components/programs/TesterTable.vue
  src/modules/vendor/components/questionnaires/ProfileEdition.vue
  src/modules/vendor/mixins/templateMixin.js
  src/modules/vendor/pages/ni/pedagogy/ActivityProfile.vue
  src/modules/vendor/pages/ni/pedagogy/CategoriesDirectory.vue
Labels: dev
