Repository CompaniTech/compani-webapp, pull requests merged in 2021-06, with the labels that each got.

#1117 COM-2090
  src/core/components/form/DatetimeRange.vue
  src/modules/client/components/planning/EventEditionModal.vue
  src/modules/client/components/planning/PlanningModalHeader.vue
  src/modules/client/mixins/planningActionMixin.js
Labels: dev

#1118 COM-2095: block creation and edition after stopping date
  src/core/components/form/DatetimeRange.vue
  src/core/helpers/date.js
  src/core/mixins/learnerDirectoryMixin.js
  src/modules/client/components/planning/DeleteEventsModal.vue
  src/modules/client/components/planning/EventCreationModal.vue
  src/modules/client/components/planning/EventEditionModal.vue
  src/modules/client/mixins/planningActionMixin.js
  src/modules/client/mixins/planningModalMixin.js
  src/modules/client/pages/ni/planning/CustomerPlanning.vue
Labels: dev

#1119 COM-2091: can't update a timestamped end date
  src/modules/client/components/planning/EventEditionModal.vue
  src/modules/client/mixins/planningActionMixin.js
Labels: dev

#1120 hide-stop-button: hide button
  src/modules/client/components/customers/CustomerProfileHeader.vue
Labels: dev

#1125 dont send company if user already have one on coachlist
  src/core/components/table/CoachList.vue
Labels: dev

#1126 MES
  src/core/components/table/CoachList.vue
Labels: staging

#1127 Com 2075 fix
  src/modules/client/components/planning/EventEditionModal.vue
  src/modules/client/components/planning/Planning.vue
  src/modules/client/mixins/planningActionMixin.js
  src/modules/client/pages/ni/planning/AuxiliaryPlanning.vue
  src/modules/client/pages/ni/planning/CustomerPlanning.vue
Labels: dev

#1130 COM-2094: change constant
  src/core/data/constants.js
Labels: dev

#1129 MEP intermediaire
  src/modules/client/components/planning/EventEditionModal.vue
  src/modules/client/components/planning/Planning.vue
  src/modules/client/mixins/planningActionMixin.js
  src/modules/client/pages/ni/planning/AuxiliaryPlanning.vue
  src/modules/client/pages/ni/planning/CustomerPlanning.vue
Labels: master

#1132 COM-2139: add loader
  src/modules/client/components/planning/DeleteEventsModal.vue
  src/modules/client/components/planning/Planning.vue
Labels: dev

#1131 Com 2142
  src/modules/client/components/config/ThirdPartyPayerCreationModal.vue
  src/modules/client/components/config/ThirdPartyPayerEditionModal.vue
  src/modules/client/pages/ni/config/CustomersConfig.vue
Labels: dev

#1134 COM-2138
  src/modules/client/components/planning/DeleteEventsModal.vue
  src/modules/client/mixins/planningActionMixin.js
Labels: dev

#1133 Com 2075 histories
  src/modules/client/components/planning/EventEditionModal.vue
  src/modules/client/mixins/planningActionMixin.js
  src/modules/client/pages/ni/pay/Absences.vue
Labels: dev

#1140 COM-2075 disable fields on history loading
  src/modules/client/components/planning/EventEditionModal.vue
  src/modules/client/mixins/planningActionMixin.js
  src/modules/client/pages/auxiliaries/planning/AuxiliaryAgenda.vue
  src/modules/client/pages/ni/pay/Absences.vue
  src/modules/client/pages/ni/planning/AuxiliaryPlanning.vue
  src/modules/client/pages/ni/planning/CustomerPlanning.vue
Labels: dev

#1138 COM-2094 - Show button
  src/modules/client/components/customers/CustomerProfileHeader.vue
Labels: dev

#1137 COM-2143: add teletransmission field to funding modals
  src/modules/client/components/customers/infos/FundingCreationModal.vue
  src/modules/client/components/customers/infos/FundingEditionModal.vue
  src/modules/client/components/customers/infos/ProfileInfo.vue
Labels: dev

#1139 COM-2186: fix bugs
  src/modules/client/components/customers/infos/ProfileInfo.vue
Labels: dev

#1147 COM-2192 fix creditNote button
  src/modules/client/pages/ni/billing/CreditNotes.vue
Labels: dev

#1148 COM-2143: add fundingplanId to details modal
  src/modules/client/components/customers/infos/FundingDetailsModal.vue
  src/modules/client/mixins/fundingMixin.js
Labels: dev

#1146 MEP
  package-lock.json
  src/core/data/constants.js
  src/modules/client/components/auxiliary/ProfileContracts.vue
  src/modules/client/components/config/ThirdPartyPayerCreationModal.vue
  src/modules/client/components/config/ThirdPartyPayerEditionModal.vue
  src/modules/client/components/customers/CustomerProfileHeader.vue
  src/modules/client/components/customers/infos/FundingCreationModal.vue
  src/modules/client/components/customers/infos/FundingEditionModal.vue
  src/modules/client/components/customers/infos/ProfileInfo.vue
  src/modules/client/components/planning/DeleteEventsModal.vue
  src/modules/client/components/planning/EventEditionModal.vue
  src/modules/client/components/planning/Planning.vue
  src/modules/client/mixins/planningActionMixin.js
  src/modules/client/pages/auxiliaries/planning/AuxiliaryAgenda.vue
  src/modules/client/pages/ni/config/CustomersConfig.vue
  src/modules/client/pages/ni/pay/Absences.vue
  src/modules/client/pages/ni/planning/AuxiliaryPlanning.vue
  src/modules/client/pages/ni/planning/CustomerPlanning.vue
Labels: master

#1149 COM-2192 - update fonts
  src/core/components/CourseProgress.vue
  src/core/components/DirectoryHeader.vue
  src/core/components/ProfileHeader.vue
  src/core/components/TitleHeader.vue
  src/core/components/courses/BlendedCourseProfileHeader.vue
  src/core/components/courses/ELearningIndicator.vue
  src/core/components/form/Select.vue
  src/core/components/modal/HtmlModal.vue
  src/core/components/modal/Modal.vue
  src/core/pages/AccountInfo.vue
  src/css/app.styl
  src/css/fonts/AvenirLTStd-Light.woff
  src/css/header.styl
  src/css/input.styl
  src/css/modal.styl
  src/modules/client/components/auxiliary/AuxiliaryProfileHeader.vue
  src/modules/client/components/customers/CustomerProfileHeader.vue
  src/modules/client/components/planning/EventCreationModal.vue
  src/modules/client/components/planning/EventEditionModal.vue
  src/modules/client/pages/auxiliaries/administrative/Contracts.vue
  src/modules/client/pages/auxiliaries/administrative/Documents.vue
  src/modules/client/pages/auxiliaries/administrative/Info.vue
  src/modules/client/pages/auxiliaries/administrative/Salaries.vue
  src/modules/client/pages/auxiliaries/customers/CustomerInfo.vue
  src/modules/client/pages/customers/Billing.vue
  src/modules/client/pages/customers/Contact.vue
  src/modules/client/pages/customers/Subscriptions.vue
  src/modules/client/pages/ni/auxiliaries/StaffRegister.vue
  src/modules/client/pages/ni/billing/ClientsBalances.vue
  src/modules/client/pages/ni/billing/CreditNotes.vue
  src/modules/client/pages/ni/billing/DebitsArchive.vue
  src/modules/client/pages/ni/billing/ToBill.vue
  src/modules/client/pages/ni/config/CoachConfig.vue
  src/modules/client/pages/ni/config/CompanyConfig.vue
  src/modules/client/pages/ni/config/CustomersConfig.vue
  src/modules/client/pages/ni/config/RhConfig.vue
  src/modules/client/pages/ni/courses/Dashboard.vue
  src/modules/client/pages/ni/customers/CustomersFundingsMonitoring.vue
  src/modules/client/pages/ni/exports/DataExports.vue
  src/modules/client/pages/ni/exports/HistoryExports.vue
  src/modules/client/pages/ni/pay/ContractEnds.vue
  src/modules/client/pages/ni/pay/ToPay.vue
  src/modules/vendor/pages/ni/management/QuestionnaireAnswersProfile.vue
  src/modules/vendor/pages/trainers/administrative/Info.vue
Labels: dev

#1152 Com 2175
  src/core/api/CustomerNotes.js
  src/modules/client/components/customers/ProfileFollowUp.vue
  src/modules/client/components/customers/infos/CustomerNoteCreationModal.vue
  src/modules/client/components/table/CustomerNoteCell.vue
  src/modules/client/components/table/CustomerNotesContainer.vue
Labels: dev

#1154 Com 2192 menu
  quasar.conf.js
  src/core/components/BiColorButton.vue
  src/core/components/CopyButton.vue
  src/core/components/courses/CourseCell.vue
  src/core/components/courses/QuestionAnswerChart.vue
  src/core/components/courses/SlotContainer.vue
  src/core/components/courses/SurveyChart.vue
  src/core/components/form/DateInput.vue
  src/core/components/form/DateRange.vue
  src/core/components/form/DatetimeRange.vue
  src/core/components/form/FileUploader.vue
  src/core/components/form/Input.vue
  src/core/components/form/MultipleFilesUploader.vue
  src/core/components/form/OptionGroup.vue
  src/core/components/form/SearchAddress.vue
  src/core/components/form/Select.vue
  src/core/components/form/SelectSector.vue
  src/core/components/form/TimeInput.vue
  src/core/components/learners/ProfileInfo.vue
  src/core/components/menu/MenuItem.vue
  src/core/components/table/EditableTd.vue
  src/core/components/table/PrefixedCellContent.vue
  src/core/pages/AccountInfo.vue
  src/css/app.styl
  src/css/chip.styl
  src/css/drawer.styl
  src/css/modal.styl
  src/css/planning.styl
  src/modules/client/components/auxiliary/AuxiliaryCreationModal.vue
  src/modules/client/components/auxiliary/ProfileInfo.vue
  src/modules/client/components/contracts/ContractsCell.vue
  src/modules/client/components/planning/ChipAuxiliaryIndicator.vue
  src/modules/client/components/planning/ChipCustomerIndicator.vue
  src/modules/client/components/planning/EventCreationModal.vue
  src/modules/client/components/planning/EventEditionModal.vue
  src/modules/client/components/planning/Planning.vue
  src/modules/client/layouts/Layout.vue
  src/modules/client/pages/ni/auxiliaries/Dashboard.vue
  src/modules/client/pages/ni/courses/Dashboard.vue
  src/modules/client/pages/ni/customers/CustomersFundingsMonitoring.vue
  src/modules/vendor/components/programs/ProfileContent.vue
  src/modules/vendor/components/questionnaires/ProfileEdition.vue
  src/modules/vendor/components/trainers/ProfileInfo.vue
  src/modules/vendor/layouts/Layout.vue
Labels: dev

#1155 COM-2192 - fix menu on helper side
  src/css/drawer.styl
Labels: bug, dev

#1161 COM-2176: edition modal
  src/core/api/CustomerNotes.js
  src/core/components/form/Input.vue
  src/core/components/modal/Modal.vue
  src/modules/client/components/customers/ProfileFollowUp.vue
  src/modules/client/components/customers/infos/CustomerNoteEditionModal.vue
  src/modules/client/components/table/CustomerNoteCell.vue
  src/modules/client/components/table/CustomerNotesContainer.vue
Labels: dev

#1160 Com 2173
  src/core/api/Customers.js
  src/core/components/form/DateInput.vue
  src/core/components/form/DateRange.vue
  src/core/components/form/DatetimeRange.vue
  src/core/components/form/FileUploader.vue
  src/core/components/form/Input.vue
  src/core/components/form/MultipleFilesUploader.vue
  src/core/components/form/OptionGroup.vue
  src/core/components/form/SearchAddress.vue
  src/core/components/form/Select.vue
  src/core/components/form/TimeInput.vue
  src/css/input.styl
  src/modules/client/components/customers/ProfileFollowUp.vue
Labels: dev
