Repository CompaniTech/compani-webapp, pull requests merged in 2022-03, with the labels that each got.

#1476 COM-2710 - Add saturday to subscription history and data export
  src/modules/client/mixins/subscriptionMixin.js
  src/modules/client/pages/customers/Subscriptions.vue
Labels: dev

#1478 Com 2704
  src/core/api/CourseBillingItems.js
  src/core/api/CourseBills.js
  src/core/components/courses/CourseBilling.vue
  src/modules/vendor/components/billing/CourseBillCreationModal.vue
  src/modules/vendor/components/billing/CourseFeeAdditionModal.vue
  src/modules/vendor/components/billing/CourseFeeEditionModal.vue
  src/modules/vendor/components/billing/FunderEditionModal.vue
Labels: dev

#1480 COM-2695: add confirmation modal
  src/modules/client/pages/ni/planning/CustomerPlanning.vue
Labels: dev

#1479 COM-2690 - Visual refacto for helpers subscriptions
  src/modules/client/components/customers/SubscriptionCell.vue
  src/modules/client/components/customers/infos/ProfileInfo.vue
  src/modules/client/mixins/subscriptionMixin.js
  src/modules/client/pages/customers/Subscriptions.vue
Labels: dev

#1481 COM-2704: add chevron
  src/core/components/courses/CourseBilling.vue
Labels: dev

#1484 COM-2730: validate bill
  src/core/components/courses/CourseBilling.vue
  src/modules/vendor/components/billing/CourseBillValidationModal.vue
Labels: dev

#1488 COM-2738: refacto to change item in purchase
  src/core/api/CourseBills.js
  src/core/components/courses/CourseBilling.vue
  src/modules/vendor/components/billing/BillingPurchaseAdditionModal.vue
Labels: dev

#1486 Com 2729
  src/core/data/constants.js
  src/modules/client/components/config/ThirdPartyPayerDetailsModal.vue
  src/modules/client/components/config/ThirdPartyPayerEditionModal.vue
  src/modules/client/pages/ni/config/CustomersConfig.vue
Labels: dev

#1487 COM-2734 - Add misc to credit note pdf
  src/modules/client/components/customers/billing/CreditNoteCreationModal.vue
  src/modules/client/components/customers/billing/CustomerBillingTable.vue
Labels: dev

#1492 COM-2740 - mini fix for exports
  src/modules/client/pages/ni/exports/HistoryExports.vue
Labels: dev

#1490 COM-2732: add download button
  src/core/api/CourseBills.js
  src/core/components/courses/CourseBilling.vue
Labels: dev

#1491 COM-2718: change theoretical hours in modal
  src/core/components/learners/ProfileCourses.vue
  src/core/helpers/date.js
  src/modules/vendor/components/programs/ProfileContent.vue
  src/modules/vendor/components/programs/StepEditionModal.vue
Labels: dev

#1497 COM-2718: required if other field not defined + boyscout format
  src/core/helpers/date.js
  src/modules/vendor/components/programs/ProfileContent.vue
Labels: dev

#1496 COM-2690 - Fix Romain's review
  src/css/app.sass
  src/modules/client/components/customers/SubscriptionCell.vue
Labels: dev

#1499 COM-2743 - add loading
  src/modules/client/pages/ni/billing/ToBill.vue
Labels: bug, dev

#1500 Com 2733
  src/modules/client/components/planning/EventCreationModal.vue
  src/modules/client/components/planning/EventEditionModal.vue
  src/modules/client/mixins/planningActionMixin.js
  src/modules/client/mixins/planningModalMixin.js
Labels: dev

#1503 COM-2734 - Fix Corentin's reviews
  src/modules/client/components/customers/billing/CreditNoteCreationModal.vue
Labels: dev

#1504 COM-2729 - Fix Ulysse's reviews
  src/modules/client/components/config/ThirdPartyPayerEditionModal.vue
Labels: dev

#1507 MES-21-03
  src/core/api/CourseBills.js
  src/core/components/courses/CourseBilling.vue
  src/core/components/learners/ProfileCourses.vue
  src/core/data/constants.js
  src/core/helpers/date.js
  src/core/mixins/eLearningCourseDirectoryMixin.js
  src/css/app.sass
  src/modules/client/components/config/ThirdPartyPayerDetailsModal.vue
  src/modules/client/components/config/ThirdPartyPayerEditionModal.vue
  src/modules/client/components/customers/SubscriptionCell.vue
  src/modules/client/components/customers/billing/CreditNoteCreationModal.vue
  src/modules/client/components/customers/billing/CustomerBillingTable.vue
  src/modules/client/components/planning/EventCreationModal.vue
  src/modules/client/components/planning/EventEditionModal.vue
  src/modules/client/mixins/planningActionMixin.js
  src/modules/client/mixins/planningModalMixin.js
  src/modules/client/mixins/subscriptionMixin.js
  src/modules/client/pages/ni/billing/ToBill.vue
  src/modules/client/pages/ni/config/CustomersConfig.vue
  src/modules/client/pages/ni/courses/ELearningCourseProfile.vue
  src/modules/client/pages/ni/courses/ELearningCoursesDirectory.vue
  src/modules/client/pages/ni/exports/HistoryExports.vue
  src/modules/vendor/components/billing/BillingPurchaseAdditionModal.vue
  src/modules/vendor/components/billing/CourseBillValidationModal.vue
  src/modules/vendor/components/billing/CourseFeeEditionModal.vue
  src/modules/vendor/components/programs/ProfileContent.vue
  src/modules/vendor/components/programs/StepEditionModal.vue
  src/modules/vendor/pages/ni/management/ELearningCourseProfile.vue
  src/modules/vendor/pages/ni/management/ELearningCoursesDirectory.vue
Labels: staging

#1508 mini-fixes-mes-22-03: minor fixes
  src/core/components/courses/CourseBilling.vue
  src/modules/vendor/components/programs/StepEditionModal.vue
Labels: bug

#1505 Com 2764
  src/modules/client/mixins/planningActionMixin.js
Labels: dev

#1509 MES-22-03
  src/core/components/courses/CourseBilling.vue
  src/modules/client/components/config/ThirdPartyPayerEditionModal.vue
  src/modules/client/mixins/planningActionMixin.js
  src/modules/vendor/components/programs/StepEditionModal.vue
Labels: master

#1510 COM-2766 remove warning on test launch
  test/cypress/plugins/index.js
Labels: dev, tests

#1512 Com 2767
  test/cypress/integration/auxiliary/planning/auxiliaryAgenda.spec.js
  test/cypress/integration/customer/agenda.spec.js
  test/cypress/integration/customer/billing.spec.js
  test/cypress/integration/customer/subscription.spec.js
  test/cypress/integration/ni/planning/auxiliaryPlanning.spec.js
Labels: dev, tests

#1513 COM-2769 use luxon instead of cypress.moment
  package-lock.json
  package.json
  test/cypress/integration/auxiliary/planning/auxiliaryAgenda.spec.js
  test/cypress/integration/customer/agenda.spec.js
  test/cypress/integration/customer/subscription.spec.js
  test/cypress/integration/ni/planning/auxiliaryPlanning.spec.js
  test/cypress/support/index.js
Labels: dev, tests

#1514 COM-2760: can update vendor company
  src/core/api/VendorCompanies.js
  src/core/composables/validations.js
  src/modules/vendor/pages/ni/billing/BillingConfig.vue
Labels: dev

#1517 COM-2754: display bills on company profile
  src/core/components/courses/CourseBilling.vue
  src/core/data/constants.js
  src/modules/vendor/components/companies/ProfileBilling.vue
  src/modules/vendor/pages/ni/users/companies/CompanyProfile.vue
Labels: dev

#1518 Com 2770
  src/modules/client/components/customers/SubscriptionCell.vue
  test/cypress/integration/customer/subscription.spec.js
Labels: dev, tests

#1519 COM-2751: disable button + boyscout
  src/modules/client/pages/ni/config/CustomersConfig.vue
  src/modules/vendor/pages/ni/billing/BillingConfig.vue
Labels: dev

#1520 COM-2756: move type definition for companies
  src/modules/client/pages/ni/config/CompanyConfig.vue
  src/modules/vendor/components/companies/CompanyCreationModal.vue
  src/modules/vendor/components/companies/ProfileInfo.vue
  src/modules/vendor/pages/ni/users/companies/CompaniesDirectory.vue
Labels: dev
