Repository CompaniTech/compani-webapp, pull requests merged in 2022-10, with the labels that each got.

#1669 MES 03/10/22
  src/core/api/Attendances.js
  src/core/api/Courses.js
  src/core/components/courses/BlendedCourseProfileHeader.vue
  src/core/components/courses/CourseContainer.vue
  src/core/components/courses/ProfileOrganization.vue
  src/core/components/courses/SmsSendingModal.vue
  src/core/components/learners/ProfileCourses.vue
  src/core/components/table/AttendanceTable.vue
  src/core/data/constants.js
  src/core/helpers/dates/companiDates.js
  src/core/helpers/dates/utils.js
  src/modules/client/components/planning/EventCreationModal.vue
  src/modules/client/pages/ni/courses/BlendedCoursesDirectory.vue
  src/modules/client/pages/ni/courses/ELearningCoursesDirectory.vue
  src/modules/vendor/pages/ni/management/BlendedCoursesDirectory.vue
  src/modules/vendor/pages/ni/management/ELearningCoursesDirectory.vue
  src/modules/vendor/pages/trainers/management/BlendedCoursesDirectory.vue
Labels: staging

#1673 COM-3224 fix creation and edition of credit note
  src/modules/client/pages/ni/billing/CreditNotes.vue
Labels: bug

#1670 Feature luxon date component
  src/core/components/courses/BlendedCourseProfileHeader.vue
  src/core/components/courses/SlotContainer.vue
  src/core/components/form/DateInput.vue
  src/core/components/form/DateRange.vue
  src/core/components/form/DatetimeRange.vue
  src/core/components/form/TimeInput.vue
  src/core/helpers/date.js
  src/core/helpers/dates/companiDates.js
  src/core/helpers/dates/luxon.js
  src/core/helpers/vuelidateCustomVal.js
  src/modules/client/components/planning/CustomerAbsenceEditionModal.vue
  src/modules/client/components/planning/DeleteEventsModal.vue
  src/modules/client/components/planning/EventCancellationModal.vue
  src/modules/client/components/planning/EventCreationModal.vue
  src/modules/client/components/planning/EventEditionModal.vue
  src/modules/client/composables/planningAction.js
  src/modules/client/mixins/planningActionMixin.js
  src/modules/client/mixins/planningModalMixin.js
  src/modules/client/pages/auxiliaries/planning/AuxiliaryAgenda.vue
  src/modules/client/pages/ni/billing/CreditNotes.vue
  src/modules/client/pages/ni/planning/AuxiliaryPlanning.vue
  src/modules/client/pages/ni/planning/CustomerPlanning.vue
Labels: merge-feature

#1675 Com 3217
  src/core/components/courses/CourseHistory.vue
  src/core/components/courses/ProfileOrganization.vue
  src/core/components/courses/SlotContainer.vue
  src/core/helpers/dates/utils.js
  src/modules/client/components/planning/EventCreationModal.vue
Labels: dev

#1676 COM-3202: block non image/pdf file upload
  src/core/components/courses/AttendanceSheetAdditionModal.vue
  src/core/components/form/Input.vue
Labels: dev

#1681 MES 14/10
  .github/pull_request_template.md
  src/core/components/courses/AttendanceSheetAdditionModal.vue
  src/core/components/courses/BlendedCourseProfileHeader.vue
  src/core/components/courses/CourseHistory.vue
  src/core/components/courses/ProfileOrganization.vue
  src/core/components/courses/SlotContainer.vue
  src/core/components/form/DateInput.vue
  src/core/components/form/DateRange.vue
  src/core/components/form/DatetimeRange.vue
  src/core/components/form/Input.vue
  src/core/components/form/TimeInput.vue
  src/core/components/table/AttendanceTable.vue
  src/core/components/table/TraineeAttendanceCreationModal.vue
  src/core/helpers/date.js
  src/core/helpers/dates/companiDates.js
  src/core/helpers/dates/luxon.js
  src/core/helpers/dates/utils.js
  src/core/helpers/vuelidateCustomVal.js
  src/modules/client/components/planning/CustomerAbsenceEditionModal.vue
  src/modules/client/components/planning/DeleteEventsModal.vue
  src/modules/client/components/planning/EventCancellationModal.vue
  src/modules/client/components/planning/EventCreationModal.vue
  src/modules/client/components/planning/EventEditionModal.vue
  src/modules/client/composables/planningAction.js
  src/modules/client/mixins/planningActionMixin.js
  src/modules/client/mixins/planningModalMixin.js
  src/modules/client/pages/auxiliaries/planning/AuxiliaryAgenda.vue
  src/modules/client/pages/ni/billing/CreditNotes.vue
  src/modules/client/pages/ni/planning/AuxiliaryPlanning.vue
  src/modules/client/pages/ni/planning/CustomerPlanning.vue
Labels: staging

#1683 COM-3237: replace getTotalDuration with luxon
  src/core/components/courses/ProfileTraineeFollowUp.vue
  src/core/components/learners/ProfileCourses.vue
  src/core/data/constants.js
  src/core/helpers/date.js
  src/core/helpers/dates/companiDates.js
  src/core/helpers/dates/companiDurations.js
  src/core/helpers/dates/luxon.js
  src/core/helpers/dates/utils.js
Labels: dev

#1684 COM-3234 use constants for format
  src/core/components/courses/AttendanceSheetAdditionModal.vue
  src/core/components/courses/CourseHistory.vue
  src/core/components/courses/ProfileOrganization.vue
  src/core/components/courses/SlotContainer.vue
  src/core/components/form/DateInput.vue
  src/core/components/table/AttendanceTable.vue
  src/core/components/table/TraineeAttendanceCreationModal.vue
  src/core/data/constants.js
Labels: dev

#1686 COM-3244 remove moment from SlotContainer
  src/core/components/courses/SlotContainer.vue
Labels: dev

#1688 COM-3243 : remove moment from CourseCell
  src/core/components/courses/CourseCell.vue
  src/core/helpers/courses.js
  src/core/helpers/dates/companiDurations.js
  src/core/helpers/dates/utils.js
Labels: dev

#1690 COM-3230: remove formatIntervalHourly, getDuration & formatDuration
  src/core/components/courses/ProfileTraineeFollowUp.vue
  src/core/components/courses/SlotContainer.vue
  src/core/components/courses/SlotEditionModal.vue
  src/core/components/learners/ProfileCourses.vue
  src/core/helpers/courses.js
  src/core/helpers/date.js
  src/core/helpers/dates/utils.js
Labels: dev

#1692 Merge Feature-refacto-company-course-link in dev
  src/core/components/courses/ProfileBilling.vue
  src/core/components/courses/ProfileOrganization.vue
  src/core/components/courses/TraineeTable.vue
  src/core/components/table/AttendanceTable.vue
  src/core/helpers/courses.js
  src/core/mixins/courseFiltersMixin.js
  src/modules/vendor/components/companies/ProfileBilling.vue
Labels: merge-feature

#1693 MES 28/10/2022
  src/core/components/courses/AttendanceSheetAdditionModal.vue
  src/core/components/courses/CourseCell.vue
  src/core/components/courses/CourseHistory.vue
  src/core/components/courses/ProfileBilling.vue
  src/core/components/courses/ProfileOrganization.vue
  src/core/components/courses/ProfileTraineeFollowUp.vue
  src/core/components/courses/SlotContainer.vue
  src/core/components/courses/SlotEditionModal.vue
  src/core/components/courses/TraineeTable.vue
  src/core/components/form/DateInput.vue
  src/core/components/learners/ProfileCourses.vue
  src/core/components/table/AttendanceTable.vue
  src/core/components/table/TraineeAttendanceCreationModal.vue
  src/core/data/constants.js
  src/core/helpers/courses.js
  src/core/helpers/date.js
  src/core/helpers/dates/companiDates.js
  src/core/helpers/dates/companiDurations.js
  src/core/helpers/dates/luxon.js
  src/core/helpers/dates/utils.js
  src/core/mixins/courseFiltersMixin.js
  src/modules/client/mixins/planningTimelineMixin.js
  src/modules/client/pages/auxiliaries/planning/AuxiliaryAgenda.vue
  src/modules/client/pages/ni/planning/AuxiliaryPlanning.vue
  src/modules/client/pages/ni/planning/CustomerPlanning.vue
  src/modules/vendor/components/companies/ProfileBilling.vue
Labels: master
