Repository CompaniTech/compani-webapp, pull requests merged in 2022-06, with the labels that each got.

#1578 COM-2843: fix wrong alignment on table
  src/modules/client/pages/ni/courses/BillingProfile.vue
  src/modules/vendor/components/companies/ProfileBilling.vue
Labels: bug

#1582 COM-2889 - fix tests
  test/cypress/integration/customer/subscription.spec.js
Labels: tests

#1583 COM-2795 : npm update
  package-lock.json
  package.json
  src/core/components/Button.vue
  src/core/components/CourseProgress.vue
  src/core/data/constants.js
Labels: dependancies

#1584 COM-2847: refacto sales representative
  src/core/components/courses/InterlocutorCell.vue
  src/core/components/courses/InterlocutorModal.vue
  src/core/components/courses/ProfileOrganization.vue
  src/core/helpers/ability.js
Labels: dev

#1587 COM-2842: add constant
  src/core/data/constants.js
Labels: dev

#1591 COM-2815: display trainer infos
  src/core/components/courses/InterlocutorCell.vue
  src/core/components/courses/InterlocutorModal.vue
  src/core/components/courses/ProfileOrganization.vue
Labels: dev

#1593 COM-2880: underline link on hover + style
  src/core/components/courses/SlotContainer.vue
Labels: dev

#1594 COM-2821: can restore event
  src/core/data/constants.js
  src/core/helpers/date.js
  src/modules/client/components/planning/EventCancellationModal.vue
  src/modules/client/components/planning/EventEditionModal.vue
  src/modules/client/mixins/planningActionMixin.js
Labels: dev

#1598 COM-2877: move usefull docs section
  src/core/components/courses/CourseInfoLink.vue
  src/core/components/courses/ProfileOrganization.vue
  src/core/components/courses/ProfileTraineeFollowUp.vue
  src/core/mixins/courseMixin.js
Labels: dev

#1597 Com 2901
  src/core/components/courses/ProfileBilling.vue
  src/modules/vendor/components/billing/CourseBillCreationModal.vue
  src/modules/vendor/components/billing/CourseBillValidationModal.vue
  src/modules/vendor/components/billing/CourseBillingCard.vue
  src/modules/vendor/components/companies/ProfileBilling.vue
  src/modules/vendor/pages/ni/management/BlendedCourseProfile.vue
Labels: dev

#1599 COM-2875: refacto sms history
  src/core/components/Banner.vue
  src/core/components/courses/CourseSmsHistoryModal.vue
  src/core/components/courses/ProfileOrganization.vue
  src/core/components/courses/SmsCell.vue
  src/core/components/courses/SmsDetailsModal.vue
  src/modules/client/components/planning/HistoryCancellationModal.vue
Labels: dev

#1601 Com 2879
  src/core/components/courses/ProfileOrganization.vue
  src/core/components/courses/ProfileTraineeFollowUp.vue
  src/core/helpers/utils.js
  src/core/mixins/courseMixin.js
  src/modules/vendor/components/billing/CourseBillingCard.vue
  src/modules/vendor/components/companies/ProfileBilling.vue
Labels: dev

#1602 Com 2902
  src/core/components/courses/CourseSmsHistoryModal.vue
  src/core/components/courses/InterlocutorModal.vue
  src/css/app.sass
  src/modules/client/components/planning/EventCancellationModal.vue
  src/modules/vendor/components/billing/BillingPurchaseAdditionModal.vue
  src/modules/vendor/components/billing/CourseBillCreationModal.vue
  src/modules/vendor/components/billing/CourseBillValidationModal.vue
  src/modules/vendor/components/billing/CourseBillingCard.vue
  src/modules/vendor/components/billing/CourseCreditNoteCreationModal.vue
  src/modules/vendor/components/billing/CourseFeeEditionModal.vue
  src/modules/vendor/components/billing/CoursePaymentCreationModal.vue
  src/modules/vendor/components/billing/CoursePaymentEditionModal.vue
  src/modules/vendor/components/billing/PayerEditionModal.vue
Labels: dev

#1604 COM-2845: redirection to company profile
  src/modules/vendor/components/billing/CourseBillingCard.vue
  src/modules/vendor/router/routes.js
Labels: dev
