Repository CompaniTech/compani-webapp, pull requests merged in 2022-05, with the labels that each got.

#1550 COM-2833 add checkbox in teletransmission for onlyPastEvents
  src/modules/client/components/customers/billing/DeliveryDownloadModal.vue
  src/modules/client/pages/ni/billing/ToBill.vue
Labels: dev

#1553 COM-2835 - Specific 403 message
  src/core/components/courses/BlendedCourseProfileHeader.vue
  src/modules/vendor/pages/ni/management/BlendedCourseProfile.vue
Labels: bug, dev

#1555 MES 04/05/2022
  src/core/components/courses/BlendedCourseProfileHeader.vue
  src/modules/vendor/pages/ni/management/BlendedCourseProfile.vue
Labels: staging

#1554 COM-2816: hide button for clients
  src/core/components/courses/CourseHistory.vue
  src/core/components/courses/SlotContainer.vue
  src/core/components/courses/SlotEditionModal.vue
Labels: dev

#1558 COM-2817: delete slot creation modal
  src/core/components/courses/SlotContainer.vue
  src/core/components/courses/SlotCreationModal.vue
Labels: dev

#1561 COM-2852 display specific message when downloading template for remot…
  src/core/components/courses/ProfileTraineeFollowUp.vue
Labels: bug, dev

#1559 COM-2837: display slots by step
  src/core/components/courses/SlotContainer.vue
  src/css/quasar.variables.sass
Labels: dev

#1562 COM-2825: remove select to update step
  src/core/components/courses/SlotContainer.vue
  src/core/components/courses/SlotEditionModal.vue
Labels: dev

#1564 COM-2837: move slots to plan section
  src/core/components/courses/SlotContainer.vue
Labels: dev

#1565 MES 16/05/2022
  src/core/components/courses/CourseHistory.vue
  src/core/components/courses/ProfileTraineeFollowUp.vue
  src/core/components/courses/SlotContainer.vue
  src/core/components/courses/SlotCreationModal.vue
  src/core/components/courses/SlotEditionModal.vue
  src/css/quasar.variables.sass
Labels: staging

#1570 COM-2812: add companies as possible payers
  src/core/components/courses/ProfileBilling.vue
Labels: dev

#1571 COM-2813: display bills by payer
  src/modules/vendor/components/companies/ProfileBilling.vue
Labels: dev

#1575 COM-2844: refacto address
  src/modules/vendor/components/billing/CourseFundingOrganisationCreationModal.vue
  src/modules/vendor/pages/ni/billing/BillingConfig.vue
Labels: dev
