Repository CompaniTech/compani-webapp, pull requests merged in 2022-04, with the labels that each got.

#1523 COM-2754: change program name color
  src/modules/vendor/components/companies/ProfileBilling.vue
Labels: dev

#1524 MES 04-04
  package-lock.json
  package.json
  quasar.conf.js
  src/core/api/VendorCompanies.js
  src/core/components/courses/CourseBilling.vue
  src/core/components/menu/SideMenuFooter.vue
  src/core/composables/validations.js
  src/core/data/constants.js
  src/modules/client/components/customers/SubscriptionCell.vue
  src/modules/client/pages/ni/config/CompanyConfig.vue
  src/modules/client/pages/ni/config/CustomersConfig.vue
  src/modules/vendor/components/companies/CompanyCreationModal.vue
  src/modules/vendor/components/companies/ProfileBilling.vue
  src/modules/vendor/components/companies/ProfileInfo.vue
  src/modules/vendor/pages/ni/billing/BillingConfig.vue
  src/modules/vendor/pages/ni/users/companies/CompaniesDirectory.vue
  src/modules/vendor/pages/ni/users/companies/CompanyProfile.vue
  test/cypress/integration/auxiliary/planning/auxiliaryAgenda.spec.js
  test/cypress/integration/customer/agenda.spec.js
  test/cypress/integration/customer/billing.spec.js
  test/cypress/integration/customer/subscription.spec.js
  test/cypress/integration/ni/planning/auxiliaryPlanning.spec.js
  test/cypress/plugins/index.js
  test/cypress/support/index.js
Labels: staging

#1525 COM-2755: can add payment
  src/core/api/CoursePayments.js
  src/modules/vendor/components/billing/CoursePaymentCreationModal.vue
  src/modules/vendor/components/companies/ProfileBilling.vue
Labels: dev

#1526 COM-2780: download files
  src/core/api/GoogleDrive.js
  src/core/components/courses/ProfileOrganization.vue
  src/core/components/courses/ProfileTraineeFollowUp.vue
  src/core/helpers/file.js
  src/modules/client/components/customers/billing/CustomerBillingTable.vue
  src/modules/client/composables/taxCertificates.js
  src/modules/client/mixins/customerMixin.js
Labels: dev

#1528 COM-2771: can edit payment
  src/core/api/CoursePayments.js
  src/modules/vendor/components/billing/CoursePaymentEditionModal.vue
  src/modules/vendor/components/companies/ProfileBilling.vue
Labels: dev

#1532 Com 2787
  src/core/data/constants.js
  test/cypress/integration/authenticate.spec.js
  test/cypress/integration/auxiliary/planning/auxiliaryAgenda.spec.js
  test/cypress/integration/customer/agenda.spec.js
  test/cypress/integration/customer/billing.spec.js
  test/cypress/integration/customer/contact.spec.js
  test/cypress/integration/customer/subscription.spec.js
  test/cypress/integration/ni/billing/toBill.spec.js
  test/cypress/integration/ni/planning/auxiliaryPlanning.spec.js
  test/cypress/plugins/index.js
  test/cypress/support/commands.js
Labels: dev, tests

#1534 COM-2773: add columns
  src/core/components/courses/ProfileBilling.vue
  src/core/components/table/ExpandingTable.vue
  src/core/data/constants.js
  src/core/helpers/utils.js
  src/modules/vendor/components/billing/CourseCreditNoteCreationModal.vue
  src/modules/vendor/components/companies/ProfileBilling.vue
Labels: dev

#1539 MES - fix payment
  src/modules/vendor/components/companies/ProfileBilling.vue
Labels: master

#1536 COM-2792: display estimated start date field
  src/core/components/courses/ProfileOrganization.vue
  src/core/components/courses/SlotContainer.vue
  src/modules/vendor/components/courses/CourseCreationModal.vue
  src/modules/vendor/pages/ni/management/BlendedCoursesDirectory.vue
Labels: dev

#1537 Com 2774
  src/core/api/CourseCreditNotes.js
  src/core/components/courses/ElearningFollowUpTable.vue
  src/core/components/courses/ProfileBilling.vue
  src/core/components/courses/ProfileTraineeFollowUp.vue
  src/core/components/learners/ProfileCourses.vue
  src/css/app.sass
  src/css/quasar.variables.sass
  src/modules/vendor/components/companies/ProfileBilling.vue
Labels: dev

#1541 COM-2772: add text and subtext in modal
  src/core/components/courses/ProfileBilling.vue
  src/modules/vendor/components/billing/CourseCreditNoteCreationModal.vue
Labels: dev

#1540 COM-2791: redirect to course profile (billing) when click on course name
  src/modules/vendor/components/companies/ProfileBilling.vue
  src/modules/vendor/router/routes.js
Labels: dev

#1543 COM-2823 rename field
  src/modules/client/components/customers/infos/ProfileInfo.vue
Labels: dev

#1545 COM-2786: add trim to authenticate and forgot password
  src/core/pages/signin/Authenticate.vue
  src/core/pages/signin/ForgotPassword.vue
Labels: dev

#1546 COM-2772: change caption
  src/modules/vendor/components/billing/CourseCreditNoteCreationModal.vue
Labels: dev

#1547 COM-2791: can't click outside of program name
  src/modules/vendor/components/companies/ProfileBilling.vue
Labels: bug

#1548 COM-2790: change caption and show last bill details
  src/core/components/courses/ProfileBilling.vue
  src/modules/vendor/components/billing/CourseBillCreationModal.vue
Labels: dev
