Repository CompaniTech/compani-webapp, pull requests merged in 2022-07, with the labels that each got.

#1607 COM-2821: on small screen space between both buttons
  src/modules/client/components/planning/EventEditionModal.vue
Labels: dev

#1608 MES 04/07
  src/core/api/Repetitions.js
  src/core/components/Banner.vue
  src/core/components/courses/CourseInfoLink.vue
  src/core/components/courses/CourseSmsHistoryModal.vue
  src/core/components/courses/InterlocutorModal.vue
  src/core/components/courses/ProfileBilling.vue
  src/core/components/courses/ProfileOrganization.vue
  src/core/components/courses/ProfileTraineeFollowUp.vue
  src/core/components/courses/SmsCell.vue
  src/core/components/courses/SmsDetailsModal.vue
  src/core/components/courses/TraineeTable.vue
  src/core/data/constants.js
  src/core/helpers/rbac.js
  src/core/helpers/utils.js
  src/core/mixins/courseMixin.js
  src/css/app.sass
  src/modules/client/components/planning/EventCancellationModal.vue
  src/modules/client/components/planning/EventEditionModal.vue
  src/modules/client/components/planning/HistoryCancellationModal.vue
  src/modules/client/components/planning/RepetitionCell.vue
  src/modules/client/components/planning/RepetitionDeletionConfirmationModal.vue
  src/modules/client/components/planning/RepetitionDeletionModal.vue
  src/modules/client/mixins/menuItemsMixin.js
  src/modules/client/mixins/planningModalMixin.js
  src/modules/client/pages/ni/planning/RepetitionsPlanning.vue
  src/modules/client/router/routes.js
  src/modules/vendor/components/billing/BillingPurchaseAdditionModal.vue
  src/modules/vendor/components/billing/CourseBillCreationModal.vue
  src/modules/vendor/components/billing/CourseBillValidationModal.vue
  src/modules/vendor/components/billing/CourseBillingCard.vue
  src/modules/vendor/components/billing/CourseCreditNoteCreationModal.vue
  src/modules/vendor/components/billing/CourseFeeEditionModal.vue
  src/modules/vendor/components/billing/CoursePaymentCreationModal.vue
  src/modules/vendor/components/billing/CoursePaymentEditionModal.vue
  src/modules/vendor/components/billing/PayerEditionModal.vue
  src/modules/vendor/components/companies/ProfileBilling.vue
  src/modules/vendor/pages/ni/management/BlendedCourseProfile.vue
  src/modules/vendor/router/routes.js
Labels: staging

#1610 Mini mes 04/07
  src/modules/client/mixins/menuItemsMixin.js
  src/modules/client/router/routes.js
Labels: staging

#1611 COM-2916: i can add company representative to course
  src/core/components/courses/InterlocutorCell.vue
  src/core/components/courses/InterlocutorModal.vue
  src/core/components/courses/ProfileOrganization.vue
  src/store/course.js
Labels: dev

#1581 COM-2888 first test for end2end tests workflow
  .github/workflows/node.js.yml
  .gitignore
  package.json
  test/cypress/integration/auxiliary/planning/auxiliaryAgenda.spec.js
  test/cypress/integration/customer/agenda.spec.js
  test/cypress/integration/customer/subscription.spec.js
  test/cypress/integration/ni/planning/auxiliaryPlanning.spec.js
  test/cypress/support/utils.js
Labels: dev, tests

#1616 Com 2918
  src/core/components/courses/InterlocutorCell.vue
  src/core/components/courses/InterlocutorModal.vue
  src/core/components/courses/ProfileOrganization.vue
Labels: dev

#1618 COM-2953: add unbreakeable spaces before '?'
  src/core/components/CompanyLinkRequestCell.vue
  src/core/components/PictureUploader.vue
  src/core/components/courses/ElearningFollowUpTable.vue
  src/core/components/courses/SlotEditionModal.vue
  src/core/components/courses/TraineeTable.vue
  src/core/components/table/AttendanceTable.vue
  src/core/mixins/cardMixin.js
  src/core/pages/signin/Authenticate.vue
  src/modules/client/components/auxiliary/ProfileContracts.vue
  src/modules/client/components/auxiliary/ProfileInfo.vue
  src/modules/client/components/auxiliary/ProfilePay.vue
  src/modules/client/components/customers/CustomerProfileHeader.vue
  src/modules/client/components/customers/ProfileFollowUp.vue
  src/modules/client/components/customers/infos/ProfileInfo.vue
  src/modules/client/components/customers/infos/StopSupportModal.vue
  src/modules/client/components/planning/CustomerAbsenceEditionModal.vue
  src/modules/client/components/planning/DeleteEventsModal.vue
  src/modules/client/components/planning/EventCancellationModal.vue
  src/modules/client/components/planning/EventEditionModal.vue
  src/modules/client/components/planning/HistoryCancellationModal.vue
  src/modules/client/components/planning/RepetitionDeletionConfirmationModal.vue
  src/modules/client/composables/payments.js
  src/modules/client/composables/taxCertificates.js
  src/modules/client/mixins/configMixin.js
  src/modules/client/mixins/contractMixin.js
  src/modules/client/mixins/financialCertificatesMixin.js
  src/modules/client/mixins/helperMixin.js
  src/modules/client/mixins/planningActionMixin.js
  src/modules/client/pages/ni/billing/ClientsBalances.vue
  src/modules/client/pages/ni/billing/ManualBills.vue
  src/modules/client/pages/ni/billing/ToBill.vue
  src/modules/client/pages/ni/config/CompanyConfig.vue
  src/modules/client/pages/ni/config/CustomersConfig.vue
  src/modules/client/pages/ni/config/RhConfig.vue
  src/modules/client/pages/ni/pay/ContractEnds.vue
  src/modules/client/pages/ni/pay/ToPay.vue
  src/modules/client/pages/ni/planning/CustomerPlanning.vue
  src/modules/vendor/components/billing/CourseBillValidationModal.vue
  src/modules/vendor/components/billing/CourseBillingCard.vue
  src/modules/vendor/components/courses/ProfileAccess.vue
  src/modules/vendor/components/programs/ProfileContent.vue
  src/modules/vendor/components/programs/ProfileInfo.vue
  src/modules/vendor/components/programs/TesterTable.vue
  src/modules/vendor/components/programs/ValidateUnlockingStepModal.vue
  src/modules/vendor/components/questionnaires/ProfileEdition.vue
  src/modules/vendor/mixins/templateMixin.js
  src/modules/vendor/pages/ni/billing/BillingConfig.vue
  src/modules/vendor/pages/ni/management/BlendedCourseProfile.vue
  src/modules/vendor/pages/ni/pedagogy/ActivityProfile.vue
  src/modules/vendor/pages/ni/pedagogy/CategoriesDirectory.vue
Labels: dev

#1620 COM-2954 add course payment export
  src/core/data/constants.js
Labels: dev

#1625 Com 2895
  src/core/api/GoogleDrive.js
  src/modules/client/components/customers/billing/CustomerBillingTable.vue
  src/modules/client/components/customers/billing/ProfileBilling.vue
  src/modules/client/composables/taxCertificates.js
  src/modules/client/pages/customers/Subscriptions.vue
  src/modules/client/pages/ni/billing/TppBillSlips.vue
Labels: dev
