Repository CompaniTech/compani-webapp, pull requests merged in 2022-02, with the labels that each got.

#1442 COM-2615: display presence progress
  src/core/components/learners/ProfileCourses.vue
Labels: dev

#1445 Com 2642
  src/core/components/courses/CourseCell.vue
  src/core/components/courses/CourseHistory.vue
  src/core/components/courses/ProfileTraineeFollowUp.vue
  src/core/components/courses/SlotContainer.vue
  src/core/components/learners/ProfileCourses.vue
  src/core/helpers/date.js
  src/core/helpers/utils.js
  src/modules/client/components/customers/ProfileFollowUp.vue
  src/modules/client/components/customers/infos/CustomerNoteHistory.vue
  src/modules/client/components/pay/PaySurchargeDetailsModal.vue
  src/modules/client/components/planning/AuxiliaryIndicators.vue
  src/modules/client/components/planning/EventHistory.vue
  src/modules/client/mixins/fundingMixin.js
  src/modules/client/mixins/payMixin.js
  src/modules/client/pages/ni/auxiliaries/Dashboard.vue
  src/modules/client/pages/ni/config/CustomersConfig.vue
  src/modules/client/pages/ni/customers/CustomersFundingsMonitoring.vue
  src/modules/client/pages/ni/pay/Absences.vue
Labels: dev

#1446 COM-2642: add to come mention for slot to come
  src/core/components/learners/ProfileCourses.vue
Labels: dev

#1448 COM-2671 - fix customer balance
  src/modules/client/composables/balance.js
Labels: bug, dev

#1449 MEP-mobile
  src/core/api/CourseFundingOrganisations.js
  src/core/components/courses/CourseCell.vue
  src/core/components/courses/CourseHistory.vue
  src/core/components/courses/ElearningFollowUpTable.vue
  src/core/components/courses/ProfileFollowUp.vue
  src/core/components/courses/ProfileTraineeFollowUp.vue
  src/core/components/courses/SlotContainer.vue
  src/core/components/courses/SlotCreationModal.vue
  src/core/components/courses/SlotEditionModal.vue
  src/core/components/learners/ProfileCourses.vue
  src/core/composables/learners.js
  src/core/helpers/date.js
  src/core/helpers/rbac.js
  src/core/helpers/utils.js
  src/core/mixins/traineeFollowUpTableMixin.js
  src/modules/client/components/customers/ProfileFollowUp.vue
  src/modules/client/components/customers/infos/CustomerNoteHistory.vue
  src/modules/client/components/pay/PaySurchargeDetailsModal.vue
  src/modules/client/components/planning/AuxiliaryIndicators.vue
  src/modules/client/components/planning/EventHistory.vue
  src/modules/client/composables/balance.js
  src/modules/client/mixins/fundingMixin.js
  src/modules/client/mixins/payMixin.js
  src/modules/client/pages/ni/auxiliaries/Dashboard.vue
  src/modules/client/pages/ni/config/CustomersConfig.vue
  src/modules/client/pages/ni/customers/CustomersFundingsMonitoring.vue
  src/modules/client/pages/ni/pay/Absences.vue
  src/modules/vendor/components/billing/CourseFundingOrganisationCreationModal.vue
  src/modules/vendor/components/companies/ProfileInfo.vue
  src/modules/vendor/mixins/menuItemsMixin.js
  src/modules/vendor/pages/ni/billing/BillingConfig.vue
  src/modules/vendor/router/routes.js
Labels: staging

#1450 COM-2642: change 'to come' mention style
  src/core/components/learners/ProfileCourses.vue
Labels: dev

#1451 MES
  src/core/components/learners/ProfileCourses.vue
Labels: staging

#1453 COM-2665: add billing item
  src/core/api/CourseBillingItems.js
  src/modules/vendor/components/billing/CourseBillingItemCreationModal.vue
  src/modules/vendor/pages/ni/billing/BillingConfig.vue
Labels: dev

#1454 COM-2678 condition on createdAt instead of index
  src/modules/client/components/customers/infos/ProfileInfo.vue
Labels: bug, dev

#1455 Com 2657
  src/core/data/constants.js
  src/modules/client/components/customers/billing/CreditNoteCreationModal.vue
  src/modules/client/components/customers/billing/CreditNoteEditionModal.vue
  src/modules/client/pages/ni/billing/CreditNotes.vue
Labels: dev

#1459 COM-2687 - Fix bug for billing items in service creation and edition
  src/modules/client/pages/ni/config/CustomersConfig.vue
Labels: dev

#1458 Com 2657 2
  src/core/data/constants.js
  src/modules/client/components/customers/billing/CreditNoteCreationModal.vue
  src/modules/client/components/customers/billing/ManualBillCreationModal.vue
  src/modules/client/pages/ni/billing/CreditNotes.vue
Labels: dev

#1463 MES 21/02
  src/core/api/CourseBillingItems.js
  src/core/components/courses/ProfileAdmin.vue
  src/core/components/courses/ProfileOrganization.vue
  src/core/components/courses/ProfileTraineeFollowUp.vue
  src/core/data/constants.js
  src/core/mixins/courseMixin.js
  src/modules/client/components/customers/billing/CreditNoteCreationModal.vue
  src/modules/client/components/customers/billing/CreditNoteEditionModal.vue
  src/modules/client/components/customers/billing/ManualBillCreationModal.vue
  src/modules/client/components/customers/infos/ProfileInfo.vue
  src/modules/client/components/planning/Agenda.vue
  src/modules/client/components/planning/EventHours.vue
  src/modules/client/components/planning/PlanningEventCell.vue
  src/modules/client/mixins/planningActionMixin.js
  src/modules/client/mixins/planningEventMixin.js
  src/modules/client/pages/ni/billing/CreditNotes.vue
  src/modules/client/pages/ni/config/CustomersConfig.vue
  src/modules/client/pages/ni/courses/BlendedCourseProfile.vue
  src/modules/vendor/components/billing/CourseBillingItemCreationModal.vue
  src/modules/vendor/pages/ni/billing/BillingConfig.vue
  src/modules/vendor/pages/ni/management/BlendedCourseProfile.vue
Labels: staging

#1465 COM-2696: add facturation tab
  src/core/api/CourseBills.js
  src/core/components/courses/CourseBilling.vue
  src/modules/vendor/components/billing/CourseBillCreationModal.vue
  src/modules/vendor/pages/ni/management/BlendedCourseProfile.vue
Labels: dev

#1464 Com 2709
  src/core/data/constants.js
  src/modules/client/components/customers/infos/ProfileInfo.vue
  src/modules/client/components/customers/infos/SubscriptionCreationModal.vue
  src/modules/client/components/customers/infos/SubscriptionEditionModal.vue
  src/modules/client/components/planning/EventHours.vue
  src/modules/client/helpers/tags.js
  src/modules/client/mixins/subscriptionMixin.js
  src/modules/client/pages/customers/Subscriptions.vue
  test/cypress/integration/customer/subscription.spec.js
Labels: dev

#1466 COM-2697: edit funder
  src/core/api/CourseBills.js
  src/core/components/courses/CourseBilling.vue
  src/modules/vendor/components/billing/FunderEditionModal.vue
Labels: dev

#1468 Com 2702
  src/core/components/courses/CourseBilling.vue
  src/core/helpers/vuelidateCustomVal.js
  src/modules/vendor/components/billing/CourseBillCreationModal.vue
Labels: dev
