Repository CompaniTech/compani-webapp, pull requests merged in 2022-08, with the labels that each got.

#1632 Com 2927
  src/core/components/courses/CourseCell.vue
  src/core/components/courses/ElearningFollowUpTable.vue
  src/core/components/courses/ProfileBilling.vue
  src/core/components/courses/TraineeTable.vue
  src/core/composables/courses.js
  src/core/helpers/courses.js
  src/modules/vendor/components/programs/ProfileContent.vue
  src/modules/vendor/components/programs/StepAdditionModal.vue
Labels: dev

#1633 Com 2927 2
  src/core/components/courses/CourseCell.vue
  src/core/components/courses/ElearningFollowUpTable.vue
  src/core/components/courses/ProfileOrganization.vue
  src/core/components/courses/TraineeTable.vue
  src/core/composables/courses.js
  src/modules/client/pages/ni/courses/BlendedCourseProfile.vue
  src/modules/vendor/components/companies/ProfileBilling.vue
  src/modules/vendor/components/programs/StepAdditionModal.vue
  src/modules/vendor/components/programs/TesterTable.vue
  src/modules/vendor/pages/ni/management/BlendedCourseProfile.vue
Labels: dev

#1638 COM-2970 - allow negative discount
  src/modules/client/components/table/ToBillRow.vue
Labels: bug, dev

#1639 MES 16/08
  src/modules/client/components/table/ToBillRow.vue
Labels: master
