Repository CompaniTech/compani-webapp, pull requests merged in 2023-07, with the labels that each got.

#1837 COM-3502: rename downloaded file
  src/core/components/courses/TrainingContractContainer.vue
Labels: dev

#1836 Com 3499
  src/core/components/SecondaryButton.vue
  src/core/components/courses/InterlocutorCell.vue
  src/core/components/courses/ProfileOrganization.vue
  src/css/app.sass
  src/css/interlocutor.sass
  src/modules/vendor/pages/ni/config/MainConfig.vue
Labels: dev

#1841 COM-3510: can access user
  src/store/userProfile.js
Labels: dev

#1843 COM-3500 - display billingRepresentative on ContactProfile
  src/modules/client/pages/ni/courses/ContactProfile.vue
Labels: dev

#1842 COM-3505 - can define billing representative of my company
  src/modules/client/mixins/configMixin.js
  src/modules/client/pages/ni/config/CompanyConfig.vue
Labels: dev

#1846 COM-3505 - fix validation bug
  src/modules/client/mixins/configMixin.js
  src/modules/client/pages/ni/config/CompanyConfig.vue
Labels: dev

#1845 COM-3504 - can define billing representative on company's profile
  src/core/components/courses/InterlocutorCell.vue
  src/modules/vendor/components/companies/ProfileBilling.vue
Labels: dev

#1848 MES 27/07/2023
  src/core/components/courses/InterlocutorCell.vue
  src/core/components/courses/InterlocutorModal.vue
  src/core/components/courses/ProfileOrganization.vue
  src/core/helpers/rbac.js
  src/modules/client/mixins/configMixin.js
  src/modules/client/mixins/menuItemsMixin.js
  src/modules/client/pages/ni/config/CompanyConfig.vue
  src/modules/client/pages/ni/courses/ContactProfile.vue
  src/modules/client/router/routes.js
  src/modules/vendor/components/companies/ProfileBilling.vue
  src/modules/vendor/pages/ni/config/MainConfig.vue
  src/store/userProfile.js
Labels: staging

#1847 COM-3509: get trainees from course
  src/core/components/table/AttendanceTable/Composables/Attendances.js
Labels: dev

#1850 Dev
  src/core/components/table/AttendanceTable/Composables/Attendances.js
  src/modules/vendor/components/companies/ProfileBilling.vue
Labels: master
