Repository CompaniTech/compani-webapp, pull requests merged in 2023-01, with the labels that each got.

#1738 Com 3340
  src/core/components/courses/TraineeContainer.vue
  src/core/components/courses/TraineeTable.vue
Labels: dev

#1742 MES 11/01
  .github/workflows/endToEnd.js.yml
  src/core/components/courses/LearnerCreationModal.vue
  src/core/components/courses/TraineeContainer.vue
  src/core/components/courses/TraineeTable.vue
  src/core/composables/learners.js
  src/modules/client/pages/ni/courses/LearnersDirectory.vue
  src/modules/vendor/components/companies/CompanyLinkModal.vue
  src/modules/vendor/pages/ni/users/learners/LearnerProfile.vue
  src/modules/vendor/pages/ni/users/learners/LearnersDirectory.vue
Labels: master

#1743 COM-3365: can add auxiliary in the future
  src/core/helpers/userCompanies.js
  src/modules/client/pages/ni/auxiliaries/Directory.vue
  src/store/userProfile.js
Labels: dev

#1748 MES 1 projet détachement 18/01
  .github/workflows/endToEnd.js.yml
  quasar.conf.js
  src/core/api/UserCompanies.js
  src/core/components/courses/TraineeContainer.vue
  src/core/components/learners/CompanyDetachModal.vue
  src/core/components/learners/ProfileCourses.vue
  src/core/components/table/CoachList.vue
  src/core/composables/companyDetachment.js
  src/core/composables/learners.js
  src/core/helpers/userCompanies.js
  src/core/mixins/courseFiltersMixin.js
  src/modules/client/mixins/helperMixin.js
  src/modules/client/pages/ni/auxiliaries/Directory.vue
  src/modules/client/pages/ni/courses/BlendedCoursesDirectory.vue
  src/modules/client/pages/ni/courses/LearnerProfile.vue
  src/modules/vendor/components/billing/CourseBillingCard.vue
  src/modules/vendor/pages/ni/management/BlendedCoursesDirectory.vue
  src/modules/vendor/pages/ni/users/learners/LearnerProfile.vue
  src/modules/vendor/pages/trainers/management/BlendedCoursesDirectory.vue
  src/store/course.js
  src/store/userProfile.js
Labels: dev

#1751 COM-3382 - display error
  src/core/components/courses/SlotContainer.vue
Labels: bug

#1755 COM-3379: array is not sorted again when new attendances
  src/core/components/table/AttendanceTable.vue
Labels: bug
