Repository CompaniTech/compani-webapp, pull requests merged in 2023-03, with the labels that each got.

#1776 COM-3352 show NotifyPositive on attendanceTable only if unsubscribed …
  src/core/components/table/AttendanceTable.vue
Labels: dev

#1780 COM-3404: disable required on phone when future trainee coach side
  src/core/components/courses/LearnerCreationModal.vue
  src/core/composables/learners.js
Labels: dev

#1778 Com 3358
  src/core/components/courses/ProfileOrganization.vue
  src/core/components/table/AttendanceTable/Composables/Attendances.js
  src/core/composables/learners.js
  src/core/data/constants.js
Labels: dev

#1781 MES 06/03
  package-lock.json
  package.json
  src/core/components/courses/ElearningFollowUpTable.vue
  src/core/components/courses/LearnerCreationModal.vue
  src/core/components/courses/ProfileOrganization.vue
  src/core/components/courses/TraineeContainer.vue
  src/core/components/learners/ProfileCourses.vue
  src/core/components/table/AttendanceTable.vue
  src/core/components/table/AttendanceTable/Composables/AttendanceSheets.js
  src/core/components/table/AttendanceTable/Composables/Attendances.js
  src/core/components/table/AttendanceTable/index.vue
  src/core/composables/learners.js
  src/core/data/constants.js
  src/modules/client/components/auxiliary/AuxiliaryProfileHeader.vue
  src/modules/client/components/customers/CustomerProfileHeader.vue
  src/modules/client/pages/ni/billing/Bills.vue
  src/modules/client/pages/ni/billing/ClientsBalances.vue
  src/modules/client/pages/ni/pay/ContractMonitoring.vue
  src/modules/client/router/routes.js
  src/modules/vendor/components/billing/CourseBillingCard.vue
  src/modules/vendor/components/companies/ProfileBilling.vue
  src/modules/vendor/router/routes.js
Labels: staging

#1779 Com 3409
  package-lock.json
  package.json
  src/core/api/ressources/alenviAxios.js
  src/core/components/menu/SideMenuFooter.vue
  src/modules/client/router/routes.js
Labels: dependancies

#1782 COm-3414 fix getCurrentAndFutureCompanies
  src/core/helpers/userCompanies.js
Labels: dev

#1785 COM-3421 route to 404 when user is not in the company anymore
  src/store/userProfile.js
Labels: dev

#1784 COM-3416: can generate contract
  src/core/api/Courses.js
  src/core/components/courses/ProfileOrganization.vue
  src/core/components/courses/TrainingContractContainer.vue
  src/core/components/courses/TrainingContractInfosModal.vue
  src/core/components/courses/TrainingContractPriceAdditionModal.vue
  src/core/helpers/utils.js
Labels: dev

#1791 Com 3415 fix bug
  src/core/components/courses/ElearningFollowUpTable.vue
  src/core/components/courses/TraineeContainer.vue
  src/core/components/courses/TraineeTable.vue
  src/core/components/table/AttendanceTable/Composables/Attendances.js
  src/core/components/table/AttendanceTable/index.vue
  src/core/composables/learnersCreation.js
  src/core/composables/learnersEdition.js
  src/core/composables/traineeFollowUp.js
  src/modules/client/pages/ni/courses/LearnersDirectory.vue
  src/modules/vendor/pages/ni/users/learners/LearnersDirectory.vue
Labels: dev
