Repository CompaniTech/compani-webapp, pull requests merged in 2023-08, with the labels that each got.

#1852 MES 01/08
  src/modules/vendor/components/companies/ProfileBilling.vue
Labels: staging

#1853 COM-3532: update to node 18 + dependencies
  .eslintrc.js
  .github/workflows/endToEnd.js.yml
  .github/workflows/lint.yml
  package-lock.json
  package.json
  src/core/api/PayDocuments.js
  src/core/api/ressources/alenviAxios.js
  src/core/helpers/ability.js
  src/modules/client/components/planning/RepetitionCell.vue
  src/modules/client/pages/ni/auxiliaries/AuxiliaryProfile.vue
  src/modules/client/pages/ni/courses/LearnerProfile.vue
  src/modules/client/pages/ni/customers/CustomerProfile.vue
  src/modules/client/pages/ni/planning/RepetitionsPlanning.vue
  src/modules/vendor/pages/ni/management/ELearningCourseProfile.vue
  src/modules/vendor/pages/ni/pedagogy/ProgramProfile.vue
  src/modules/vendor/pages/ni/pedagogy/QuestionnaireProfile.vue
  src/modules/vendor/pages/ni/users/companies/CompanyProfile.vue
  src/modules/vendor/pages/ni/users/learners/LearnerProfile.vue
  src/modules/vendor/pages/ni/users/trainers/TrainerProfile.vue
Labels: dependencies

#1855 COM-3386: display activities count on elearning step only
  src/modules/vendor/components/programs/ProfileContent.vue
Labels: dev

#1861 COM-3521 - restrictive questionnnaire card templates
  src/modules/vendor/components/programs/cards/CardCreationModal.vue
  src/modules/vendor/components/questionnaires/ProfileEdition.vue
Labels: dev

#1863 Com 3523
  src/core/api/Courses.js
  src/core/api/QuestionnaireHistories.js
  src/core/api/Questionnaires.js
  src/core/components/questionnaires/cards/End.vue
  src/core/components/questionnaires/cards/Footer.vue
  src/core/components/questionnaires/cards/MetaInfos.vue
  src/core/components/questionnaires/cards/Start.vue
  src/core/data/constants.js
  src/css/app.sass
  src/css/questionnaire.sass
  src/modules/notLogged/pages/QuestionnaireForm.vue
  src/modules/vendor/store/questionnaire.js
Labels: dev

#1857 COM-3536: open learner in new tab
  src/css/app.sass
  src/modules/client/pages/ni/courses/LearnersDirectory.vue
  src/modules/vendor/pages/ni/users/learners/LearnersDirectory.vue
Labels: dev

#1864 Com 3524
  src/core/components/questionnaires/cards/CardTemplate.vue
  src/core/components/questionnaires/cards/Footer.vue
  src/core/components/questionnaires/cards/MetaInfos.vue
  src/core/components/questionnaires/cards/Transition.vue
  src/css/questionnaire.sass
  src/modules/notLogged/pages/QuestionnaireForm.vue
Labels: dev

#1858 COM-3538: can archive and unarchive course easily
  src/core/components/courses/BlendedCourseProfileHeader.vue
  src/core/components/form/FileUploader.vue
Labels: dev
