Repository CompaniTech/compani-webapp, pull requests merged in 2023-10, with the labels that each got.

#1879 COM-3554: can add company
  src/core/components/courses/ProfileOrganization.vue
  src/core/components/courses/TraineeContainer.vue
  src/core/composables/companiesCoursesLink.js
  src/core/helpers/ability.js
  src/modules/vendor/components/holdings/ProfileInfo.vue
Labels: dev

#1881 Com 3555
  src/core/components/courses/ProfileOrganization.vue
  src/core/components/courses/TraineeContainer.vue
Labels: dev

#1882 COM-3556: can add trainee
  src/core/components/courses/ProfileOrganization.vue
  src/core/components/courses/TraineeContainer.vue
  src/core/components/courses/TraineeTable.vue
  src/core/helpers/ability.js
Labels: dev

#1885 COM-3574 - fix blur trigger on date input icon click
  src/core/components/form/DateInput.vue
  src/core/components/form/DateRange.vue
  src/modules/client/pages/ni/billing/ToBill.vue
  test/cypress/integration/ni/billing/toBill.spec.js
Labels: bug

#1883 COM-3560: can download attendance sheet
  src/core/components/courses/ProfileOrganization.vue
Labels: dev

#1886 COM-3566: block sections
  src/core/components/courses/ProfileOrganization.vue
  src/core/components/learners/ProfileCourses.vue
  src/modules/client/pages/ni/courses/BlendedCourseProfile.vue
  src/modules/vendor/pages/ni/management/BlendedCourseProfile.vue
Labels: dev

#1888 COM-3579 - add default description in draft bill
  src/core/helpers/courses.js
  src/modules/vendor/components/billing/CourseBillingCard.vue
Labels: dev

#1890 COM-3567: can create intra_holding course
  src/core/composables/courseFilters.js
  src/core/data/constants.js
  src/modules/vendor/components/courses/CourseCreationModal.vue
  src/modules/vendor/pages/ni/management/BlendedCoursesDirectory.vue
Labels: dev

#1891 COM-3575 - can choose sending email at coach account creation
  src/core/components/table/CoachCreationModal.vue
  src/core/components/table/CoachList.vue
Labels: dev

#1889 COM-3564: can access history + boyscout
  src/core/components/courses/ProfileOrganization.vue
  src/core/components/courses/TraineeContainer.vue
  src/core/helpers/ability.js
Labels: dev

#1892 MES 17/10/23
  src/core/components/courses/ProfileOrganization.vue
  src/core/components/courses/SlotContainer.vue
  src/core/components/courses/TraineeContainer.vue
  src/core/components/courses/TraineeTable.vue
  src/core/components/form/DateInput.vue
  src/core/components/form/DateRange.vue
  src/core/components/learners/ProfileCourses.vue
  src/core/components/table/CoachCreationModal.vue
  src/core/components/table/CoachList.vue
  src/core/composables/companiesCoursesLink.js
  src/core/composables/courseFilters.js
  src/core/composables/courses.js
  src/core/data/constants.js
  src/core/helpers/ability.js
  src/core/helpers/courses.js
  src/core/pages/signin/Authenticate.vue
  src/index.template.html
  src/modules/client/pages/ni/billing/ToBill.vue
  src/modules/client/pages/ni/courses/BlendedCourseProfile.vue
  src/modules/vendor/components/billing/CourseBillingCard.vue
  src/modules/vendor/components/courses/CourseCreationModal.vue
  src/modules/vendor/components/holdings/ProfileInfo.vue
  src/modules/vendor/pages/ni/management/BlendedCourseProfile.vue
  src/modules/vendor/pages/ni/management/BlendedCoursesDirectory.vue
  test/cypress/integration/ni/billing/toBill.spec.js
Labels: staging

#1893 COM-3592: fix bug on course creation
  src/modules/vendor/components/courses/CourseCreationModal.vue
Labels: bug

#1894 COM-3581: can get attendances
  src/core/components/courses/ElearningFollowUpTable.vue
  src/core/components/courses/ProfileOrganization.vue
  src/core/components/courses/ProfileTraineeFollowUp.vue
  src/core/components/courses/TraineeTable.vue
  src/core/components/learners/ProfileCourses.vue
  src/core/components/table/AttendanceTable/Composables/Attendances.js
  src/core/components/table/AttendanceTable/index.vue
  src/core/composables/courses.js
  src/core/composables/learnersEdition.js
  src/core/helpers/ability.js
  src/modules/client/pages/ni/courses/BlendedCourseProfile.vue
  src/modules/vendor/pages/ni/management/BlendedCourseProfile.vue
  src/modules/vendor/router/routes.js
Labels: dev

#1896 COM-3582: can get potential trainees
  src/core/components/table/AttendanceTable/Composables/Attendances.js
Labels: dev

#1897 COM-3601: without trainer filter works
  src/core/components/courses/CourseCell/index.vue
  src/core/composables/courseFilters.js
  src/core/data/constants.js
Labels: bug

#1898 COM-3585: can upload intra_holding attendance sheet
  src/core/components/courses/AttendanceSheetAdditionModal.vue
  src/core/components/table/AttendanceTable/Composables/AttendanceSheets.js
Labels: dev

#1899 COM-3584: can't add sheet if no companies
  src/core/components/table/AttendanceTable/Composables/AttendanceSheets.js
Labels: dev
