Repository CompaniTech/compani-webapp, pull requests merged in 2023-02, with the labels that each got.

#1758 MES 06/02
  .github/workflows/endToEnd.js.yml
  .github/workflows/lint.yml
  src/core/components/courses/SlotContainer.vue
  src/core/components/form/DateInput.vue
  src/core/components/table/AttendanceTable.vue
  src/core/composables/courseFilters.js
  src/core/data/constants.js
  src/core/helpers/dates/companiDurations.js
  src/core/helpers/dates/utils.js
  src/core/mixins/courseFiltersMixin.js
  src/core/mixins/courseTimeline.js
  src/modules/client/pages/ni/courses/BlendedCoursesDirectory.vue
  src/modules/client/router/routes.js
  src/modules/vendor/pages/ni/management/BlendedCoursesDirectory.vue
  src/modules/vendor/pages/trainers/management/BlendedCoursesDirectory.vue
  src/modules/vendor/router/routes.js
  src/store/course.js
Labels: master

#1759 COM-3333: use company field rather than trainee field
  src/core/components/table/AttendanceTable.vue
Labels: dev

#1764 Com 3392
  src/core/components/courses/TraineeAdditionModal.vue
  src/core/components/courses/TraineeContainer.vue
  src/core/composables/learners.js
Labels: dev

#1765 COM-3396 fix date time range
  src/core/components/form/DatetimeRange.vue
Labels: dev

#1766 Com 3399
  src/core/components/courses/ProfileOrganization.vue
Labels: dev

#1767 COM-3388 change filter
  src/modules/vendor/components/questionnaires/ProfileAnswers.vue
Labels: dev

#1769 COM-3400: add border and hide checkbox if no trainees
  src/core/components/table/AttendanceTable.vue
Labels: dev

#1768 Com 3393
  src/core/components/courses/TraineeAdditionModal.vue
  src/core/components/courses/TraineeContainer.vue
  src/core/composables/learners.js
Labels: dev

#1771 Fusion feature-detachment 17/02
  src/core/components/courses/LearnerCreationModal.vue
  src/core/components/courses/ProfileOrganization.vue
  src/core/components/courses/TraineeAdditionModal.vue
  src/core/components/courses/TraineeContainer.vue
  src/core/composables/learners.js
  src/core/helpers/userCompanies.js
  src/modules/client/pages/ni/auxiliaries/Directory.vue
  src/modules/client/pages/ni/courses/LearnersDirectory.vue
  src/store/userProfile.js
Labels: dev

#1775 MAJ vue-router
  package-lock.json
  package.json
  src/core/components/courses/ElearningFollowUpTable.vue
  src/core/components/courses/TraineeContainer.vue
  src/core/components/learners/ProfileCourses.vue
  src/modules/client/components/auxiliary/AuxiliaryProfileHeader.vue
  src/modules/client/components/customers/CustomerProfileHeader.vue
  src/modules/client/pages/ni/billing/Bills.vue
  src/modules/client/pages/ni/billing/ClientsBalances.vue
  src/modules/client/pages/ni/pay/ContractMonitoring.vue
  src/modules/client/router/routes.js
  src/modules/vendor/components/billing/CourseBillingCard.vue
  src/modules/vendor/components/companies/ProfileBilling.vue
  src/modules/vendor/router/routes.js
Labels: dependancies
