Repository CompaniTech/compani-webapp, pull requests merged in 2023-05, with the labels that each got.

#1806 Com 3444
  src/core/components/courses/CourseCell/index.vue
  src/core/components/courses/Trello.vue
  src/core/composables/courseFilters.js
  src/core/helpers/dates/utils.js
  src/core/mixins/courseTimeline.js
  src/modules/client/pages/ni/courses/BlendedCoursesDirectory.vue
  src/modules/vendor/pages/ni/management/BlendedCoursesDirectory.vue
  src/modules/vendor/pages/trainers/management/BlendedCoursesDirectory.vue
Labels: dev

#1807 COM-3453: empty uploader for media
  src/core/components/courses/TrainingContractContainer.vue
  src/core/components/form/FileUploader.vue
Labels: bug

#1808 Com 3452
  src/core/components/courses/CourseCell/index.vue
  src/core/components/courses/Trello.vue
  src/core/composables/courseFilters.js
  src/modules/client/pages/ni/courses/BlendedCoursesDirectory.vue
  src/modules/vendor/pages/ni/management/BlendedCoursesDirectory.vue
  src/modules/vendor/pages/trainers/management/BlendedCoursesDirectory.vue
Labels: dev

#1809 Com 3457
  src/modules/client/mixins/payMixin.js
Labels: dev

#1811 MES 23/05
  package-lock.json
  package.json
  quasar.conf.js
  src/boot/.gitkeep
  src/boot/vue-analytics.js
  src/core/components/courses/CourseCell.vue
  src/core/components/courses/CourseCell/ForthcomingSection.vue
  src/core/components/courses/CourseCell/InProgressSection.vue
  src/core/components/courses/CourseCell/index.vue
  src/core/components/courses/CourseContainer.vue
  src/core/components/courses/TrainingContractContainer.vue
  src/core/components/courses/TrainingContractTable.vue
  src/core/components/courses/Trello.vue
  src/core/components/form/FileUploader.vue
  src/core/composables/courseFilters.js
  src/core/helpers/dates/utils.js
  src/core/mixins/courseTimeline.js
  src/css/course.sass
  src/modules/client/mixins/payMixin.js
  src/modules/client/pages/ni/courses/BlendedCoursesDirectory.vue
  src/modules/vendor/pages/ni/management/BlendedCoursesDirectory.vue
  src/modules/vendor/pages/trainers/management/BlendedCoursesDirectory.vue
  src/store/course.js
Labels: master

#1813 COM-3464 - reset completedCourseList on refresh
  src/core/components/courses/Trello.vue
  src/modules/vendor/pages/ni/management/BlendedCoursesDirectory.vue
Labels: bug, dev

#1816 COM-3447 - update mongo version in test workflow
  .github/workflows/endToEnd.js.yml
Labels: dev, tests

#1817 COM-3461: display holding profile
  src/core/api/Companies.js
  src/core/api/Holdings.js
  src/core/components/table/ResponsiveTable.vue
  src/core/helpers/rbac.js
  src/modules/vendor/components/holdings/ProfileInfo.vue
  src/modules/vendor/pages/ni/users/holdings/HoldingProfile.vue
  src/modules/vendor/pages/ni/users/holdings/HoldingsDirectory.vue
  src/modules/vendor/router/routes.js
  src/modules/vendor/store/holding.js
  src/store/index.js
Labels: dev
