Repository CompaniTech/compani-webapp, pull requests merged in 2024-01, with the labels that each got.

#1928 COM-3631: a course can have certifying tests
  src/core/components/courses/ProfileOrganization.vue
  src/core/helpers/ability.js
  src/modules/vendor/components/courses/CourseCreationModal.vue
  src/modules/vendor/pages/ni/management/BlendedCoursesDirectory.vue
Labels: dev

#1932 fix bug on creation
  src/modules/vendor/pages/ni/management/BlendedCoursesDirectory.vue
Labels: dev

#1933 COM-3633: hide button when no trainees
  src/core/components/courses/TraineeContainer.vue
Labels: bug

#1934 MES - 22/01/2024
  src/core/api/TrainerMissions.js
  src/core/components/courses/CertificationsUpdateModal.vue
  src/core/components/courses/CourseCell/index.vue
  src/core/components/courses/ProfileOrganization.vue
  src/core/components/courses/TraineeContainer.vue
  src/core/components/courses/TraineeTable.vue
  src/core/components/courses/TrainerMissionCreationModal.vue
  src/core/components/courses/TrainerMissionTable.vue
  src/core/components/courses/UserAdditionModal.vue
  src/core/components/table/ExpandingTable.vue
  src/core/composables/courseFilters.js
  src/core/composables/learnersCreation.js
  src/core/helpers/ability.js
  src/modules/vendor/components/courses/CourseCreationModal.vue
  src/modules/vendor/components/trainers/ProfileContract.vue
  src/modules/vendor/pages/ni/management/BlendedCoursesDirectory.vue
  src/modules/vendor/pages/ni/users/trainers/TrainerProfile.vue
  src/modules/vendor/pages/trainers/management/BlendedCoursesDirectory.vue
  src/modules/vendor/router/routes.js
  src/store/course.js
Labels: master

#1935 COM-3646: fix bug
  src/core/components/courses/UserAdditionModal.vue
Labels: bug

#1931 COM-3634: can generate trainer mission
  src/core/components/courses/TrainerMissionCreationModal.vue
  src/core/components/courses/TrainerMissionInfosModal.vue
  src/core/components/courses/TrainingContractInfosModal.vue
  src/core/composables/courseDocumentInfosModal.js
  src/core/data/constants.js
  src/modules/vendor/components/trainers/ProfileContract.vue
Labels: dev

#1936 COM-3630: can cancel trainer mission
  src/core/api/TrainerMissions.js
  src/core/components/courses/TrainerMissionCreationModal.vue
  src/core/components/courses/TrainerMissionTable.vue
  src/modules/vendor/components/trainers/ProfileContract.vue
Labels: dev
