Repository CompaniTech/compani-webapp, pull requests merged in 2024-12, with the labels that each got.

#2088 Com 3845
  src/core/api/AttendanceSheets.js
  src/core/components/courses/AttendanceSheetEditionModal.vue
  src/core/components/table/AttendanceTable/Composables/AttendanceSheets.js
  src/core/components/table/AttendanceTable/index.vue
Labels: dev

#2092 COM-3861: use ref
  src/core/components/courses/CourseContainer.vue
Labels: bug

#2095 COM-3851: disable uncomplete attendance sheets
  src/core/components/table/AttendanceTable/Composables/AttendanceSheets.js
  src/core/components/table/AttendanceTable/index.vue
Labels: dev

#2096 Com 3865
  package-lock.json
  package.json
  quasar.conf.js
Labels: dependencies
