Repository CompaniTech/compani-webapp, pull requests merged in 2024-07, with the labels that each got.

#2016 MES 10/07/2024
  src/core/components/courses/SurveyChart.vue
  src/modules/vendor/components/programs/cards/templates/OpenQuestion.vue
  src/modules/vendor/components/programs/cards/templates/OrderTheSequence.vue
  src/modules/vendor/components/questionnaires/ProfileAnswers.vue
  src/modules/vendor/pages/ni/config/MainConfig.vue
Labels: master

#2019 COM-3754 - update mongodb version in ci
  .github/workflows/endToEnd.js.yml
Labels: dev, tests

#2020 Com 3734
  src/core/composables/learnerDirectory.js
  src/core/mixins/learnerDirectoryMixin.js
  src/modules/client/pages/ni/courses/LearnersDirectory.vue
  src/modules/vendor/pages/ni/users/learners/LearnersDirectory.vue
Labels: dev

#2021 COM-3747: display companies count
  src/modules/vendor/pages/ni/users/holdings/HoldingsDirectory.vue
Labels: dev

#2022 COM-3748: display holding name
  src/core/composables/learnerDirectory.js
  src/core/composables/learnersCreation.js
  src/modules/vendor/pages/ni/users/companies/CompaniesDirectory.vue
Labels: dev
