Repository CompaniTech/compani-webapp, pull requests merged in 2024-04, with the labels that each got.

#1983 COM-3685: update html-loader
  package-lock.json
  package.json
Labels: dependencies

#1984 COM-3683: increase font size
  src/core/components/Rating.vue
  src/core/components/questionnaires/cards/MetaInfos.vue
  src/core/components/questionnaires/cards/Transition.vue
  src/css/app.sass
  src/css/card.sass
  src/css/questionnaire.sass
Labels: dev

#1985 Com 3688
  package-lock.json
  package.json
Labels: dependencies

#1986 COM-3687: join both questionnaires
  src/core/api/Questionnaires.js
  src/core/components/courses/ProfileTraineeFollowUp.vue
  src/core/components/courses/QuestionnaireQRCodeCell.vue
  src/core/components/questionnaires/cards/MetaInfos.vue
  src/core/helpers/courses.js
  src/modules/notLogged/pages/QuestionnaireForm.vue
  src/router/routes.js
Labels: dev

#1987 Com 3694
  src/core/components/courses/CourseCell/index.vue
  src/core/components/courses/ProfileTraineeFollowUp.vue
  src/core/components/questionnaires/cards/MetaInfos.vue
  src/core/composables/courseFilters.js
  src/modules/client/pages/ni/courses/BlendedCourseProfile.vue
  src/modules/vendor/pages/ni/management/BlendedCoursesDirectory.vue
  src/store/course.js
Labels: dev

#1990 MES 23/04/2024
  package-lock.json
  package.json
  src/core/api/Questionnaires.js
  src/core/components/Rating.vue
  src/core/components/courses/CourseCell/index.vue
  src/core/components/courses/ProfileTraineeFollowUp.vue
  src/core/components/courses/QuestionnaireQRCodeCell.vue
  src/core/components/questionnaires/cards/MetaInfos.vue
  src/core/components/questionnaires/cards/Survey.vue
  src/core/components/questionnaires/cards/Transition.vue
  src/core/composables/courseFilters.js
  src/core/helpers/courses.js
  src/css/app.sass
  src/css/card.sass
  src/css/questionnaire.sass
  src/modules/client/pages/ni/courses/BlendedCourseProfile.vue
  src/modules/notLogged/pages/QuestionnaireForm.vue
  src/modules/vendor/pages/ni/management/BlendedCoursesDirectory.vue
  src/router/routes.js
  src/store/course.js
Labels: staging

#1988 Com 3695
  src/modules/vendor/components/programs/cards/templates/FillTheGaps.vue
  src/modules/vendor/components/programs/cards/templates/Flashcard.vue
  src/modules/vendor/components/programs/cards/templates/MultipleChoiceQuestion.vue
  src/modules/vendor/composables/CardTemplate.js
Labels: dev

#1991 COM-3697: update chart.js
  package-lock.json
  package.json
  src/core/components/charts/LineChart.vue
  src/core/components/courses/ProfileFollowUp.vue
Labels: dependencies

#1989 Com 3693
  src/core/api/AdministrativeDocuments.js
  src/core/api/Authentication.js
  src/core/api/Contracts.js
  src/core/api/CustomerNotes.js
  src/core/api/CustomerPartners.js
  src/core/api/Esign.js
  src/core/api/InternalHours.js
  src/core/api/Partners.js
  src/core/api/Pay.js
  src/core/api/PayDocuments.js
  src/core/api/Sms.js
  src/core/api/Stats.js
  src/core/api/Users.js
  src/core/data/constants.js
  src/core/data/euSpace.js
  src/core/data/user.js
  src/core/helpers/rbac.js
  src/modules/client/components/auxiliary/AuxiliaryCreationModal.vue
  src/modules/client/components/auxiliary/AuxiliaryProfileHeader.vue
  src/modules/client/components/auxiliary/ProfileContracts.vue
  src/modules/client/components/auxiliary/ProfileInfo.vue
  src/modules/client/components/auxiliary/ProfilePay.vue
  src/modules/client/components/config/AdministrativeDocumentCreationModal.vue
  src/modules/client/components/config/InternalHourCreationModal.vue
  src/modules/client/components/config/SectorCreationModal.vue
  src/modules/client/components/config/SectorEditionModal.vue
  src/modules/client/components/contracts/ContractCreationModal.vue
  src/modules/client/components/contracts/ContractEndingModal.vue
  src/modules/client/components/contracts/ContractsCell.vue
  src/modules/client/components/contracts/VersionCreationModal.vue
  src/modules/client/components/contracts/VersionEditionModal.vue
  src/modules/client/components/customers/ProfileFollowUp.vue
  src/modules/client/components/customers/infos/CustomerNoteCreationModal.vue
  src/modules/client/components/customers/infos/CustomerNoteEditionModal.vue
  src/modules/client/components/customers/infos/CustomerNoteHistory.vue
  src/modules/client/components/customers/infos/CustomerNoteHistoryContainer.vue
  src/modules/client/components/customers/infos/CustomerPartnerCreationModal.vue
  src/modules/client/components/pay/PayDocumentCreationModal.vue
  src/modules/client/components/table/CustomerNoteCell.vue
  src/modules/client/components/table/CustomerNotesContainer.vue
  src/modules/client/helpers/getUserStartDate.js
  src/modules/client/helpers/tags.js
  src/modules/client/helpers/userProfileValidation.js
  src/modules/client/mixins/contractMixin.js
  src/modules/client/mixins/customerMixin.js
  src/modules/client/mixins/menuItemsMixin.js
  src/modules/client/mixins/planningModalMixin.js
  src/modules/client/pages/auxiliaries/administrative/Contracts.vue
  src/modules/client/pages/auxiliaries/administrative/Documents.vue
  src/modules/client/pages/auxiliaries/administrative/Info.vue
  src/modules/client/pages/auxiliaries/administrative/Salaries.vue
  src/modules/client/pages/auxiliaries/customers/AuxiliaryCustomersDirectory.vue
  src/modules/client/pages/auxiliaries/customers/CustomerInfo.vue
  src/modules/client/pages/ni/auxiliaries/AuxiliaryProfile.vue
  src/modules/client/pages/ni/auxiliaries/Directory.vue
  src/modules/client/pages/ni/config/RhConfig.vue
  src/modules/client/pages/ni/config/TagConfig.vue
  src/modules/client/pages/ni/customers/CustomerProfile.vue
  src/modules/client/router/routes.js
  test/cypress/integration/authenticate.spec.js
Labels: dev, compani-outils
