Repository CompaniTech/compani-webapp, pull requests merged in 2024-05, with the labels that each got.

#1996 Com 3686
  package-lock.json
  package.json
  quasar.conf.js
  src/boot/localEntry.js
Labels: dependencies

#1998 COM-3708 : display message when there is no card in questionnaire
  src/modules/notLogged/pages/QuestionnaireForm.vue
Labels: bug

#1999 COM-3689 : remove useless temporary code
  src/router/routes.js
Labels: dev
