Repository CompaniTech/compani-webapp, pull requests merged in 2024-09, with the labels that each got.

#2047 COM-3780: migrate file in vue3
  src/core/components/PictureUploader.vue
  src/core/components/courses/AttendanceSheetAdditionModal.vue
  src/core/components/table/TraineeAttendanceCreationModal.vue
  src/modules/vendor/components/billing/CourseFundingOrganisationCreationModal.vue
  src/modules/vendor/components/programs/cards/CardEdition.vue
Labels: dev

#2044 COM-3759 : refacto qcu
  src/core/data/constants.js
  src/modules/vendor/components/programs/cards/templates/MultipleChoiceQuestion.vue
  src/modules/vendor/components/programs/cards/templates/SingleChoiceQuestion.vue
Labels: dev

#2045 COM-3774: add holding name in creation user select
  src/core/components/courses/LearnerCreationModal.vue
  src/core/components/courses/TraineeContainer.vue
  src/modules/vendor/pages/ni/users/learners/LearnersDirectory.vue
Labels: dev

#2046 COM-3750: can create company on holding profile
  src/core/components/courses/CompanyAdditionModal.vue
  src/core/components/form/CompanySelect.vue
  src/modules/vendor/components/companies/CompanyCreationModal.vue
  src/modules/vendor/components/holdings/ProfileInfo.vue
Labels: dev

#2048 COM-3783: can add default description on creation
  src/core/components/courses/ProfileBilling.vue
  src/modules/vendor/components/billing/CourseBillCreationModal.vue
  src/modules/vendor/components/billing/CourseBillingCard.vue
Labels: dev

#2055 Com 3784
  src/modules/vendor/components/programs/cards/templates/TitleText.vue
Labels: dev

#2056 COM-3774: fix company options
  src/core/components/courses/TraineeContainer.vue
Labels: bug

#2051 Com 3782
  src/modules/vendor/components/programs/cards/templates/Transition.vue
Labels: dev

#2049 Com 3781
  src/modules/vendor/components/programs/cards/templates/QuestionAnswer.vue
Labels: dev

#2058 Com 3767
  src/core/components/courses/ELearningIndicator.vue
  src/core/components/courses/Indicator.vue
  src/core/components/courses/ProfileFollowUp.vue
  src/core/components/learners/ProfileCourses.vue
  src/core/components/table/AttendanceTable/index.vue
  src/modules/client/pages/ni/courses/Dashboard.vue
Labels: dev

#2059 Com 3785
  src/modules/vendor/components/programs/cards/templates/TextMedia.vue
  src/modules/vendor/composables/CardTemplate.js
Labels: dev

#2060 Com 3787
  src/modules/vendor/components/programs/cards/templates/TextMedia.vue
  src/modules/vendor/components/programs/cards/templates/TitleTextMedia.vue
Labels: dev

#2062 MES 17/09/2024
  src/core/components/courses/ELearningIndicator.vue
  src/core/components/courses/Indicator.vue
  src/core/components/courses/OpenQuestionChart.vue
  src/core/components/courses/ProfileFollowUp.vue
  src/core/components/courses/TraineeContainer.vue
  src/core/components/learners/ProfileCourses.vue
  src/core/components/table/AttendanceTable/index.vue
  src/modules/client/pages/ni/courses/Dashboard.vue
  src/modules/vendor/components/programs/cards/templates/QuestionAnswer.vue
  src/modules/vendor/components/programs/cards/templates/TextMedia.vue
  src/modules/vendor/components/programs/cards/templates/TitleText.vue
  src/modules/vendor/components/programs/cards/templates/TitleTextMedia.vue
  src/modules/vendor/components/programs/cards/templates/Transition.vue
  src/modules/vendor/composables/CardTemplate.js
Labels: master

#2063 COM-3789: on TraineeContainer change navigation with router-link
  src/core/components/courses/TraineeContainer.vue
Labels: dev

#2061 Com 3765
  src/core/components/courses/Indicator.vue
  src/core/mixins/questionnaireAnswersMixin.js
  src/modules/vendor/components/courses/ProfileQuestionnaires.vue
  src/modules/vendor/components/questionnaires/ProfileAnswers.vue
  src/modules/vendor/components/questionnaires/QuestionnaireAnswersContainer.vue
  src/modules/vendor/composables/QuestionnaireAnswers.js
Labels: dev

#2065 Com 3790
  src/core/data/constants.js
  src/modules/vendor/components/programs/cards/templates/MultipleChoiceQuestion.vue
  src/modules/vendor/components/programs/cards/templates/OpenQuestion.vue
  src/modules/vendor/components/programs/cards/templates/OrderTheSequence.vue
  src/modules/vendor/components/programs/cards/templates/QuestionAnswer.vue
  src/modules/vendor/components/programs/cards/templates/SingleChoiceQuestion.vue
  src/modules/vendor/components/programs/cards/templates/Survey.vue
  src/modules/vendor/components/programs/cards/templates/TitleText.vue
  src/modules/vendor/components/programs/cards/templates/TitleTextMedia.vue
  src/modules/vendor/composables/CardTemplate.js
  src/modules/vendor/mixins/templateMixin.js
Labels: dev

#2064 COM-3778: refacto fill the gap
  src/core/data/constants.js
  src/core/helpers/vuelidateCustomVal.js
  src/modules/vendor/components/programs/cards/templates/FillTheGaps.vue
  src/modules/vendor/components/programs/cards/templates/MultipleChoiceQuestion.vue
  src/modules/vendor/composables/CardTemplate.js
Labels: dev

#2066 COM-3795: display holding in billing creation and edition
  src/core/components/courses/ProfileBilling.vue
  src/modules/vendor/components/billing/CompaniesSelectionModal.vue
  src/modules/vendor/components/billing/CourseBillCreationModal.vue
  src/modules/vendor/components/billing/PayerEditionModal.vue
Labels: dev

#2067 COM-3801: remove yarn
  package.json
Labels: bug
