Repository CompaniTech/compani-webapp, pull requests merged in 2024-03, with the labels that each got.

#1956 COM-3662 - reset filters on arrival at BlendedCourseDirectory (clientInterface)
  src/modules/client/pages/ni/courses/BlendedCoursesDirectory.vue
  src/modules/vendor/pages/ni/management/BlendedCoursesDirectory.vue
Labels: dev

#1958 MES 06-03-2024
  package-lock.json
  package.json
  quasar.extensions.json
  src/core/components/ProfileHeader.vue
  src/core/components/SecondaryButton.vue
  src/core/components/courses/CourseCell/index.vue
  src/core/components/courses/InterlocutorCell.vue
  src/core/components/courses/InterlocutorModal.vue
  src/core/components/courses/ProfileOrganization.vue
  src/core/components/courses/TraineeContainer.vue
  src/core/components/courses/TrainingContractContainer.vue
  src/core/composables/courseFilters.js
  src/core/composables/courses.js
  src/core/composables/learnersCreation.js
  src/core/data/constants.js
  src/core/helpers/ability.js
  src/modules/client/pages/ni/courses/BlendedCoursesDirectory.vue
  src/modules/client/pages/ni/courses/LearnerProfile.vue
  src/modules/client/pages/ni/courses/LearnersDirectory.vue
  src/modules/vendor/components/courses/CourseCreationModal.vue
  src/modules/vendor/pages/ni/management/BlendedCoursesDirectory.vue
  src/modules/vendor/pages/ni/pedagogy/ProgramProfile.vue
  src/modules/vendor/pages/ni/users/companies/CompanyProfile.vue
  src/modules/vendor/pages/ni/users/learners/LearnerProfile.vue
  src/modules/vendor/pages/ni/users/trainers/TrainerProfile.vue
  src/modules/vendor/pages/trainers/management/BlendedCoursesDirectory.vue
  src/store/course.js
Labels: staging

#1957 COM-3663 - rof can download completionC in pdf
  src/core/components/courses/ProfileTraineeFollowUp.vue
  src/css/modal.sass
Labels: dev

#1959 COM-3665 : add hydratation flag to remove warning
  quasar.conf.js
Labels: dev

#1963 Com 3669
  src/modules/vendor/pages/ni/pedagogy/QuestionnairesDirectory.vue
Labels: dev

#1964 COM-3673: sort coursebills
  src/modules/vendor/components/companies/ProfileBilling.vue
Labels: dev

#1961 Com 3668
  src/core/components/Rating.vue
  src/core/components/courses/SurveyChart.vue
  src/core/components/questionnaires/cards/Survey.vue
  src/modules/vendor/components/programs/cards/templates/Survey.vue
  src/modules/vendor/composables/CardTemplate.js
Labels: dev

#1965 COM-3666-2: fix bug
  src/modules/vendor/components/companies/ProfileBilling.vue
Labels: bug

#1968 MES 19/03/2024
  quasar.conf.js
  src/core/components/Rating.vue
  src/core/components/courses/ProfileTraineeFollowUp.vue
  src/core/components/courses/SurveyChart.vue
  src/core/components/questionnaires/cards/Survey.vue
  src/core/helpers/ability.js
  src/css/modal.sass
  src/modules/client/pages/ni/config/CompanyConfig.vue
  src/modules/vendor/components/companies/ProfileBilling.vue
  src/modules/vendor/components/programs/cards/templates/Survey.vue
  src/modules/vendor/composables/CardTemplate.js
  src/modules/vendor/pages/ni/pedagogy/QuestionnairesDirectory.vue
Labels: staging

#1969 COM-3666: fix label
  src/core/components/courses/ProfileOrganization.vue
Labels: bug

#1970 MES 19/03/2024 - 2
  src/core/components/courses/ProfileOrganization.vue
Labels: staging

#1966 Com 3670
  src/core/components/questionnaires/QuestionnaireContainer.vue
  src/core/data/constants.js
  src/modules/vendor/components/programs/QuestionnaireCreationModal.vue
  src/modules/vendor/pages/ni/pedagogy/ProgramProfile.vue
  src/modules/vendor/pages/ni/pedagogy/QuestionnairesDirectory.vue
  src/modules/vendor/router/routes.js
Labels: dev

#1955 Com 3664
  src/assets/gauge-needle.svg
  src/core/api/Companies.js
  src/core/api/Contracts.js
  src/core/api/Customers.js
  src/core/api/Events.js
  src/core/api/FinalPay.js
  src/core/api/PartnerOrganizations.js
  src/core/api/Pay.js
  src/core/api/Repetitions.js
  src/core/api/Stats.js
  src/core/helpers/rbac.js
  src/core/mixins/partnerOrganizationMixin.js
  src/modules/client/components/Gauge.vue
  src/modules/client/components/customers/EventConflictModal.vue
  src/modules/client/components/customers/PartnerCreationModal.vue
  src/modules/client/components/customers/PartnerEditionModal.vue
  src/modules/client/components/customers/PartnerOrganizationCreationModal.vue
  src/modules/client/components/customers/SubscriptionCell.vue
  src/modules/client/components/pay/PaySurchargeDetailsModal.vue
  src/modules/client/components/planning/Agenda.vue
  src/modules/client/components/planning/RepetitionCell.vue
  src/modules/client/components/planning/RepetitionDeletionConfirmationModal.vue
  src/modules/client/components/planning/RepetitionDeletionModal.vue
  src/modules/client/mixins/editableTdMixin.js
  src/modules/client/mixins/menuItemsMixin.js
  src/modules/client/mixins/payMixin.js
  src/modules/client/pages/auxiliaries/planning/AuxiliaryAgenda.vue
  src/modules/client/pages/auxiliaries/teams/TeamsDirectory.vue
  src/modules/client/pages/customers/Contact.vue
  src/modules/client/pages/customers/CustomerAgenda.vue
  src/modules/client/pages/customers/Subscriptions.vue
  src/modules/client/pages/ni/auxiliaries/Dashboard.vue
  src/modules/client/pages/ni/auxiliaries/StaffRegister.vue
  src/modules/client/pages/ni/customers/CustomersFundingsMonitoring.vue
  src/modules/client/pages/ni/customers/PartnerOrganizationProfile.vue
  src/modules/client/pages/ni/customers/PartnerOrganizationsDirectory.vue
  src/modules/client/pages/ni/pay/Absences.vue
  src/modules/client/pages/ni/pay/ContractEnds.vue
  src/modules/client/pages/ni/pay/ContractMonitoring.vue
  src/modules/client/pages/ni/pay/ToPay.vue
  src/modules/client/pages/ni/planning/RepetitionsPlanning.vue
  src/modules/client/router/routes.js
  test/cypress/integration/authenticate.spec.js
  test/cypress/integration/auxiliary/planning/auxiliaryAgenda.spec.js
  test/cypress/integration/customer/agenda.spec.js
  test/cypress/integration/customer/contact.spec.js
  test/cypress/integration/customer/subscription.spec.js
  test/cypress/integration/ni/planning/auxiliaryPlanning.spec.js
Labels: compani-outils

#1967 COM-3671: can display course bills
  src/core/components/courseBilling/CourseBillingInfos.vue
  src/core/helpers/ability.js
  src/core/helpers/rbac.js
  src/modules/client/pages/ni/courses/BillingProfile.vue
  src/modules/client/pages/ni/courses/BlendedCourseProfile.vue
  src/modules/vendor/components/companies/ProfileBilling.vue
Labels: dev

#1973 MES 27/03/2024
  src/assets/gauge-needle.svg
  src/core/api/Companies.js
  src/core/api/Contracts.js
  src/core/api/Customers.js
  src/core/api/Events.js
  src/core/api/FinalPay.js
  src/core/api/PartnerOrganizations.js
  src/core/api/Pay.js
  src/core/api/Repetitions.js
  src/core/api/Stats.js
  src/core/components/courseBilling/CourseBillingInfos.vue
  src/core/components/questionnaires/QuestionnaireContainer.vue
  src/core/data/constants.js
  src/core/helpers/ability.js
  src/core/helpers/rbac.js
  src/core/mixins/partnerOrganizationMixin.js
  src/modules/client/components/Gauge.vue
  src/modules/client/components/customers/EventConflictModal.vue
  src/modules/client/components/customers/PartnerCreationModal.vue
  src/modules/client/components/customers/PartnerEditionModal.vue
  src/modules/client/components/customers/PartnerOrganizationCreationModal.vue
  src/modules/client/components/customers/SubscriptionCell.vue
  src/modules/client/components/pay/PaySurchargeDetailsModal.vue
  src/modules/client/components/planning/Agenda.vue
  src/modules/client/components/planning/RepetitionCell.vue
  src/modules/client/components/planning/RepetitionDeletionConfirmationModal.vue
  src/modules/client/components/planning/RepetitionDeletionModal.vue
  src/modules/client/mixins/editableTdMixin.js
  src/modules/client/mixins/menuItemsMixin.js
  src/modules/client/mixins/payMixin.js
  src/modules/client/pages/auxiliaries/planning/AuxiliaryAgenda.vue
  src/modules/client/pages/auxiliaries/teams/TeamsDirectory.vue
  src/modules/client/pages/customers/Contact.vue
  src/modules/client/pages/customers/CustomerAgenda.vue
  src/modules/client/pages/customers/Subscriptions.vue
  src/modules/client/pages/ni/auxiliaries/Dashboard.vue
  src/modules/client/pages/ni/auxiliaries/StaffRegister.vue
  src/modules/client/pages/ni/courses/BillingProfile.vue
  src/modules/client/pages/ni/courses/BlendedCourseProfile.vue
  src/modules/client/pages/ni/customers/CustomersFundingsMonitoring.vue
  src/modules/client/pages/ni/customers/PartnerOrganizationProfile.vue
  src/modules/client/pages/ni/customers/PartnerOrganizationsDirectory.vue
  src/modules/client/pages/ni/pay/Absences.vue
  src/modules/client/pages/ni/pay/ContractEnds.vue
  src/modules/client/pages/ni/pay/ContractMonitoring.vue
  src/modules/client/pages/ni/pay/ToPay.vue
  src/modules/client/pages/ni/planning/RepetitionsPlanning.vue
  src/modules/client/router/routes.js
  src/modules/vendor/components/companies/ProfileBilling.vue
  src/modules/vendor/components/programs/QuestionnaireCreationModal.vue
  src/modules/vendor/components/programs/cards/templates/Survey.vue
  src/modules/vendor/pages/ni/pedagogy/ProgramProfile.vue
  src/modules/vendor/pages/ni/pedagogy/QuestionnairesDirectory.vue
  src/modules/vendor/router/routes.js
  test/cypress/integration/authenticate.spec.js
  test/cypress/integration/auxiliary/planning/auxiliaryAgenda.spec.js
  test/cypress/integration/customer/agenda.spec.js
  test/cypress/integration/customer/contact.spec.js
  test/cypress/integration/customer/subscription.spec.js
  test/cypress/integration/ni/planning/auxiliaryPlanning.spec.js
Labels: staging

#1972 Com 3675
  src/core/components/Rating.vue
  src/core/components/questionnaires/cards/Survey.vue
Labels: dev
