Repository CompaniTech/compani-webapp, pull requests merged in 2024-02, with the labels that each got.

#1937 COM-3607: can update trainer with trainer mission
  src/core/components/courses/ProfileOrganization.vue
Labels: dev

#1941 COM-3645 - display salesRepresentative on ContactProfile
  src/modules/client/pages/ni/courses/ContactProfile.vue
Labels: dev

#1940 COM-3654: rof can have trainer mission
  src/core/components/courses/TrainerMissionCreationModal.vue
  src/modules/vendor/components/trainers/ProfileContract.vue
  src/modules/vendor/pages/ni/users/trainers/TrainersDirectory.vue
Labels: dev

#1945 COM-3634: fix bug
  src/core/components/courses/TrainerMissionInfosModal.vue
Labels: bug

#1946 MES 07/02/2024 - 2
  src/core/components/courses/TrainerMissionInfosModal.vue
Labels: staging

#1943 COM-3659: can see holding trainees
  src/core/composables/learnersCreation.js
  src/modules/client/pages/ni/courses/LearnersDirectory.vue
Labels: dev

#1942 Com 3651
  src/modules/vendor/components/courses/CourseCreationModal.vue
  src/modules/vendor/pages/ni/management/BlendedCoursesDirectory.vue
Labels: dev

#1947 COM-3517: can create trainee
  src/modules/client/pages/ni/courses/LearnersDirectory.vue
Labels: dev

#1948 Com 3652
  src/core/components/SecondaryButton.vue
  src/core/components/courses/InterlocutorModal.vue
  src/core/components/courses/ProfileOrganization.vue
  src/core/helpers/ability.js
Labels: dev

#1950 Com 3655
  src/core/components/ProfileHeader.vue
  src/core/components/courses/CourseCell/index.vue
  src/core/composables/courseFilters.js
  src/core/composables/courses.js
  src/core/data/constants.js
  src/modules/vendor/pages/ni/management/BlendedCoursesDirectory.vue
  src/store/course.js
Labels: dev

#1951 COM-3656 - fix bug at company's edition
  src/modules/client/pages/ni/courses/LearnerProfile.vue
  src/modules/vendor/pages/ni/pedagogy/ProgramProfile.vue
  src/modules/vendor/pages/ni/users/companies/CompanyProfile.vue
  src/modules/vendor/pages/ni/users/learners/LearnerProfile.vue
  src/modules/vendor/pages/ni/users/trainers/TrainerProfile.vue
Labels: dev

#1952 Com 3520
  src/core/components/courses/TraineeContainer.vue
  src/core/components/courses/TrainingContractContainer.vue
Labels: dev

#1953 COM-3518 : can remove trainer from course
  src/core/components/courses/InterlocutorCell.vue
  src/core/components/courses/InterlocutorModal.vue
  src/core/components/courses/ProfileOrganization.vue
Labels: dev

#1954 Com 3662
  src/core/composables/courseFilters.js
  src/modules/vendor/pages/ni/management/BlendedCoursesDirectory.vue
  src/modules/vendor/pages/trainers/management/BlendedCoursesDirectory.vue
  src/store/course.js
Labels: dev
