Repository CompaniTech/compani-webapp, pull requests merged in 2025-04, with the labels that each got.

#2146 Com 3950
  .github/workflows/endToEnd.js.yml
  quasar.conf.js
  src/core/components/courses/TrainerMissionCreationModal.vue
  src/core/composables/courseCreation.js
  src/core/composables/courseFilters.js
  src/core/data/constants.js
  src/core/helpers/rbac.js
  src/modules/vendor/components/courses/CourseCreationModal.vue
  src/modules/vendor/components/trainers/ProfileContract.vue
  src/modules/vendor/mixins/menuItemsMixin.js
  src/modules/vendor/pages/ni/management/BlendedCoursesDirectory.vue
  src/modules/vendor/pages/ni/management/SingleCourseDirectory.vue
  src/modules/vendor/router/routes.js
  src/store/course.js
Labels: dev

#2151 COM-3960: hide useless sections
  .github/workflows/endToEnd.js.yml
  src/core/components/courses/ProfileOrganization.vue
  src/core/components/courses/ProfileTraineeFollowUp.vue
  src/core/helpers/ability.js
Labels: dev

#2154 COM-3958: display error message
  src/core/components/courses/SlotContainer.vue
  src/core/components/courses/TraineeTable.vue
Labels: bug

#2156 fusion de branche Feature single
  .github/workflows/endToEnd.js.yml
  quasar.conf.js
  src/core/components/courses/AttendanceSheetAdditionModal.vue
  src/core/components/courses/ProfileBilling.vue
  src/core/components/courses/ProfileOrganization.vue
  src/core/components/courses/ProfileTraineeFollowUp.vue
  src/core/components/courses/TraineeContainer.vue
  src/core/components/courses/TraineeTable.vue
  src/core/components/courses/TrainerMissionCreationModal.vue
  src/core/components/table/AttendanceTable/Composables/AttendanceSheets.js
  src/core/components/table/AttendanceTable/index.vue
  src/core/composables/courseCreation.js
  src/core/composables/courseFilters.js
  src/core/composables/courses.js
  src/core/data/constants.js
  src/core/helpers/ability.js
  src/core/helpers/rbac.js
  src/modules/vendor/components/billing/CourseBillCreationModal.vue
  src/modules/vendor/components/billing/CourseBillValidationModal.vue
  src/modules/vendor/components/billing/CourseBillingCard.vue
  src/modules/vendor/components/billing/CourseFeeEditionModal.vue
  src/modules/vendor/components/courses/CourseCreationModal.vue
  src/modules/vendor/components/trainers/ProfileContract.vue
  src/modules/vendor/mixins/menuItemsMixin.js
  src/modules/vendor/pages/ni/management/BlendedCoursesDirectory.vue
  src/modules/vendor/pages/ni/management/SingleCourseDirectory.vue
  src/modules/vendor/router/routes.js
  src/store/course.js
Labels: merge-feature

#2157 MES 15/04
  .github/workflows/endToEnd.js.yml
  package-lock.json
  package.json
  quasar.conf.js
  src/core/api/CompletionCertificates.js
  src/core/components/courses/AttendanceSheetAdditionModal.vue
  src/core/components/courses/ElearningFollowUpTable.vue
  src/core/components/courses/InterlocutorCell.vue
  src/core/components/courses/LearnerCreationModal.vue
  src/core/components/courses/ProfileBilling.vue
  src/core/components/courses/ProfileOrganization.vue
  src/core/components/courses/ProfileTraineeFollowUp.vue
  src/core/components/courses/SlotContainer.vue
  src/core/components/courses/TraineeContainer.vue
  src/core/components/courses/TraineeEditionModal.vue
  src/core/components/courses/TraineeTable.vue
  src/core/components/courses/TrainerMissionCreationModal.vue
  src/core/components/form/PhoneSelect.vue
  src/core/components/learners/ProfileInfo.vue
  src/core/components/table/AttendanceTable/Composables/AttendanceSheets.js
  src/core/components/table/AttendanceTable/index.vue
  src/core/components/table/CoachCreationModal.vue
  src/core/components/table/CoachEditionModal.vue
  src/core/components/table/CoachList.vue
  src/core/components/table/CompletionCertificateTable.vue
  src/core/composables/completionCertificates.js
  src/core/composables/courseCreation.js
  src/core/composables/courseFilters.js
  src/core/composables/courses.js
  src/core/composables/learnerDirectory.js
  src/core/composables/learnersCreation.js
  src/core/composables/user.js
  src/core/data/constants.js
  src/core/data/countryCodes.js
  src/core/helpers/ability.js
  src/core/helpers/dates/utils.js
  src/core/helpers/rbac.js
  src/core/helpers/utils.js
  src/core/helpers/vuelidateCustomVal.js
  src/core/pages/AccountInfo.vue
  src/modules/vendor/components/billing/CourseBillCreationModal.vue
  src/modules/vendor/components/billing/CourseBillValidationModal.vue
  src/modules/vendor/components/billing/CourseBillingCard.vue
  src/modules/vendor/components/billing/CourseFeeEditionModal.vue
  src/modules/vendor/components/courses/CompletionCertificateAdditionModal.vue
  src/modules/vendor/components/courses/CourseCreationModal.vue
  src/modules/vendor/components/holdings/ProfileInfo.vue
  src/modules/vendor/components/programs/TesterCreationModal.vue
  src/modules/vendor/components/programs/TesterTable.vue
  src/modules/vendor/components/trainers/ProfileContract.vue
  src/modules/vendor/components/trainers/ProfileInfo.vue
  src/modules/vendor/mixins/menuItemsMixin.js
  src/modules/vendor/pages/ni/billing/CompletionCertificatesDashboard.vue
  src/modules/vendor/pages/ni/billing/MainConfig.vue
  src/modules/vendor/pages/ni/management/BlendedCoursesDirectory.vue
  src/modules/vendor/pages/ni/management/SingleCourseDirectory.vue
  src/modules/vendor/router/routes.js
  src/store/course.js
Labels: staging

#2158 COM-3968: fix bugs
  src/core/components/courses/ProfileTraineeFollowUp.vue
  src/modules/vendor/components/courses/CourseCreationModal.vue
  src/modules/vendor/pages/ni/management/SingleCourseDirectory.vue
Labels: bug

#2159 Dev
  src/core/components/courses/ProfileTraineeFollowUp.vue
  src/modules/vendor/components/courses/CourseCreationModal.vue
  src/modules/vendor/pages/ni/management/SingleCourseDirectory.vue
Labels: staging

#2160 Com 3962
  .eslintignore
  .eslintrc.js
  eslint.config.mjs
  package-lock.json
  package.json
  quasar.conf.js
  src/core/api/Courses.js
  src/core/components/PictureUploader.vue
  src/core/components/courses/ProfileBilling.vue
  src/core/components/courses/ProfileOrganization.vue
  src/core/components/form/Input.vue
  src/core/components/menu/SideMenuFooter.vue
  src/core/components/table/AttendanceTable/Composables/AttendanceSheets.js
  src/core/composables/companyDetachment.js
  src/core/composables/login.js
  src/core/helpers/alenvi.js
  src/core/helpers/utils.js
  src/core/mixins/userMixin.js
  src/core/pages/404.vue
  src/modules/client/pages/ni/courses/LearnersDirectory.vue
  src/modules/vendor/components/trainers/ProfileInfo.vue
  src/modules/vendor/composables/CardTemplate.js
  src/modules/vendor/pages/ni/billing/CompletionCertificatesDashboard.vue
  src/modules/vendor/pages/ni/users/trainers/TrainersDirectory.vue
  test/cypress/integration/authenticate.spec.js
  test/cypress/support/commands.js
Labels: dependencies

#2161 Dev
  .eslintignore
  .eslintrc.js
  eslint.config.mjs
  package-lock.json
  package.json
  quasar.conf.js
  src/core/api/Courses.js
  src/core/components/PictureUploader.vue
  src/core/components/courses/ProfileBilling.vue
  src/core/components/courses/ProfileOrganization.vue
  src/core/components/form/Input.vue
  src/core/components/menu/SideMenuFooter.vue
  src/core/components/table/AttendanceTable/Composables/AttendanceSheets.js
  src/core/composables/companyDetachment.js
  src/core/composables/login.js
  src/core/helpers/alenvi.js
  src/core/helpers/utils.js
  src/core/mixins/userMixin.js
  src/core/pages/404.vue
  src/modules/client/pages/ni/courses/LearnersDirectory.vue
  src/modules/vendor/components/trainers/ProfileInfo.vue
  src/modules/vendor/composables/CardTemplate.js
  src/modules/vendor/pages/ni/billing/CompletionCertificatesDashboard.vue
  src/modules/vendor/pages/ni/users/trainers/TrainersDirectory.vue
  test/cypress/integration/authenticate.spec.js
  test/cypress/support/commands.js
Labels: staging

#2164 COM-3971: can add price to course at creation
  src/core/composables/courseCreation.js
  src/modules/vendor/components/courses/CourseCreationModal.vue
  src/modules/vendor/pages/ni/management/BlendedCoursesDirectory.vue
  src/modules/vendor/pages/ni/management/SingleCourseDirectory.vue
Labels: dev
