Repository CompaniTech/compani-webapp, pull requests merged in 2025-08, with the labels that each got.

#2217 MES - 06/08/2025
  src/core/components/courses/ProfileBilling.vue
  src/core/composables/courseBills.js
  src/modules/vendor/components/billing/CourseBillCreationModal.vue
  src/modules/vendor/components/billing/MultipleCourseBillEditionModal.vue
Labels: master

#2218 COM-4027: can generate attendance sheet
  src/core/components/table/AttendanceTable/Composables/AttendanceSheets.js
  src/core/components/table/AttendanceTable/index.vue
Labels: dev

#2227 COM-4041 - add ics in Compani info
  src/core/helpers/vuelidateCustomVal.js
  src/modules/vendor/pages/ni/billing/MainConfig.vue
Labels: dev

#2228 Com 4042
  src/core/api/VendorCompanies.js
  src/core/data/constants.js
  src/modules/vendor/pages/ni/billing/MainConfig.vue
Labels: dev

#2229 Com 4043
  src/core/api/Companies.js
  src/modules/vendor/components/companies/ProfileInfo.vue
Labels: dev

#2230 Com 4045
  src/core/api/Companies.js
  src/core/api/GoogleDrive.js
  src/modules/vendor/components/companies/ProfileInfo.vue
Labels: dev

#2233 COM-4045: minor changes
  src/core/data/constants.js
Labels: bug
