Repository CompaniTech/compani-webapp, pull requests merged in 2025-01, with the labels that each got.

#2097 COM-3856: can generate file
  src/core/components/table/AttendanceTable/Composables/AttendanceSheets.js
  src/core/components/table/AttendanceTable/index.vue
Labels: dev

#2102 COM-3858: edit deletion message
  src/core/components/table/AttendanceTable/Composables/AttendanceSheets.js
Labels: dev

#2103 COM-3770: rename field correct in isCorrect
  src/core/helpers/vuelidateCustomVal.js
  src/modules/vendor/components/programs/cards/templates/FillTheGaps.vue
  src/modules/vendor/components/programs/cards/templates/MultipleChoiceQuestion.vue
  src/modules/vendor/components/programs/cards/templates/SingleChoiceQuestion.vue
  src/modules/vendor/composables/CardTemplate.js
Labels: dev

#2105 COM-3874: move first slot to plan and change warning message
  src/core/components/courses/SlotContainer.vue
Labels: bug

#2108 MES 16/01/2025
  package-lock.json
  package.json
  quasar.conf.js
  src/core/api/Courses.js
  src/core/components/courseBilling/CourseBillingInfos.vue
  src/core/components/courses/AttendanceSheetAdditionModal.vue
  src/core/components/courses/CourseCell/index.vue
  src/core/components/courses/InterlocutorCell.vue
  src/core/components/courses/InterlocutorModal.vue
  src/core/components/courses/MultipleSlotCreationModal.vue
  src/core/components/courses/ProfileBilling.vue
  src/core/components/courses/ProfileOrganization.vue
  src/core/components/courses/ProfileTraineeFollowUp.vue
  src/core/components/courses/SlotContainer.vue
  src/core/components/courses/SmsCell.vue
  src/core/components/courses/TrainerMissionInfosModal.vue
  src/core/components/courses/TrainingContractContainer.vue
  src/core/components/courses/TrainingContractInfosModal.vue
  src/core/components/learners/ProfileCourses.vue
  src/core/components/table/AttendanceTable/Composables/AttendanceSheets.js
  src/core/components/table/AttendanceTable/index.vue
  src/core/composables/courseFilters.js
  src/core/composables/courses.js
  src/core/helpers/vuelidateCustomVal.js
  src/css/interlocutor.sass
  src/modules/client/mixins/configMixin.js
  src/modules/client/pages/ni/config/CompanyConfig.vue
  src/modules/notLogged/pages/QuestionnaireForm.vue
  src/modules/vendor/components/companies/ProfileInfo.vue
  src/modules/vendor/components/programs/cards/templates/FillTheGaps.vue
  src/modules/vendor/components/programs/cards/templates/MultipleChoiceQuestion.vue
  src/modules/vendor/components/programs/cards/templates/SingleChoiceQuestion.vue
  src/modules/vendor/components/questionnaires/ProfileAnswers.vue
  src/modules/vendor/components/questionnaires/SelfPositionningItem.vue
  src/modules/vendor/components/trainers/ProfileContract.vue
  src/modules/vendor/composables/CardTemplate.js
  src/modules/vendor/pages/ni/config/MainConfig.vue
  src/modules/vendor/pages/ni/pedagogy/QuestionnaireAnswersProfile.vue
  src/modules/vendor/pages/trainers/management/SelfPositionningAnswersProfile.vue
  src/modules/vendor/router/routes.js
  src/router/routes.js
  src/store/course.js
Labels: master

#2109 COM-3881: add TutorModal in ProfieOrganization
  src/core/api/Courses.js
  src/core/components/courses/InterlocutorCell.vue
  src/core/components/courses/ProfileOrganization.vue
  src/core/data/constants.js
Labels: dev

#2112 COM-3882: display tutor courses
  src/core/components/courseBilling/CourseBillingInfos.vue
  src/core/components/learners/ProfileCourses.vue
  src/modules/client/router/routes.js
  src/modules/vendor/router/routes.js
Labels: dev
